### ISSUE TITLE
which address standard will use? cashAddr, bitpay style or bitcoin legacy?

### ISSUE THREAD

**Issue by mrbianchi** [bitcoin-sv/bitcoin-sv#10]

**Comment by Danconnolly** [comment]
Bitcoin SV is an implementation of Bitcoin Cash. We will continue with the cashaddr style of addresses.

**Comment by priestc** [comment]
> We will continue with the cashaddr style of addresses.

Bad idea. Could this please be reconsidered? Base58 is Satoshi's invention. If this project is really going for the goal of "Satoshi's Vision", then Base58 is what should be used.

**Comment by mboyd1** [comment]
any chance to revisit this now that we are cleanly separated from the BCH ticker and 'Cash' name?  I would support a return to legacy base58 addresses
