### ISSUE TITLE
Excuse me, is there any documentation of the RPC interface

### ISSUE THREAD

**Issue by shawnshawnshawn** [bitcoin-sv/bitcoin-sv#103]
I searched for a long time, but I didn't find it.

**Comment by Danconnolly** [comment]
The `bitcoin-cli` tool uses the RPC commands. If you type `bitcoin-cli help` you will get a list of commands. Then try `bitcoin-cli help <command>` and you will get a description of the command with RPC examples.

I hope that helps.
