### ISSUE TITLE
Compile error windows

### ISSUE THREAD

**Issue by comilionas** [bitcoin-sv/bitcoin-sv#107]
I tried to compile 'bitcoin-sv-0.2.2.beta' according the "build-windows.md" manual.

I get an error message i tried to compile with the following command:
cmake  -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake  -G "Visual Studio 15 2017 Win64"  -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release

```
...

-- Boost version: 1.71.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Performing Test BOOST_TEST_DYN_LINK
-- Performing Test BOOST_TEST_DYN_LINK - Failed
-- BerkeleyDB libs: C:/vcpkg/installed/x64-windows-static/lib/libdb48.lib
-- Found BerkeleyDB: C:/vcpkg/installed/x64-windows-static/include
-- libevent: C:/vcpkg/installed/x64-windows-static/lib/event.lib
-- ZeroMQ lib: ZMQ_LIBRARY-NOTFOUND
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZeroMQ (missing: ZMQ_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindZeroMQ.cmake:22 (find_package_handle_standard_args)
  C:/vcpkg/installed/x64-windows-static/share/zeromq/vcpkg-cmake-wrapper.cmake:1 (_find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:218 (include)
  src/zmq/CMakeLists.txt:13 (find_package)
```

### Machine specs:
- OS: Windows 10
- CPU: i7-8700
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

**Comment by xianxiongwang** [comment]
Could NOT find ZeroMQ (missing: ZMQ_LIBRARY

**Comment by xianxiongwang** [comment]
Could NOT find ZeroMQ (missing: ZMQ_LIBRARY ） ，没有找到zmq lib。

**Comment by comilionas** [comment]
I used the following build cmd (like written in build-windows.md)
`cmake  -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake  -G "Visual Studio 15 2017 Win64"  -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release ..`

Its stated there:

> The CMAKE_BUILD_TYPE parameter is required. Without it, VCPKG will put both debug and release libraries on linkers search path. This will cause problems at link time, since BerkleyDB uses same file name for debug and release libraries (libdb48.lib).

But it seems, BerkleyDB still makes troubles here... 

ZeroMQ is installed because i followed according the instruction and installed the package with the following cmd:
`vcpkg install --triplet x64-windows-static boost-filesystem boost-signals2 boost-test boost-program-options boost-interprocess boost-random boost-assign boost-uuid libevent openssl zeromq berkeleydb`

**Comment by MaxKot** [comment]
If you have checked out vcpkg from the master branch, it is likely too contain a newer version of ZeroMQ than supported by the Bitcoin SV build scripts. You have to add your version of ZeroMQ to `cmake\modules\FindZeroMQ.cmake` file. You can check the installed ZeroMQ version in `c:\vcpkg\installed\x64-windows-static\lib`. Another solution is to downgrade your vcpkg to an older version. Since the build-windows.md was last edited in May, 2019, I used vcpkg release would be 2019.06 (there are no earlier releases of vcpkg).

I think `git clone https://github.com/Microsoft/vcpkg.git` command in build-windows.md should include the `--branch` parameter with the tag or commit in vcpkg that was tested and is known to be supported by the Bitcoin SV build scripts.

**Comment by Danconnolly** [comment]
Closing this issue. 

I think the documentation for compiling on Windows has been improved. We do have developers using Windows and Visual Studio and will support this platform for development.
