### ISSUE TITLE
How to validate q address 

### ISSUE THREAD

**Issue by peysab** [bitcoin-sv/bitcoin-sv#108]
Hello,

I'm running a mining pool for BSV ( https://persianmine.com/pool/en/#bsv/stats )

My problem is the wallets starting with q are not getting validated for example:
bitcoin-cli  validateaddress "1E8rxamBV3NX5D1fkzg1BzNh8k2ac5JqD2" results in:
```{
  "isvalid": true,
  "address": "1E8rxamBV3NX5D1fkzg1BzNh8k2ac5JqD2",
  "scriptPubKey": "76a9149016400155ec24156559e5fa159791c6e4c6de2088ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "02c203ca907882428fbe1dca79481ed743bc8d465f207f8a6fb2be8ade6f1fd42a",
  "iscompressed": true,
  "account": "",
  "timestamp": 1571643376,
  "hdkeypath": "m/0'/0'/0'",
  "hdmasterkeyid": "ad4719ddd83d567aaf718c90b5bb2147a309e9db"
}
```
but :
bitcoin-cli validateaddress "qrgf9udh3fmnwh6mmvl7ad7w6q64l9ssc5jr845znh"
results in : 
```
{
  "isvalid": false
}
```

I even tried to set usecashaddr to 0 and 1 and both had same results.
since most of the exchanges and wallets like coinomi only supporting the q address how can I fix that issue?

Thanks

**Comment by peysab** [comment]
Anyone?

**Comment by Danconnolly** [comment]
The q address format is a Bitcoin Cash extension. I'm sorry but the Bitcoin SV Node implementation does not support this format.

**Comment by peysab** [comment]
@Danconnolly , Thanks for your reply, but why some exchanges or even wallets like coinomi, they only support q address for bsv and not generating the other types? only q address.

**Comment by peysab** [comment]
Anyone?

**Comment by pinpins** [comment]
Is that possible to add support?

**Comment by Danconnolly** [comment]
I'm sorry but we're not going to add support for the Bitcoin Cash format addresses, these addresses are specific to Bitcoin Cash.

**Comment by Danconnolly** [comment]
For the Coinomi wallet specifically, please see this help page: https://coinomi.freshdesk.com/support/solutions/articles/29000018980-new-bch-address-format
