### ISSUE TITLE
Is there an Ubuntu PPA (or apt source) available?

### ISSUE THREAD

**Issue by boldandbusted** [bitcoin-sv/bitcoin-sv#11]
Thanks! :)

**Comment by Danconnolly** [comment]
We will add this feature in the future.

**Comment by daengx** [comment]
In that case use Ubuntu container https://snapcraft.io not ppa to minimize dependencies

**Comment by kanakan34** [comment]
what is the rpc port number of bitcoin sv

**Comment by Danconnolly** [comment]
default RPC is 8322.

**Comment by kanakan34** [comment]
thank you for your quick reply

**Comment by Danconnolly** [comment]
:-)

**Comment by Danconnolly** [comment]
sorry about that.
