### ISSUE TITLE
High memory usage with -reindex option

### ISSUE THREAD

**Issue by jolonf** [bitcoin-sv/bitcoin-sv#112]
When running bitcoind with `-reindex` it uses about 40GB of RAM on mainnet. This appears to be unnecessarily high. After indexing has finished and restarting the node, the memory usage is less than 400MB which seems to indicate that it is not freeing the memory allocated during the reindex process. Memory usage when indexing testnet is much lower indicating that it is proportional to the size of the blockchain.

This bug appears to have been fixed in bitcoin-core shortly after the BCH fork:

https://github.com/bitcoin/bitcoin/issues/11822

I think the relevant fix for the memory leak is this line which is not present in bitcoin-sv:

https://github.com/TheBlueMatt/bitcoin/blob/97d2b09c124e6e5803f7fd4503348d9710d1260f/src/validation.cpp#L2575

#### If so, please list the steps to reproduce below:
bitcoind -reindex -txindex

### Expected behaviour
Memory usage should be somewhat contained, and at the very least freed after the indexing process.

### Actual behaviour
Memory usage climbs to around 40GB at end of indexing and doesn't drop unless bitcoind is restarted.

### What version of bitcoin-sv are you using?
0.2.1

### Machine specs:
- OS: Ubuntu 19.10
- CPU: i3-8109U
- RAM: 32GB
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Comment by Danconnolly** [comment]
Thank you. We'll look into this straight away.

**Comment by gWOLF3** [comment]
Has this been fixed in 1.0.1?

**Comment by Danconnolly** [comment]
This is fixed in the next release, 1.0.2.

**Comment by Danconnolly** [comment]
Version 1.0.2 has been released.
