### ISSUE TITLE
So, is the bug bounty program really active?

### ISSUE THREAD

**Issue by seceine** [bitcoin-sv/bitcoin-sv#117]
Today I read a post on bitcoinsv.io claiming the bug bounty program is active, but my reports and all e-mails to security@bitcoinsv.io have been ignored for months after a single initial reply.

I'm still waiting for any update on BSVRD-713 and BSVD-593, both submitted on March this year.

**Comment by Danconnolly** [comment]
Yes, the bug bounty programme is active. We're planning to publish a summary of the effectiveness of this programme in the new year.

Of those two reports, one has been addressed and one has been partially addressed and we expect a full mitigation soon. This is from memory, I will e-mail a more complete response after Christmas.

The one that has not been fully addressed is the last one of the vulnerabilities that have been responsibly disclosed and a particularly complex one. I dont want to get into details here.
