### ISSUE TITLE
Can I make use of an existing Bitcoin Cash (ABC) blockchain directory?

### ISSUE THREAD

**Issue by boldandbusted** [bitcoin-sv/bitcoin-sv#12]
Or must I re-download the whole blockchain again when standing up a new SV node? Thanks in advance.

**Comment by Klar** [comment]
I just pointed my current ux bitcoin data (bitcoin.conf, wallet.dat, blockchain...) to the sv-node, working as expected, so yes.

**Comment by Danconnolly** [comment]
As of ABC version 0.17.2 and SV version 0.1.0, you can use a copy of the ABC block data. Data downloaded by later versions of ABC may also work but this is not a feature we intend to maintain.
