### ISSUE TITLE
Test failure on MacOSX

### ISSUE THREAD

**Issue by kyuupichan** [bitcoin-sv/bitcoin-sv#124]
### Describe the issue
Test failure + stoll exception

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
./configure && make && make check

### Expected behaviour
Tests pass

### Actual behaviour
One failure plus a weird diagnostic about **stoll**

### What version of bitcoin-sv are you using?
v1.0.0.beta2

### Machine specs:
- OS: MacOSX
- CPU: x86
- RAM: 32GB
- Disk size: 3TB
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
==========================================
   Bitcoin SV 1.0.0: src/test-suite.log
==========================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

************************
EXCEPTION: St16invalid_argument       
stoll: no conversion       
bitcoin in ArgsManager::GetArg       

************************
EXCEPTION: St16invalid_argument       
stoll: no conversion       
bitcoin in ArgsManager::GetArg       

Running 449 test cases...
test/threadpool_tests.cpp:111: error: in "TestThreadPool/Prioritised": check taskResults == expectedResults has failed
JSON NESTING DEPTH exceed 3 > 2

*** 1 failure is detected in the test module "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)

**Comment by Danconnolly** [comment]
Pull request https://github.com/bitcoin-sv/bitcoin-sv/pull/123
Included in v1.0.1
