### ISSUE TITLE
Genesis does not compile on i686

### ISSUE THREAD

**Issue by xloem** [bitcoin-sv/bitcoin-sv#126]
This issue tracker is only for technical issues related to bitcoin-sv.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
Cannot build master on 32-bit x86; encounter compilation error.

#### If so, please list the steps to reproduce below:
1. checkout master on i686
2. mkdir build; cd build; cmake ..; make

### Expected behaviour
Tell us what should happen
Should build bitcoind.

### Actual behaviour
Tell us what happens instead

    src/big_int.cpp:469:43: error: static assertion failed
      469 |     static_assert(sizeof(unique_asn1_ptr) == 8);

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-sv are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

This is tag v1.0.0 7fd177c7c443

### Machine specs:
- OS: Foreign GUIX on Fedora 18
- CPU: VIA C7-M 1GHz
- RAM: 1GB with 4GB swap
- Disk size: Compile was run on 100GB disk
- Disk Type (HD/SDD): Flash

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `bitcoind.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
I may look at this more and try to patch it and submit a PR but do not hold your breath.

**Comment by coolbobo** [comment]
root@stage-bch-node:~/.bitcoin# bitcoin-cli listunspent 0
error code: -2
error message:
Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.

who know why?

**Comment by coolbobo** [comment]
my bsv node version is :Bitcoin SV RPC client version v1.0.0

**Comment by Danconnolly** [comment]
I'm sorry but we don't support 32-bit systems.

**Comment by Danconnolly** [comment]
@coolbobo please don't add to another issue, please create a separate issue, or it gets very confusing.

**Comment by xloem** [comment]
I tried commenting out that 64-bit-assuming assertion and it is compiling and running fine over here.  Would you accept a PR if I could discern the reason for the assertion and make sure it was still met on 32-bit?

**Comment by Danconnolly** [comment]
We'll accept PR's for 32-bit compatibility as long as they do not have a large impact on the code.

**Comment by Danconnolly** [comment]
Thank you for the PR but I'm sorry, I'm going to have to backtrack on this.

32-bit software is limited to 4GB RAM. This just isn't enough. The current Genesis Test network will not validate using 32-bit software. Block 5095 has a single transaction that is 1GB in size and will not validate with 4GB RAM. I have compiled a 32-bit version and tested it. See also #127.

Although a 32-bit may be able to validate the mainnet blockchain at the current time (although I have some doubts, there have been some large blocks), I doubt very much that it will be able to validate the blockchain after Genesis activation.

So, I'm sorry but we are going to completely withdraw 32-bit support. Thank you for the work you did on this, I'm sorry that it will not be used.
