### ISSUE TITLE
Corrupt block on Genesis Testnet?

### ISSUE THREAD

**Issue by g574** [bitcoin-sv/bitcoin-sv#127]
#### Describe the issue
I've set up a GT node as of this [guide](https://bitcoinsv.io/wp-content/uploads/2020/01/stable_GT_eng.pdf).
The synchronisation stops at block nr 5094.

### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
1. Built new bitcoin-sv version 1.0.0
2. Configured it to use Genesis Testnet
3. Tried to delete the downloaded data and start synchronisation again. It always stops at block 5094.
The log says:
```
Loaded best chain: hashBestChain=0000000049eada007d89763d32706346c6d92c68cf075346fe90f622d1cac026 height=5094 date=2020-01-07 11:33:27 progress=-0.000000 ...
...
New outbound peer connected: version: 70015, blocks=6444, peer=11
Peer=9 is stalling block download, disconnecting
```
These last two lines are repeated several times. The "blocks=" part shows the expected block height but the synchronisation stops.
It can be confirmed with `bitcoin-cli getinfo`
```
{
  "version": 101000000,
  "protocolversion": 70015,
  "blocks": 5094,
  "timeoffset": 0,
  "connections": 1,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "stn": true,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000250,
  "errors": "",
  "maxblocksize": 9223372036854775807,
  "maxminedblocksize": 128000000,
  "maxstackmemoryusagepolicy": 9223372036854775807,
  "maxstackmemoryusageconsensus": 9223372036854775807
}
```

### Expected behaviour
The sync should continue and `getinfo` should show the up to date height.

### Actual behaviour
The current blockheight is displayed but not synced.

### What version of bitcoin-sv are you using?
v1.0.0

### Any extra information that might be useful in the debugging process.
I compare my results to https://gt.whatsonchain.com/.
Interestingly enough, here we can't display block 5095, either.
[5094](https://gt.whatsonchain.com/block-height/5094) works, but [5095](https://gt.whatsonchain.com/block-height/5094) does not.

**Comment by Danconnolly** [comment]
Block 5095 is 1GB with a single transaction (not including coinbase) and can cause issues.

Try `bitcoin-cli addnode 159.89.163.191 add`. Let me know how it goes.

```
{
  "tx": [
    "047c853a63e291aef8e870ff5f1717709d4d882db57f7b4201a5a0a6ab895601",
    "3c97bb66ce0eed26ccd0028f18cd81289863cea44f01cea09b1f019c83a9f4c9"
  ],
  "hash": "00000000594e67e882de82f9e65f1758b57c16308f2ecef8fa7f209226e9df33",
  "confirmations": 1354,
  "size": 999999398,
  "height": 5095,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "a844b40e0de59da4a4c9d67951dc081b4e1d35f41fe5042e03e98bd6ef397a4c",
  "time": 1578397247,
  "mediantime": 1578393617,
  "nonce": 3529035009,
  "bits": "1d00ffff",
  "difficulty": 1,
  "chainwork": "00000000000000000000000000000000000000000000000000001d401f4422d8",
  "previousblockhash": "0000000049eada007d89763d32706346c6d92c68cf075346fe90f622d1cac026",
  "nextblockhash": "00000000fd4e20d829087b1b04cb3dd7e4eaeba433a5122613df00c55afdbe77"
}
```

**Comment by g574** [comment]
hi @Danconnolly ,
I've added the node, but it did not help. I still see the same things in the log.
I've also tried to add assumevalid=<hash> with the code of 5095 and 5096 but it made no difference. Is there anything else I can try?

**Comment by g574** [comment]
Some additional info:
I changed `excessiveblocksize=10000000000` to `excessiveblocksize=0` and it allowed me twice to synchronise but it is not reliable. If I try to resynchronise it, it still fails quite often.

**Comment by Danconnolly** [comment]
how much RAM do you have? (including swap)

**Comment by g574** [comment]
I have 64 Gb RAM + 2 Gb swap but it is currently only using 12 Gb RAM and no swap.

**Comment by Danconnolly** [comment]
I've tried to replicate this error but have been unable to.

**Comment by Danconnolly** [comment]
This issue is being looked into.

**Comment by g574** [comment]
Great. Thank you very much.
