### ISSUE TITLE
Running 1.0.0 in docker fails to start

### ISSUE THREAD

**Issue by andrewtoth** [bitcoin-sv/bitcoin-sv#128]
Running in docker, version 1.0.0 outputs:
```
bitcoind: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by bitcoind)
```
Previous versions did not have this issue. We're using the binary downloaded from https://download.bitcoinsv.io/bitcoinsv/1.0.0/bitcoin-sv-1.0.0-x86_64-linux-gnu.tar.gz.

**Comment by Danconnolly** [comment]
Have you tried the docker images from https://hub.docker.com/r/bitcoinsv/bitcoin-sv ?

**Comment by andrewtoth** [comment]
We have not. I can't find the source for those docker images. We're trying to run in `debian:stretch-slim`.

**Comment by andrewtoth** [comment]
Using base image `debian:buster-slim` has the correct `GLIBC` version.

**Comment by KyleFromOhio** [comment]
getting same error "version `GLIBC_2.25' not found". Same binaries. Not using docker.

**Comment by Danconnolly** [comment]
The docker build files come from https://github.com/bitcoin-sv/docker-sv

Yes, a newer base image works. I'm glad you solved it and assume that everything is working well now.

**Comment by abyssal0** [comment]
Not using docker.
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/wallet/bsv/bitcoin-sv-1.0.1/bin/bitcoind)
libc6 is already the newest version (2.23)

**Comment by abyssal0** [comment]
docker run bitcoinsv/bitcoin-sv
Mandatory consensus parameter is not set. In order to start bitcoind you must set the following consensus parameters: "excessiveblocksize" and "maxstackmemoryusageconsensus". In order to start bitcoind with no limits you can set both of these parameters to 0 however it is strongly recommended to ensure you understand the implications of this setting.

**Comment by Danconnolly** [comment]
These settings must be configured, please see https://bitcoinsv.io/choosing-consensus-settings/.

**Comment by Danconnolly** [comment]
Please don't attach to an unrelated issue, please open a new one. Closing this.

**Comment by AlexWwt** [comment]
Run docker run bitcoinsv/bitcoin-sv
getblockchaininfo:
```
{
  "chain": "main",
  "blocks": 620538,
  "headers": 621881,
  "bestblockhash": "000000000000000001618b0a11306363725fbb8dbecbb0201c2b4064cda00790",
  "difficulty": 527693112605.6401,
  "mediantime": 1580777491,
  "verificationprogress": 0.9937911402493528,
  "chainwork": "000000000000000000000000000000000000000000f7efb81ff145add78f231f",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    },
    {
      "id": "csv",
      "version": 5,
      "reject": {
        "status": true
      }
    }
  ]
}
```
getnetworkinfo:
```
{
  "version": 101000100,
  "subversion": "/Bitcoin SV:1.0.1/",
  "protocolversion": 70015,
  "localservices": "0000000000000025",
  "localrelay": true,
  "timeoffset": 0,
  "txnpropagationfreq": 250,
  "txnpropagationqlen": 0,
  "networkactive": true,
  "connections": 11,
  "addresscount": 57121,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000250,
  "excessutxocharge": 0.00000000,
  "localaddresses": [
  ],
  "warnings": ""
}
```
But NOT synchronized:
```
[bitcoin-msghand] New outbound peer connected: version: 70015, blocks=621671, peer=11
[bitcoin-msghand] ERROR: AcceptBlockHeader: block 000000000000000000ab6dd91fba22c92aa2c07cd26fb9d5863a37f7a6ee37db is marked invalid
[bitcoin-msghand] ERROR: invalid header received
[bitcoin-msghand] New outbound peer connected: version: 70015, blocks=621671, peer=12
[bitcoin-msghand] ERROR: AcceptBlockHeader: block 000000000000000000ab6dd91fba22c92aa2c07cd26fb9d5863a37f7a6ee37db is marked invalid
[bitcoin-msghand] ERROR: invalid header received

```

Why and how to fix it?

**Comment by Danconnolly** [comment]
Can you should me the output of ` bitcoin-cli getblockheader 000000000000000000ab6dd91fba22c92aa2c07cd26fb9d5863a37f7a6ee37db`?

**Comment by AlexWwt** [comment]
```
{
  "hash": "000000000000000000ab6dd91fba22c92aa2c07cd26fb9d5863a37f7a6ee37db",
  "confirmations": -1,
  "height": 620539,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "17808dfa3635608f53de7d9538029b31205f0fad0471fba5a01f16381ec6fd6c",
  "time": 1580781330,
  "mediantime": 1580777547,
  "nonce": 2852668029,
  "bits": "18021f77",
  "difficulty": 517918840529.158,
  "chainwork": "000000000000000000000000000000000000000000f7f030b6c83355eda78670",
  "previousblockhash": "000000000000000001618b0a11306363725fbb8dbecbb0201c2b4064cda00790"
}
```

**Comment by Danconnolly** [comment]
Looks ok, apart from validity that is.

Can you try `bitcoin-cli reconsiderblock 000000000000000000ab6dd91fba22c92aa2c07cd26fb9d5863a37f7a6ee37db`

**Comment by AlexWwt** [comment]
Works.
Thank you.

**Comment by Danconnolly** [comment]
Wonderful, glad to hear it and thanks for responding.
