### ISSUE TITLE
v1.0.0 version can not getbalance

### ISSUE THREAD

**Issue by coolbobo** [bitcoin-sv/bitcoin-sv#129]
root@stage-bsv-node:/home/jim# bitcoin-cli --version
Bitcoin SV RPC client version v1.0.0
root@stage-bsv-node:/home/jim# bitcoin-cli listunspent 0
error code: -2
error message:
Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.
root@stage-bsv-node:/home/jim# bitcoin-cli getbalance
error code: -2
error message:
Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.

why ?

**Comment by nxtreaming** [comment]
because BSV is a garbage. forget it!

**Comment by Danconnolly** [comment]
Which network are you on? Testnet?

**Comment by coolbobo** [comment]
> Which network are you on? Testnet?

mainnet

**Comment by coolbobo** [comment]
hi, who know this issue?

**Comment by Danconnolly** [comment]
Your software is in "safe" mode. It can enter safe mode when it detects that there may be another longer chain. When its in safe mode some functions are disabled, including wallet functions.

We need to find out why it is in safe mode.

Please can you supply the output of `bitcoin-cli getnetworkinfo` and `bitcoin-cli getblockchaininfo`.

**Comment by coolbobo** [comment]
@Danconnolly

**Comment by coolbobo** [comment]
root@stage-bsv-node:/home/jim# bitcoin-cli getnetworkinfo
{
  "version": 101000000,
  "subversion": "/Bitcoin SV:1.0.0/",
  "protocolversion": 70015,
  "localservices": "0000000000000025",
  "localrelay": true,
  "timeoffset": 0,
  "txnpropagationfreq": 250,
  "txnpropagationqlen": 4,
  "networkactive": true,
  "connections": 8,
  "addresscount": 34326,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000250,
  "excessutxocharge": 0.00000000,
  "localaddresses": [
  ],
  "warnings": "Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade."
}
root@stage-bsv-node:/home/jim# bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 618377,
  "headers": 618377,
  "bestblockhash": "0000000000000000018abc7d06728f5627d0af4a6d13de94d7a527e249ceb21a",
  "difficulty": 436412440880.9841,
  "mediantime": 1579481375,
  "verificationprogress": 0.9999950773477883,
  "chainwork": "000000000000000000000000000000000000000000f476e6386cdde0817d42f7",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    },
    {
      "id": "csv",
      "version": 5,
      "reject": {
        "status": true
      }
    }
  ]
}

**Comment by coolbobo** [comment]
i just download 1.0.0 bin version by this url:
https://download.bitcoinsv.io/bitcoinsv/1.0.0/bitcoin-sv-1.0.0-x86_64-linux-gnu.tar.gz

**Comment by RayOshow** [comment]
I have had same problem.
Although I clean all data for Genesis bitcoin daemon.
I'm now reindexing all blocks data.
After that I will write down the result.

**Comment by coolbobo** [comment]
> I have had same problem although I had cleaned all data for Genesis bitcoin daemon in advance.
> I'm now reindexing all blocks data.
> After that I will write down the result.

any update ?

**Comment by coolbobo** [comment]
bitcoind -daemon start about 15min,  bitcoin-cli getbalance work fine.
pass 15min after, bitcoin-cli getbalance can not work.

show bitcoind.log logs:
2020-01-20 09:54:29 [bitcoin-net] socket recv error Connection reset by peer (104)
2020-01-20 09:54:36 [bitcoin-msghand] New outbound peer connected: version: 70015, blocks=618427, peer=15
2020-01-20 09:58:26 [bitcoin-msghand] ERROR: AcceptBlockHeader: block 0000000000000000004626ff6e3b936941d341c5932ece4357eeccac44e6d56c is marked invalid
2020-01-20 09:58:26 [bitcoin-msghand] ERROR: invalid header received
2020-01-20 10:00:03 [bitcoin-txnvalidator] AddToWallet 5b8e0fc2fe44730e2354d1b46c1118b4ed1c1947ad83748c7759b1ae5e20a440  new
2020-01-20 10:05:30 [bitcoin-opencon] connect() to [2a02:2528:503:2::14]:8333 failed: Network is unreachable (101)
2020-01-20 10:06:49 [bitcoin-worker1-N-CAsyncTaskPool] UpdateTip: new best=00000000000000000075557edce574e2f20ba81d2e3f06ac01f777371dfd29ea height=618428 version=0x20800000 log2_work=87.933946 tx=341456872 date='2020-01-20 10:05:55' progress=0.999999 cache=4.3MiB(31757txo) warning='56 of last 100 blocks have unexpected version'
2020-01-20 10:06:49 [bitcoin-worker1-N-CAsyncTaskPool] CheckForkWarningConditions: Warning: Found invalid chain at least ~6 blocks longer than our best chain.
Chain state database corruption likely.
2020-01-20 10:06:49 [bitcoin-worker1-N-CAsyncTaskPool] AddToWallet 5b8e0fc2fe44730e2354d1b46c1118b4ed1c1947ad83748c7759b1ae5e20a440  update
2020-01-20 10:06:58 [bitcoin-net] socket recv error Connection reset by peer (104)
2020-01-20 10:06:59 [bitcoin-net] socket recv error Connection reset by peer (104)
2020-01-20 10:06:59 [bitcoin-msghand] New outbound peer connected: version: 70015, blocks=609161, peer=20
2020-01-20 10:07:00 [bitcoin-opencon] connect() to 147.30.12.96:8333 failed after select(): Connection refused (111)
2020-01-20 10:07:01 [bitcoin-msghand] New outbound peer connected: version: 70015, blocks=618428, peer=21
2020-01-20 10:07:01 [bitcoin-msghand] ERROR: AcceptBlockHeader: block 0000000000000000004626ff6e3b936941d341c5932ece4357eeccac44e6d56c is marked invalid
2020-01-20 10:07:01 [bitcoin-msghand] ERROR: invalid header received
2020-01-20 10:07:10 [bitcoin-opencon] connect() to [2600:1f16:625:e00:a951:e663:4046:8c3a]:8333 failed: Network is unreachable (101)

**Comment by coolbobo** [comment]
bitcoin.conf 
server=1
rpcuser=rpcuser
rpcpassword=3xOfMoHmE8VtzStvRuLijS6c
rpcallowip=10.2.46.180
rpcport=8334
excessiveblocksize=2000000000
maxstackmemoryusageconsensus=200000000

**Comment by RayOshow** [comment]
> > I have had same problem although I had cleaned all data for Genesis bitcoin daemon in advance.
> > I'm now reindexing all blocks data.
> > After that I will write down the result.
> 
> any update ?

I have failed to fix it.
I tried docker instead of using built source but it has showed same problem.
If any changes, I will inform it.

**Comment by coolbobo** [comment]
> > > I have had same problem although I had cleaned all data for Genesis bitcoin daemon in advance.
> > > I'm now reindexing all blocks data.
> > > After that I will write down the result.
> > 
> > 
> > any update ?
> 
> I have failed to fix it.
> I tried docker instead of using built source but it has showed same problem.
> If any changes, I will inform it.

so sad information.

**Comment by jingniao** [comment]
i also have one of two has warn:
`Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade."`
it may becase error connection to bch node
```shell
bitcoin-cli getchaintips
[
  {
    "height": 618812,
    "hash": "00000000000000000029e2008149788ef5ee9085ed91adb7e0b9a03d44b19afa",
    "branchlen": 62046,
    "status": "invalid"
  },
  {
    "height": 618705,
    "hash": "000000000000000000a1c8783cba1280bf5a7c38aa18612b3a4b39cb47e7db5b",
    "branchlen": 0,
    "status": "active"
  },
  .......
]
```
00000000000000000029e2008149788ef5ee9085ed91adb7e0b9a03d44b19afa is  a bch block
how to handle with this?

**Comment by RayOshow** [comment]
I have solved this problem.
It seemed that the test chain for Beta2 is longer than main chain so bitcoind make itselt into safe mode. 
so I downloaded new src (1.0.0) and remove related source like below.
------------------------------------------------------------------------
src/validation.cpp
From
if (pindexBestForkTip || (pindexBestInvalid && pindexBestInvalid->nChainWork > chainActive.Tip()->nChainWork + (GetBlockProof(*chainActive.Tip()) * 6))) {

To
if (pindexBestForkTip)
-------------------------------------------------------------------------
And then built it and run it.

There is any problems without some error logs in bitcoind.

**Comment by coolbobo** [comment]
> ## I have solved this problem.
> It seemed that the test chain for Beta2 is longer than main chain so bitcoind make itselt into safe mode.
> so I downloaded new src (1.0.0) and remove related source like below.
> src/validation.cpp
> From
> if (pindexBestForkTip || (pindexBestInvalid && pindexBestInvalid->nChainWork > chainActive.Tip()->nChainWork + (GetBlockProof(*chainActive.Tip()) * 6))) {
> 
> ## To
> if (pindexBestForkTip)
> And then built it and run it.
> 
> There is any problems without some error logs in bitcoind.

Bitcoin SV v1.0.0 's bug?

**Comment by coolbobo** [comment]
what is any update news?

**Comment by Danconnolly** [comment]
We are looking at this and hope to have some information soon.

**Comment by coolbobo** [comment]
> We are looking at this and hope to have some information soon.

maybe an new version?

**Comment by RayOshow** [comment]
> > ## I have solved this problem.
> > It seemed that the test chain for Beta2 is longer than main chain so bitcoind make itselt into safe mode.
> > so I downloaded new src (1.0.0) and remove related source like below.
> > src/validation.cpp
> > From
> > if (pindexBestForkTip || (pindexBestInvalid && pindexBestInvalid->nChainWork > chainActive.Tip()->nChainWork + (GetBlockProof(*chainActive.Tip()) * 6))) {
> > ## To
> > if (pindexBestForkTip)
> > And then built it and run it.
> > There is any problems without some error logs in bitcoind.
> 
> Bitcoin SV v1.0.0 's bug?

Not bug.
As I know, all bitcoind has same code for checking invalid chain.
So there is a possibility that same problem happens where reboot running old version's bitcoind.

If you run 'bitcoin-cli getchaintips' , you could check 2 chain including invalid thing.
I guess invalid blockchain was originated from previous genesis beta version.
 
And it made the error when starting up and then you bitcoind is enforced to enter safe mode.

I just put away related condition, and my bitcoind has run well so far.
I think it's not recommended way.
However , if you are hurry, you could try it.

**Comment by melvjoshua** [comment]
I have some problem. Are there any updates with this issue?

**Comment by melvjoshua** [comment]
I have the same problem. Are there any update for this issue? (I tried using BSV v1.0.1 still cannot getbalance)

`bitcoin-cli getnetworkinfo`

`{
  "version": 101000100,
  "subversion": "/Bitcoin SV:1.0.1/",
  "protocolversion": 70015,
  "localservices": "0000000000000025",
  "localrelay": true,
  "timeoffset": 0,
  "txnpropagationfreq": 250,
  "txnpropagationqlen": 0,
  "networkactive": true,
  "connections": 8,
  "addresscount": 34059,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000250,
  "excessutxocharge": 0.00000000,
  "localaddresses": [
  ],
  "warnings": "Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade."
}`

`bitcoin-cli getblockchaininfo`

`{
  "chain": "main",
  "blocks": 619834,
  "headers": 619969,
  "bestblockhash": "000000000000000001d6e7a51f6b3651a4a25b33d2ead2604fd2e27914cde6cc",
  "difficulty": 459851906737.9314,
  "mediantime": 1580348410,
  "verificationprogress": 0.9999993436607054,
  "chainwork": "000000000000000000000000000000000000000000f6d1faea75abebefe58bbe",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    },
    {
      "id": "csv",
      "version": 5,
      "reject": {
        "status": true
      }
    }
  ]
}`

`bitcoin.conf`
excessiveblocksize=2000000000
maxstackmemoryusageconsensus=2000000000
server=1
daemon=1
maxconnections=30
spendzeroconfchange=0
keypool=500

Are there anything wrong with my node or config?

**Comment by coolbobo** [comment]
It's getting closer to February 4， how to solve this issue?

**Comment by Danconnolly** [comment]
Can you please execute the following commands:
```
bitcoin-cli addnode 95.217.38.93 add
bitcoin-cli addnode 68.183.42.63 add
bitcoin-cli addnode 174.138.5.253 add
```

The problem could be that your nodes are only connected to BCH nodes. The commands above add some known Bitcoin SV nodes.

**Comment by coolbobo** [comment]
> Can you please execute the following commands:
> 
> ```
> bitcoin-cli addnode 95.217.38.93 add
> bitcoin-cli addnode 68.183.42.63 add
> bitcoin-cli addnode 174.138.5.253 add
> ```
> 
> The problem could be that your nodes are only connected to BCH nodes. The commands above add some known Bitcoin SV nodes.

i have add 95.217.38.93/68.183.42.63/174.138.5.253 to bitcoin.conf， Resynchronization blockchain data
addnode=174.138.5.253
addnode=68.183.42.63
addnode=95.217.38.93

getbalance is not work fine.

**Comment by Danconnolly** [comment]
@coolbobo can you either post here or email to me (d.connolly@nchain.com) the output of `getpeerinfo` and `getblockchaininfo`?

**Comment by Danconnolly** [comment]
Note that running a Bitcoin Cash node from the same system, or with the same internet IP, or having run one within the last 24 hours, will cause issues. The Bitcoin Cash node may cause other nodes to ban the IP, the default time for a ban is 24 hours.

**Comment by justlovediaodiao** [comment]
I found the reason is that the bsv node connects to some bch nodes. bch chain is longer, so bsv node enters safe mode when it found a longer but invalid chain. 
I have got a temporary solution. Add  `disablesafemode=1` to `bitcoin.conf` and restart bsv node. It will disable safe mode.

**Comment by coolbobo** [comment]
> I found the reason is that the bsv node connects to some bch nodes. bch chain is longer, so bsv node enters safe mode when it found a longer but invalid chain.
> I have got a temporary solution. Add `disablesafemode=1` to `bitcoin.conf` and restart bsv node. It will disable safe mode.

@Danconnolly ，
Can we use this slove method？

**Comment by coolbobo** [comment]
what 's update news

**Comment by Danconnolly** [comment]
I don't recommend using the "disablesafemode" switch. The safe mode is there to protect you.

If your node is still not syncing, you can try adding the following lines in your bitcoin.conf:

```
connect=206.189.81.233
connect=159.65.152.200
connect=157.230.41.128
```

*But you must remove these lines after your node has synced*

**Comment by Pheromon** [comment]
What is this safe mode and why it must be enabled?

Shouldn't follow the chain with most PoW be enough to solve all the problems, like Satoshi wrote?

There are still at least two chains actively mined in BSV, it's a total mess.

**Comment by melvjoshua** [comment]
Try to delete all blocks data and peers.dat, it will take times to sync from 0 block. 
But it works on me.

**Comment by coolbobo** [comment]
> Try to delete all blocks data and peers.dat, and start with `connect` config.
> It will take times to sync from 0 block and solve the problem.

let me try it. thanks.

**Comment by Pheromon** [comment]
> It will take times to sync from 0 block and solve the problem.

I tried and the number of blocks I get (620840 in this moment) is less than number of headers (620935).

Also, my balance is still zero: how can I solve the problem?

**Comment by coolbobo** [comment]
> Try to delete all blocks data and peers.dat, and start with `connect` config.
> It will take times to sync from 0 block and solve the problem.
i have slove this problem, thanks.

**Comment by coolbobo** [comment]
> > I don't recommend using the "disablesafemode" switch. The safe mode is there to protect you.
> > If your node is still not syncing, you can try adding the following lines in your bitcoin.conf:
> > ```
> > connect=206.189.81.233
> > connect=159.65.152.200
> > connect=157.230.41.128
> > ```
> > 
> > 
> > _But you must remove these lines after your node has synced_
> 
> i have synced the blockchain, but the node enter "safe mode".

i have slove this problem, thanks.

**Comment by Pheromon** [comment]
@coolbobo how could you solve the problem?

My node is still stuck in safe mode and hence unusable.

**Comment by Danconnolly** [comment]
@coolbobo I'm glad you have solved the problem.

**Comment by Danconnolly** [comment]
@Pheromon can you please post the output of `bitcoin-cli getblockchaininfo`.

**Comment by Pheromon** [comment]
`
{
  "chain": "main",
  "blocks": 621184,
  "headers": 621183,
  "bestblockhash": "00000000000000000037d733736f192ec7eb4ac77df944d92792d66a80bfe78d",
  "difficulty": 516341539542.9672,
  "mediantime": 1581162205,
  "verificationprogress": 0.9999971566352598,
  "chainwork": "000000000000000000000000000000000000000000f8ef9a2b0b1dd2ba2631b5",
  "pruned": true,
  "pruneheight": 612274
}
`

There is also some info about soft forks that I did not paste here because I suppose it's useless.

**Comment by zndtoshi** [comment]
So what does "safemode" do?

**Comment by bantalon** [comment]
@coolbobo - Did you remove the lines from `bitcoin.conf` after the sync? Is this still working for you? 

Are these the steps you used to fix your broken node?

1. Add the following lines to `bitcoin.conf`:
   ```
   connect=206.189.81.233
   connect=159.65.152.200
   connect=157.230.41.128
   ```
1. Delete all blocks data and `peers.dat`.
1. Start the node and wait for the sync to complete.
1. Remove the `connect` lines added to `bitcoin.conf` and start the node.

**Comment by Danconnolly** [comment]
At the moment we are recommending the use of the 'disablesafemode` switch. This issue will be fixed in the next release which we expect early next week.

If anyone is still having issues, please comment in this thread.

**Comment by jchavannes** [comment]
@Danconnolly I am still having this issue

**Comment by daviunx** [comment]
Hi guys, if anybody still has this isse, I've got it working doing this: 

Add nodes ip in bitcoin.conf:
addnode=104.248.249.51
addnode=142.93.181.7
addnode=206.189.81.233
addnode=206.189.104.98
addnode=142.93.133.106
addnode=178.128.232.188

And after I did what i've found in https://www.reddit.com/r/Ravencoin/comments/akbqmg/how_do_i_resolve_this_stuck_at_syncing_headers/ 

> if your wallet is stuck on a block you can get past this by simply running these few commands in help>debug>console (do not use the carat "<>" symbols like in the example below)
> 
> getblockhash <stuck-block-number#> - returns stuck block hash for step 2 & 3
> stuck-block-number: You can get it from getinfo blocks field.
> 
> invalidateblock <stuck-block-hash> - marks the block as invalid and adds to set!
> 
> reconsiderblock <stuck-block-hash> - remove block from invalid block set.

Chain is loading again!

**Comment by matra774** [comment]
@coolbobo Sorry for late replay but this was fixed a while ago. Recent version included additional enhancements for header synchronizations. Feel free to open a new issue if you run into problems again.
