### ISSUE TITLE
How do I start version 1.0.0

### ISSUE THREAD

**Issue by JiangFangLing** [bitcoin-sv/bitcoin-sv#130]
First contact with BSV coin.
May I ask how to start and how to configure the document for reference?
Excessiveblocksize 1.0.0 release new add startup parameters and maxstackmemoryusageconsensus configuration in which the configuration file

**Comment by Danconnolly** [comment]
You can start bitcoind with the command-line: `bitcoind -maxstackmemoryusageconsensus=200000000 -excessiveblocksize=2000000000`

**Comment by JiangFangLing** [comment]
Thanks. Can these two configurations be configured in bitcoin.conf?

**Comment by Danconnolly** [comment]
Yes, like this:
```
maxstackmemoryusageconsensus=200000000
excessiveblocksize=2000000000
```

**Comment by JiangFangLing** [comment]
I tried.
My configuration looks like this
######
Server = 1
Rpcbind = 0.0.0.0:18335
Rpcuser = bsvcoinrpc
Rpcpassword = bsvcoinrpc
Rpcallowip = 0.0.0.0/0
Rpcport = 18335
Keypool = 100
Port = 8335
Excessiveblocksize = 200000000
Maxscriptmemoryusageconsensus = 2000000000
#######

But when it started, it still said
Mandatory consensus parameter is not set. In order to start bitcoind you must set the following consensus parameters: "Excessiveblocksize" and "maxstackmemoryusageconsensus". In order to start bitcoind with no limits you can set both of these parameters to 0 or it is strongly it to ensure you understand Implications of this setting.

For more information of how to choose these Settings safely For use case refer to: https://bitcoinsv.io/choosing-consensus-settings/

Here's how I get started
/ home/test/apps/BSV/bitecoin-sv/bin/bitcoind   -conf = / home/test/apps/bsvcoin.conf  -datadir = / home/test/bsvDatabase -daemon

Is it the wrong way to start? Is there anything missing?
