### ISSUE TITLE
Compiler error => big_int.cpp:469:43: error: static assertion failed

### ISSUE THREAD

**Issue by LoBlanc** [bitcoin-sv/bitcoin-sv#132]
### Describe the issue
I'm quite new to Linux and Bitcoin-SV, and I can't compile sources on a Raspberry Pi 4

#### If so, please list the steps to reproduce below:
1.run ./autogen.sh
2. run ./configure (I had to manually install some libboost libraries)
3.run ./make

### Expected behaviour
Should compile
### Actual behaviour
Ends with error:
`big_int.cpp:469:43: error: static assertion failed
     static_assert(sizeof(unique_asn1_ptr) == 8);
`

### What version of bitcoin-sv are you using?
Latest commit 7fd177c

### Machine specs:
Raspberry Pi 4

**Comment by Danconnolly** [comment]
I'm sorry but we dont support this platform.

See also #126 and note that a PR has been submitted to fix this issue: #131

**Comment by Danconnolly** [comment]
I'm sorry but we've completely withdrawn support for 32-bit platforms. A 32-bit system will be unable to validate the current Genesis Test network and we expect that it will be unable to validate the main network soon.
