### ISSUE TITLE
 `GLIBC_2.18'  and  `GLIBC_2.25'  not found

### ISSUE THREAD

**Issue by youngqqcn** [bitcoin-sv/bitcoin-sv#134]
error message:

```
bitcoind: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by bitcoind)
bitcoind: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by bitcoind)
```

system:  CentOS 7

**HOW CAN I  SOLVE THIS  PROBLEM ?**

**Comment by Danconnolly** [comment]
Our recommendation in this case is to use docker. Official docker images are available from https://hub.docker.com/r/bitcoinsv/bitcoin-sv.

**Comment by youngqqcn** [comment]
I compiled bitcoind from source on CentOS 7 .

**Comment by JEEEZY** [comment]
> I compiled bitcoind from source on CentOS 7 .

Did you end up resolving this? I am also having this problem but haven't used docker before.

**Comment by youngqqcn** [comment]
> > I compiled bitcoind from source on CentOS 7 .
> 
> Did you end up resolving this? I am also having this problem but haven't used docker before.

Yes.  

 I compile the source code on my machine  instead of using pre-compiled binaries which download from bitcoin-sv website.  

[The steps to  compile bitcoin-sv source on CentOS 7.](https://github.com/youngqqcn/QBlockChainNotes/blob/master/BTC%E7%B3%BB%E5%B1%B1%E5%AF%A8%E5%B8%81/7.%E7%BC%96%E8%AF%91BSV%E6%BA%90%E7%A0%81(v1.0.1).md)

**Comment by KrzysztofHajdamowicz** [comment]
#142 can help You :smile:

**Comment by JavierGonzalez** [comment]
> I compiled bitcoind from source on CentOS 7 .

This didn't work on my CentOS 7.

But with docker it is problem fixed. 
After 40 minutes (plus several hours fighting/learning with the docker network configuration).

**Comment by JEEEZY** [comment]
> > > I compiled bitcoind from source on CentOS 7 .
> > 
> > 
> > Did you end up resolving this? I am also having this problem but haven't used docker before.
> 
> Yes.
> 
> I compile the source code on my machine instead of using pre-compiled binaries which download from bitcoin-sv website.
> 
> [The steps to compile bitcoin-sv source on CentOS 7.](https://github.com/youngqqcn/QBlockChainNotes/blob/master/BTC%E7%B3%BB%E5%B1%B1%E5%AF%A8%E5%B8%81/7.%E7%BC%96%E8%AF%91BSV%E6%BA%90%E7%A0%81(v1.0.1).md)



> > > I compiled bitcoind from source on CentOS 7 .
> > 
> > 
> > Did you end up resolving this? I am also having this problem but haven't used docker before.
> 
> Yes.
> 
> I compile the source code on my machine instead of using pre-compiled binaries which download from bitcoin-sv website.
> 
> [The steps to compile bitcoin-sv source on CentOS 7.](https://github.com/youngqqcn/QBlockChainNotes/blob/master/BTC%E7%B3%BB%E5%B1%B1%E5%AF%A8%E5%B8%81/7.%E7%BC%96%E8%AF%91BSV%E6%BA%90%E7%A0%81(v1.0.1).md)

Thank you, this worked for me on CentOS 7.

**Comment by Danconnolly** [comment]
Closing. Problem with running on Centos 7 still exists.
