### ISSUE TITLE
package signing

### ISSUE THREAD

**Issue by cypherdoc** [bitcoin-sv/bitcoin-sv#135]
are you gpg signing these packages or only providing hashes?  where can i find the pgp keys for signers if it's being done?

**Comment by Danconnolly** [comment]
We are signing the hashes, you can find them in the file SHA256SUMS.asc.

The public key for the signature used for the 1.0.0 release has fingerprint `7500 0FF3 A8FF B0A1 0627  C859 E2D3 79E0 5075 7AA0`. This public key can be found on public keyservers. This public key will be included in the file doc/keys.md in the next release.

**Comment by cypherdoc** [comment]
excellent!  that'll do it.
