### ISSUE TITLE
Documentation of RPC API changes is not user-friendly

### ISSUE THREAD

**Issue by phil-dolgolev** [bitcoin-sv/bitcoin-sv#136]
In release notes don't indicated changes in RPC API while changes are present. (for example: https://github.com/bitcoin-sv/bitcoin-sv/commit/ebe93cf41e48bd1ca42e986b2bd68dca26002ec2)
Moreover, as I understand from https://github.com/bitcoin-sv/bitcoin-sv/issues/103 current way for users is personal checking changes through bitcoin-cli/codebase.

It's correct? If yes, this looks like bad practice.

**Comment by Danconnolly** [comment]
Thank you for pointing this out.
