### ISSUE TITLE
How can I get coins on GT?

### ISSUE THREAD

**Issue by SeongKuk** [bitcoin-sv/bitcoin-sv#137]
Hello bsv team.

I've finished syncing the GT (https://gt.whatsonchain.com/).

But I can not find faucet.

Could anyone send me some testnet coin or let me know faucet? ( 2N2gFytG6zqY9jUdShLj3ghh9e9BTuNaJDR ) Thanks!

**Comment by Danconnolly** [comment]
The GT faucet is at http://gt-faucet.bitcoinscaling.io.

**Comment by SeongKuk** [comment]
> The GT faucet is at http://gt-faucet.bitcoinscaling.io.

Thanks a lot!
