### ISSUE TITLE
My Bitcoin-sv full node stop at height 556776, how to fix it ?

### ISSUE THREAD

**Issue by kakelyo** [bitcoin-sv/bitcoin-sv#14]
My Bitcoin-sv full node version is 0.1.0，install on ubuntu 16.04， here is the getinfo result：
![image](https://user-images.githubusercontent.com/8394948/48631982-bacea200-e9fa-11e8-9cf2-0850be520f27.png)
![image](https://user-images.githubusercontent.com/8394948/48632324-958e6380-e9fb-11e8-9f59-18ff810b15d5.png)

**Comment by shsmith** [comment]
Most likely you are connected to only ABC peers, which are no longer compatible with SV. I see a similar issue with my SV node. I wish someone would post a list of known SV nodes so I can manually 'bitcoin-cli addnode' add them.

**Comment by scottjbarr** [comment]
Hi @kakelyo and @shsmith 

You can get a  list of Bitcoin SV peers from your node, assuming that you have a few in your list of peers to begin with. Filtering nodes like this isn't perfect, but we are currently in an imperfect situation.

I found a few, take a look at this Gist https://gist.github.com/scottjbarr/ccc81499e7f0d0de0d59c83d9359a4e0

Cheers
Scott

**Comment by kakelyo** [comment]
I see，it's work. Thanks ！

**Comment by Danconnolly** [comment]
Thank you everyone for providing assistance. If this is still an issue for people, please comment below.

**Comment by mosh5382** [comment]
Using @scottjbarr script and putting some of the nodes in my bitcoin.conf file and restarting my node got me back on track.  I'm currently getting synced back up.  Thanks for everyone's assistance!

**Comment by phpergithub** [comment]
@kakelyo Have you solved it? The same goes for mine
![image](https://user-images.githubusercontent.com/20673511/48997000-44b00500-f189-11e8-90f5-4b35aade1ccd.png)

**Comment by Danconnolly** [comment]
Add the lines below to your bitcoin.conf file and restart bitcoind.

```
addnode=104.248.249.51
addnode=142.93.181.7
addnode=206.189.81.233
addnode=206.189.104.98
addnode=142.93.133.106
addnode=178.128.232.188
```

**Comment by phpergithub** [comment]
@Danconnolly thanks

**Comment by Danconnolly** [comment]
Glad to hear it worked. Closing.
