### ISSUE TITLE
Add block explorer to the bitcoinsv.io website https://bsvexplorer.info/

### ISSUE THREAD

**Issue by HODLERTECH** [bitcoin-sv/bitcoin-sv#15]
Welcome. We have prepared a block explorer for Bitcoin SV. This is something that every project should have on the website, we hope it will be published there so that it can be found more easily.

The address: https://bsvexplorer.info/

**Comment by mrbianchi** [comment]
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by HODLERTECH** [comment]
Ttoday a certificate was added and we changed DNS, it is possible that the service was unavailable for a moment. Explorer is visited by thousands of people, we moved it to a server dedicated Intel (R) Xeon (R) CPU E3-1240 v6 @ 3.70GHz, 8 cores, 18GB RAM

**Comment by Danconnolly** [comment]
This block explorer is not supported by nChain or Bitcoin SV.

**Comment by HODLERTECH** [comment]
Ok, we just thought that you are encouraging the community to support the project. Thank you for your response.

**Comment by Danconnolly** [comment]
Sorry, I must have been in a bad mood and only saw the request for help with the site. We'll get this added.

**Comment by Fl4reTobiasH** [comment]
Thank you!
