### ISSUE TITLE
Issue with sendrawtransaction

### ISSUE THREAD

**Issue by afrederick814** [bitcoin-sv/bitcoin-sv#150]
### Describe the issue

When calling sendrawtransaction, I get the following error:

16: bad-txns-vout-p2sh

Does anyone know what this means? 

Here is the raw tx (sorry I couldn't find a decoder anywhere online):

0100000001b7e0933661396928b36f731e79e06faacc4927fc54fc5c16476971b67a85e20c00000000fdfd000047304402201f7575ecf964c1f0f702c8066df7baa964a744564847047e016e98b1cde0d931022068da7694aa264084c585c758eca9e76578ea47bdefe44c7a487bc7a4b16dcbb741483045022100eec0a76ffb0809058a28b815eecb2640c758c50d688d6677fceff011b5f9bbbb02200a51f8bb121b8a93a0f3b0a20267e56cd8a89e768a503f45880935614d81cc68414c695221036a72109f87a8f68e44af0791c63295319c7ff3745f856de462ddfb2f04ed473621035ba490208b6ad818c8b68b271969aff6e741fda3031543603493c28a0fb5c9fd2102d03902dc0844caf87880a244964b3dfa8e7bd743cbefffdc82991c82caff231553aeffffffff02db2d04000000000017a9145bcd6286470efa28f8d3b9c0ead3dabfb341346687727a15000000000017a9140da7c55ad5cde72b4ae475779ca7b3449b899a878700000000

### What version of bitcoin-sv are you using?
Running bsv version 1.0.0

**Comment by afrederick814** [comment]
Let me know if I can provide any other information

**Comment by bitcartel** [comment]
After the Genesis upgrade, you can no longer send to P2SH outputs, which are identified by the P2SH script pattern of: OP_HASH160 <hash> OP_EQUAL.

  "vout": [
    {
      "value": 0.00273883,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 5bcd6286470efa28f8d3b9c0ead3dabfb3413466 OP_EQUAL",
        "hex": "a9145bcd6286470efa28f8d3b9c0ead3dabfb341346687",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.01407602,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 0da7c55ad5cde72b4ae475779ca7b3449b899a87 OP_EQUAL",
        "hex": "a9140da7c55ad5cde72b4ae475779ca7b3449b899a8787",
        "type": "nonstandard"
      }
    }

You can replace the script with a functional equivalent: OP_SHA256 OP_RIPEMD160 <hash> OP_EQUAL

More info here:
https://github.com/bitcoin-sv-specs/protocol/blob/master/updates/genesis-spec.md#sunset-p2sh

**Comment by Danconnolly** [comment]
What bitcartel wrote is correct, but I do not recommend adjusting the script unless you are sure you know what you are doing.

Bitcoin addresses that start with a "3" are no longer valid in Bitcoin SV. If you have received this address from someone, you will need to contact them to obtain a different address.

**Comment by Wookie50** [comment]
Are you saying that if we have BSV funds in an address that starts with a "3", they are lost forever?  That would be crazy.

**Comment by Danconnolly** [comment]
No. Funds that are in a "3" address can be sent to a "1" address.

A "1" address is a standard wallet address. A "3" address is a P2SH address, commonly used for multi-sig wallets or Segwit. The P2SH address is no longer valid for receiving funds on Bitcoin SV.

**Comment by doido-shape** [comment]
I have the same problem: BSV network rejects my transaction due to P2SH.
 In reference to this comment above: _"You can replace the output scripts in your transaction with a functional equivalent: OP_SHA256 OP_RIPEMD160 <hash> OP_EQUAL"._
What is the best way to replace the output scripts mentioned above using ElectrumSV?
Appreciate the help!

**Comment by Danconnolly** [comment]
For assistance with ElectrumSV please use https://github.com/electrumsv/electrumsv/issues.
