### ISSUE TITLE
Fail to parse Tx from my server in 1.0.1

### ISSUE THREAD

**Issue by kyleO-O** [bitcoin-sv/bitcoin-sv#152]
Running in my 1.0.1：
`./bitcoin-cli getrawtransaction 26cf45cf415ad5072257713b9834b2c11ca675fc431e7ee6103fc5a783a6de26 true`
or 
`./bitcoin-cli decoderawtransaction 0100000007c0a596173fe56551d2d7e5a56fbce9c6bac4b5ad3237f229aee4a67db5e74f40020000006a47304402205314c9dcba8faa6e02d6ce4b47171e9aee3688e10aa289534f30df595965ab2a02207c320d5c8fa6c9cd68caaf0e136c00e082726f0ca885b97a271f155a9e82e7f54121029b5b4ea23d27281cd14b2720bbc3f1000b90a8ddaa6b7720043b8bdb6481048fffffffffc0a596173fe56551d2d7e5a56fbce9c6bac4b5ad3237f229aee4a67db5e74f40030000006b483045022100bffa7768a22c76558b61d6f3a5c3c46d20440ae66c61fa5eafdad878a001c6ec022023c2daa85849af7354a1145fc0fa08c6596ddf04a14b89f95e994fd160580fc941210332b730ee239db24930772dfc54d18075d2d89f29151508c7aa26c8717c79528bffffffff9c974d0b3772df490eb1ba35d29a40dbdf8642b650bfa8f4b80c1525763bd07d010000006b483045022100d30a0e27547839c7bfb021f9e097bc56e62751771c0361e2b4001b5d516d7d1402200a818fda787f08ce2f53c932edbf901cbd7858f6a1b2a5e966b632ce12b1ea58412103431042fe37540a0875bc21079c609ef9a98b096d442ba53522fb1d9484f63eacffffffff9c974d0b3772df490eb1ba35d29a40dbdf8642b650bfa8f4b80c1525763bd07d020000006a473044022037a9bead1ec9be90d2e75130095410ec7ef1a96d0009859e2fc0384f502f3aca02200f3dccac6f1060dab989c6d5b3250df3f29390d303a0e1a3f7c7efe8c2ec77d8412103431042fe37540a0875bc21079c609ef9a98b096d442ba53522fb1d9484f63eacffffffff9988bb8e91d08108000e929e2e211f520ff86d50c04080d60b82f49e28631adf010000006b48304502210094fef3b96bc48613942965bde271866f96ab3368b15037a3a7b4e6656436d42e02204ad083f3849e1a7c61ecedb629857af197d15faf1991a7224376fe0b29f2e1424121028569353bddd68498e87b6a64dfc2fd6da178c71780fb9b15140b7349601d4423ffffffff9988bb8e91d08108000e929e2e211f520ff86d50c04080d60b82f49e28631adf020000006b483045022100cf2e984d907701af9c9c89ecc57d4c9943152dedb95de9f1561b19dea07c052302206c31927cddd41eab9f871ee98beaeb3b48e08e464ef777a5632d10ac17389f894121028569353bddd68498e87b6a64dfc2fd6da178c71780fb9b15140b7349601d4423ffffffff9988bb8e91d08108000e929e2e211f520ff86d50c04080d60b82f49e28631adf040000006a473044022017d1ab5cf9a4e203cceaca17a4750e31f006b27e54c97c15239fbab6ea6d30c1022028d5441e6364ddc23006ca49fe9b948a1f0539f66b35b3b56148d3efcfc322b8412102e6abb9a0507216cf7320aa8ecfed15929ac42e5ae63749fab297e519b373f2b8ffffffff05f30d0000000000001976a91405186ff0710ed004229e644c0653b2985c648a2388acf30d0000000000001976a914088f6c98cf561d3909468634bfd9469dd44b33c888acf30d0000000000001976a91488558bbd30afe1e9f44474768f673bafb1a2f00a88acf30d0000000000001976a91488558bbd30afe1e9f44474768f673bafb1a2f00a88acf30d0000000000001976a91488558bbd30afe1e9f44474768f673bafb1a2f00a88ac00000000`

Error reported:
`error: couldn't parse reply from server`

But I can parse this TX in other block browsers.
How to fix it?
Is there a problem in my bitcoin.conf ？

Thank!

**Comment by JokerCatz** [comment]
Hi , I know how to fix it ...... it funny bug ...

you can just call `bitcoin-tx` without server and cli like this

    ./bitcoin-tx --json HEX_HERE

and the json is format break like

    }
    {

it missing `,` at JSON obj array ... so you need fix the source json by yourself ... like regex or string gsub ...

this bug same happen at `bitcoin-cli getblock HEX_HERE 2` & rest api & ......

**Comment by Danconnolly** [comment]
This is a bug that is fixed in the next version.

In the meantime, either use the trick you have mentioned, or roll back to version 1.0.0.

**Comment by kyleO-O** [comment]
Thank @Danconnolly .And when will the next version be released?

Thank @JokerCatz .This is a solution, but it is difficult for me to apply.
