### ISSUE TITLE
what happen of transaction : 736dd20c902aaa60ee73d2cabbee0e190326f1921a173e660d6461b281f99d18

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin-sv/bitcoin-sv#153]
txid : `736dd20c902aaa60ee73d2cabbee0e190326f1921a173e660d6461b281f99d18`

this tx vout has 3 same address , and many explorer mark this transaction target address as unknow ...

    "vout": [
      {
        "value": 0.0003,
        "n": 0,
        "scriptPubKey": {
          "asm": "2 049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed0 049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed0 049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed0 3 OP_CHECKMULTISIG",
          "hex": "5241049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed041049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed041049ab377dac431e7a8ea2b9afa8bca930139eea1e1bade2ed7f0fbdd08f69669b1eb137e8d02faacf4793d5e949d0af4212105f5aa13aaae482c4b99752db8eed053ae",
          "reqSigs": 2,
          "type": "multisig",
          "addresses": [
            "1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU",
            "1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU",
            "1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU"
          ]
        }
      }
    ],

**Comment by verretor** [comment]
This address exists. [https://live.blockcypher.com/btc/address/1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU/](https://live.blockcypher.com/btc/address/1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU/)

**Comment by Danconnolly** [comment]
This is a strange bare multisig tx. It requires two out of three signatures and the signatures can all be from the same address.

**Comment by ATMackay** [comment]
Multisig transactions do not have a single target address, that might be the issue. In this particular case the transaction paying to a script that requires duplicate signatures from the same public key.  It's probably someone just experimenting with custom scripts.

**Comment by JokerCatz** [comment]
sorry my pool english ...

I mean ... many BCHSV explorer are not allow this UTXO be balance of the target wallet
`1deoskXRMbzNuafp5UbfB9P5T3hcGnMMU` , and explorer is parse the target wallet fail
so .. is the miner trust the UTXO can be balance of future ? or just lock it ?

**Comment by Danconnolly** [comment]
This is not a standard transaction. Most wallets will not understand this transaction or display the transaction. Many explorer's may also not add this to the balance of the address.

There are many, many, possible transaction types in Bitcoin SV. Wallets generally use the standard transaction type called P2PKH. All wallets will understand the P2PKH type of transaction.

**Comment by ATMackay** [comment]
The transaction output for 736dd20c902aaa60ee73d2cabbee0e190326f1921a173e660d6461b281f99d18 is spendable (currently unspent). 

Note, some wallets have not (yet) added support for custom scripts and may not recognize nonstandard transactions. That doesn't mean that the coins are lost, but that they may be temporarily inaccessible from those wallets.

**Comment by Danconnolly** [comment]
No comments for over a week, closing.
