### ISSUE TITLE
1.0.1 getrawtransaction returns invalid JSON value, comma missing

### ISSUE THREAD

**Issue by kgcorps** [bitcoin-sv/bitcoin-sv#154]
#### If so, please list the steps to reproduce below:
1. use rpc to retrieve raw transaction (formatted as json), transaction hash: 618e3f0ad014e9713983a3c23a0318f2b32bfa4f20581b598de015791f098126

### Expected behaviour
Valid JSON returned with the pre-defined values.

### Actual behaviour
`"vout": [
      {
        "value": 0.00003576,
        "n": 0,
        "scriptPubKey": {
          "asm": "OP_DUP OP_HASH160 05186ff0710ed004229e644c0653b2985c648a23 OP_EQUALVERIFY OP_CHECKSIG",
          "hex": "76a91405186ff0710ed004229e644c0653b2985c648a2388ac",
          "reqSigs": 1,
          "type": "pubkeyhash",
          "addresses": [
            "1Twetcht1cTUxpdDoX5HQRpoXeuupAdyf"
          ]
        }
      },
      {
        "value": 0.00006464,
        "n": 1,
        "scriptPubKey": {
          "asm": "OP_DUP OP_HASH160 34c98416a3f41b2a229a287813c16228f619479a OP_EQUALVERIFY OP_CHECKSIG",
          "hex": "76a91434c98416a3f41b2a229a287813c16228f619479a88ac",
          "reqSigs": 1,
          "type": "pubkeyhash",
          "addresses": [
            "15p7YYv83BTgdTsgPud1hJ5ucjVK7aDHyM"
          ]
        }
      },
      {
        "value": 0.00007152,
        "n": 2,
        "scriptPubKey": {
          "asm": "OP_DUP OP_HASH160 a3cd3df64a1fb3cf803d0eb6d6fe63f2b7f85c02 OP_EQUALVERIFY OP_CHECKSIG",
          "hex": "76a914a3cd3df64a1fb3cf803d0eb6d6fe63f2b7f85c0288ac",
          "reqSigs": 1,
          "type": "pubkeyhash",
          "addresses": [
            "1Fw71jePrBU24KpxF2KfbRcvZytwGdZn5Z"
          ]
        }
      }
      {
        "value": 0.00007152,
        "n": 3,
        "scriptPubKey": {
          "asm": "OP_DUP OP_HASH160 a3cd3df64a1fb3cf803d0eb6d6fe63f2b7f85c02 OP_EQUALVERIFY OP_CHECKSIG",
          "hex": "76a914a3cd3df64a1fb3cf803d0eb6d6fe63f2b7f85c0288ac",
          "reqSigs": 1,
          "type": "pubkeyhash",
          "addresses": [
            "1Fw71jePrBU24KpxF2KfbRcvZytwGdZn5Z"
          ]
        }
      }
    ]`

There is a missing object seperator between output 2 and 3. Can't parse response using JSON parser libraries.

### What version of bitcoin-sv are you using?
1.0.1
Downloaded from https://download.bitcoinsv.io/bitcoinsv/1.0.1/

**Comment by JokerCatz** [comment]
save your time : `"}{" => "},{"` & `"\n"` => `","`

`"}{" => "},{"` as you say and
`"\n"` => `","` at block `0000000000000000018215cb0a652c9f05bbef546937790389b460fe75e5bbdc` (txid : `736dd20c902aaa60ee73d2cabbee0e190326f1921a173e660d6461b281f99d18` )

**Comment by Danconnolly** [comment]
Thank you, this is fixed in the next release, 1.0.2.

If this issue is affecting you, we suggest rolling back to version 1.0.0.

**Comment by abrkn** [comment]
Is there a date set for 1.0.2, @Danconnolly?

**Comment by Danconnolly** [comment]
Monday.

**Comment by bogerv** [comment]
Is there any updates?

**Comment by bogerv** [comment]
Is there any updates?

**Comment by abrkn** [comment]
Any news?

**Comment by nur-azhar** [comment]
Dan is presenting in few minutes
https://youtu.be/mW-a9hM3eeE

**Comment by Danconnolly** [comment]
This was fixed in version 1.0.2 which was released last week.

https://bitcoinsv.io/2020/02/17/optional-software-upgrade-to-v1-0-2/.
