### ISSUE TITLE
bsv coinbase bug .  

### ISSUE THREAD

**Issue by huhaichao** [bitcoin-sv/bitcoin-sv#168]
bsv coinbase income   to p2sh address.

txid  is 449c0e91665fe07490a4f194009cda394c768dc7bcc8d8fee27cb40372666c3f

[https://explorer.viawallet.com/bsv/tx/449c0e91665fe07490a4f194009cda394c768dc7bcc8d8fee27cb40372666c3f](url)

**Comment by Ljzn** [comment]
It is a normal hash puzzle.

**Comment by huhaichao** [comment]
how can i spent the coin

**Comment by Danconnolly** [comment]
We were contacted by email about this. Closing this issue.
