### ISSUE TITLE
How to used insight api on bitcoin SV ?

### ISSUE THREAD

**Issue by nakinthorn** [bitcoin-sv/bitcoin-sv#17]
Can bitcoin SV used an existing insight api and block explorer (now I'm using bitpay insight)
and how ?

**Comment by Danconnolly** [comment]
In our tests on the Gigablock Test Network, some explorers had issues with large blocks. We are working on this issue.

**Comment by msaikat** [comment]
Anybody has an update on the usage of insight-api with BSV testnet/livenet? Any help would be highly appreciated.

**Comment by Danconnolly** [comment]
If you need assistance with the insight api on Bitcoin SV, please raise that with the insight API team.

Closing.
