### ISSUE TITLE
can bsv build on macos?

### ISSUE THREAD

**Issue by zl03jsj** [bitcoin-sv/bitcoin-sv#18]
can  BSV build on mac os now?

**Comment by spaniakos** [comment]
> **(I am not a contributor, this is not an official answer)**

I am trying to find a why but for now there is a problem with berkeley-db4 not recognized and as a result to ./configure halts with libdb_cxx headers missing.
and even with --disable-wallet still there are missing headers that needs to be configured. 
I think that this will take a while.

**Comment by spaniakos** [comment]
Compiled using the following commands
(most of them are from bitcoin core library)

cd <directory of your choice>

Download source
https://github.com/bitcoin-sv/bitcoin-sv/releases/download/v0.1.0/bitcoin-sv-0.1.0.tar.gz

xcode-select --install

brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/berkeley-db.rb --without-java

brew install automake libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode

If you want to build the disk image with make deploy (.dmg / optional), you need RSVG:
brew install librsvg


Build core
./autogen.sh
./configure
make

It is recommended to build and run the unit tests:
make check

(not tested)
You can also create a .dmg that contains the .app bundle (optional):
make deploy 

Core is now available at ./src/bitcoind

Tested on macOS Mojave 10.14
8GB RAM
2.5 GHZ intel i5 x64

**Comment by zl03jsj** [comment]
@spaniakos i meet the same problem:   ....libdb_cxx headers missing...

i have tried above method, but it dosen't work..
i look into configure.log,  seems like bitcoin-sv needs berkeley 5 and up version..

i'm not sure...

**Comment by spaniakos** [comment]
try 
```
brew link --force berkeley-db4
echo 'export PATH="/usr/local/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile
export LDFLAGS="-L/usr/local/opt/berkeley-db@4/lib"
export CPPFLAGS="-I/usr/local/opt/berkeley-db@4/include"
```

after 
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/berkeley-db.rb --without-java`

not if you had installed berkeley with brew install, do brew uninstall and then proceed

**Comment by zl03jsj** [comment]
@spaniakos  i have tried the above 2 method, you mentioned.  this daytime..
it does't work for me.
does this solved your problem, or are you already successfully build BSV on mac?
if you succeed, i will  try again, tomorrow..

anyhow,  thank you for answering..

**Comment by spaniakos** [comment]
yes, have build on OSX
my time line is as following:\
installed with 
`brew install berkeley-db4`
made 
`brew link berkeley-db4 --force`
```
echo 'export PATH="/usr/local/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile
export LDFLAGS="-L/usr/local/opt/berkeley-db@4/lib"
export CPPFLAGS="-I/usr/local/opt/berkeley-db@4/include"
```
yesterday.
today i made
`brew uninstall berkeley-db4`
and then i followed my new guide. It compiled correctly.
currently i am trying to build again with qt support using 
./configure --with-gui=qt5

**Comment by Danconnolly** [comment]
Thank you everyone for providing assistance. 

In light of recent events, we are re-considering support for Windows and MacOS.

**Comment by zl03jsj** [comment]
@spaniakos  
i reset my bash environment, and followed your step, it works...
for the previous failures,  the command line i use was zsh..
thank you again..

**Comment by spaniakos** [comment]
i dont know why you needed to switch bash enviroment, maybe needed a "restart" to get the global paths and environment variables , but glad this helped

**Comment by sabela** [comment]
I followed instructions provided above by @spaniakos and had similar errors to @zl03jsj what I learnt was:

**make sure** you don't skip this line in the instructions (I ignored it initially as I thought it was to install homebrew which I already had)

brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/berkeley-db.rb --without-java

**Comment by zl03jsj** [comment]
> yes, have build on OSX
> my time line is as following:
> **yesterday:**
> installed with
> `brew install berkeley-db@4`
> made
> `brew link berkeley-db@4 --force`
> 
> ```
> echo 'export PATH="/usr/local/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile
> export LDFLAGS="-L/usr/local/opt/berkeley-db@4/lib"
> export CPPFLAGS="-I/usr/local/opt/berkeley-db@4/include"
> ```
> 
> **today i made**
> `brew uninstall berkeley-db4`
> and then i followed my new guide. It compiled correctly.
> currently i am trying to build again with qt support using
> `./configure --with-gui=qt5`
> 
> ![screenshot 2018-11-20 at 18 24 20](https://user-images.githubusercontent.com/1690858/48787474-85270300-ecf1-11e8-8d27-65c18f6a7a7d.png)

hi, man, have you build with gui(--with-gui=qt5) success on macos?

**Comment by jolonf** [comment]
I just went through the process of building for macOS Mojave 10.14.6:

1. Install macOS dependencies:

```
install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config python qt libevent qrencode
```

https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md

2. Need to `#include <inttypes.h>` in init.cpp: 

https://www.gitmemory.com/issue/bitcoin-sv/bitcoin-sv/83/512809352

3. If compiling with wallet disabled move "vmtouch.h" include: 

https://github.com/bitcoin-sv/bitcoin-sv/issues/84

4. `constexpr` generates a compiler error. 

Replaced the constant with the raw value (2048), not the best solution, but the raw value appears everywhere else in the file instead of the constant:

https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/univalue/include/univalue.h#L20

**Comment by Danconnolly** [comment]
New versions should compile on MacOS. If there are any issues, please collect them in #104.

Closing this one.
