### ISSUE TITLE
Getting error during docker run bitcoinsv/bitcoin-sv -  In order to start bitcoind you must set the following consensus parameters: "excessiveblocksize" and "maxstackmemoryusageconsensus"

### ISSUE THREAD

**Issue by pinaki29uk** [bitcoin-sv/bitcoin-sv#188]
This issue tracker is only for technical issues related to bitcoin-sv.

I download bitcoin-sv image from docker hub     ( docker pull bitcoinsv/bitcoin-sv)

However, I am getting following error while running :-    docker run bitcoinsv/bitcoin-sv   

Mandatory consensus parameter is not set. In order to start bitcoind you must set the following consensus parameters: "excessiveblocksize" and "maxstackmemoryusageconsensus". In order to start bitcoind with no limits you can set both of these parameters to 0 however it is strongly recommended to ensure you understand the implications of this setting.

How do I set the above two parameters while running docker i.e. docker run bitcoinsv/bitcoin-sv  ?

I have tried using -e with docker command but none seems to work. Also created a bitcoin.conf file in the linux current directory. no luck.

would greatly appreciate if anyone can help on this.

Thanks Pinaki

**Comment by zigako** [comment]
Hi,
you can set parameters when running docker. 
Example: `docker run bitcoinsv/bitcoin-sv bitcoind -maxstackmemoryusageconsensus=1000000000 -excessiveblocksize=100000000`

Choosing values for mandatory settings is described [here](https://bitcoinsv.io/documentation/miners/settings/).
Note that the example above does not create persistent data volume. To add a data volume please follow this [instructions](https://github.com/bitcoin-sv/docker-sv#data-volumes).

**Comment by Danconnolly** [comment]
Old, closing.
