### ISSUE TITLE
Wallet release...

### ISSUE THREAD

**Issue by screeni** [bitcoin-sv/bitcoin-sv#19]
For a mass adoption maybe you should release a Wallet Windows - Mac - Linux it is the minimum when a new crypto coin is launched....

**Comment by Danconnolly** [comment]
There are several excellent wallets which support Bitcoin SV. These include

- Handcash - https://handcash.io/
- Centbee - https://www.centbee.com/
- CashPay Wallet - https://www.cashpay.solutions/wallet/

**Comment by Danconnolly** [comment]
Thank you for your comment, given the changes recently, we will reconsider supporting the Qt Wallet.
