### ISSUE TITLE
No answer from the bug bounty program.

### ISSUE THREAD

**Issue by seceine** [bitcoin-sv/bitcoin-sv#192]
For 20+ months I've repeatedly written to security@bitcoinsv.io and to @Danconnolly with barely no answer. I'm waiting for updates on BSVRD-713 and BSVD-593. Both were reported March last year and have been fixed for months, but it seems bitcoin-sv is failing to follow up with security researchers responsibly participating in the bug bounty program.

I'm aware this might not be the right place for this kind of message, but you haven't been answering e-mails for almost a year. I would like to continue working on bitcoin-sv, but I first need some sort of conclusion on both open reports.

**Comment by Danconnolly** [comment]
I thought this was all finished off. I'll look into it.

**Comment by seceine** [comment]
I'm closing this issue as it was quickly resolved by nChain and the Bitcoin Association. I'm really satisfied with the outcome. I'll encourage other researchers to work with the bitcoinsv team in helping keeping their software secure. Thank you, @Danconnolly.
