### ISSUE TITLE
Disable some rpc methods in config 

### ISSUE THREAD

**Issue by Ljzn** [bitcoin-sv/bitcoin-sv#193]
### Describe the issue

The rpc methods like `setban` and `addnode` could be used to attack the public node which provides block sync service.  

#### If so, please list the steps to reproduce below:
1. ban the valid nodes.
2. add attacker's nodes
3. publish fake blocks and transactions from attacker's nodes

### Expected behaviour

ban a list of rpc methods in `bitcoind.conf`

### Actual behaviour

no such config

**Comment by matra774** [comment]
Hi @Ljzn !  The RPC interface is not intended to be exposed on public network or to anonymous, untrusted  users.

For example it contains wallet functionality and exposing this would definitely cause a loss of funds.

The P2P interface is the public interface that is used for exchanging information about blocks,  transactions and other nodes.

**Comment by Ljzn** [comment]
Thanks, @matra774 . I understand the RPC interface should be used in a trusted environment. In our use case, we have disabled the wallet (there is an option to disable it) and just provide the block syncing functionality for several internal services. The P2P interface is hard to use because consumers need to deserialize the data.

I think it's a common use case among crypto exchanges. An rpc method blocklist would be helpful. Currently, we need wrap another layer to filter the rpc methods to prevent consumers change the peer connections.

**Comment by rt121212121** [comment]
There are ZMQ and HTTP interfaces that can be used to provide deserialised block and transaction data. Have you looked at these?

**Comment by Ljzn** [comment]
Thanks, @rt121212121 . I will check the HTTP interface.
