### ISSUE TITLE
Balance the interests of miners and users.

### ISSUE THREAD

**Issue by chinaBLK** [bitcoin-sv/bitcoin-sv#197]
Sorry, I don't know how to contact BSV developer.
So I put forward my suggestions here.
--------

I really like the low handling charge.

But I think, a higher handling charge should be charged for large amount transfer.

For example, transfer 0.00001 -- 1bsv, Charge a handling fee of $0.001（Convert to BSV）
Transfer 1-100bsv, Each BSV is charged 0.01--1$ worth of BSV
If it is a large amount transfer，Transfer 100 -- 10000 BSV+  , Charge a handling fee of US 1-5$ worth of BSV.  BSV of $5 value is the upper limit of transfer handling charge.

Transfer less than 1bsv, we can think that is daily consumption. Therefore, only the minimum handling charge is charged.
Large transfer users don't care about 0.01 - $5 (upper limit) handling charge

Using such charging rules can balance the interests of users and miners.

**Comment by shadders** [comment]
Hi,

Transaction fee pricing policies are not chosen by BSV developers but by miners. It is miners who bear the cost of maintaining the network and confirming transactions so it's up to them how much they wish to charge for it., We have provided various tools (including MAPI) to allow miners to set pricing in more flexible ways.

I would recommend you take this suggestion to miners directly.
