### ISSUE TITLE
Fail to compile an exe in Windows subsystem of Linux. 

### ISSUE THREAD

**Issue by wer5lcy** [bitcoin-sv/bitcoin-sv#2]
I'm building an x64 exe for windows, according to [build-windows.md](https://github.com/bitcoin-sv/bitcoin-sv/blob/beta/doc/build-windows.md).
In the last step, using command "make", an error occurs with the following output.

```
CXX      leveldb/util/leveldb_libleveldb_a-env_win.o                                         
CXX      leveldb/port/leveldb_libleveldb_a-port_win.o                                        
AR       leveldb/libleveldb.a                                                              
/usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')        
CXX      leveldb/port/leveldb_libleveldb_sse42_a-port_posix_sse.o                            
AR       leveldb/libleveldb_sse42.a                                                        
/usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')        
CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o                                 
AR       leveldb/libmemenv.a                                                              
 /usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')        
CXXLD    bitcoind.exe                                                                       
CXX      seeder/bitcoin_seeder-main.o                                                      
seeder/main.cpp: In function ‘int main(int, char**)’:                                        
seeder/main.cpp:471:12: error: ‘SIGPIPE’ was not declared in this scope                           
signal(SIGPIPE, SIG_IGN);                                                                           
^~~~~~~                                                                          
seeder/main.cpp:471:12: note: suggested alternative: ‘SIGFPE’                                     
signal(SIGPIPE, SIG_IGN);                                                                           
^~~~~~~                                                                                      
SIGFPE                                                                           
Makefile:8283: recipe for target 'seeder/bitcoin_seeder-main.o' failed                       
make[2]: *** [seeder/bitcoin_seeder-main.o] Error 1                                          
make[2]: Leaving directory '/home/wer5lcy/bitcoin-sv/src'                                    
Makefile:9807: recipe for target 'all-recursive' failed                                      
make[1]: *** [all-recursive] Error 1                                                         
make[1]: Leaving directory '/home/wer5lcy/bitcoin-sv/src'                                    
Makefile:690: recipe for target 'all-recursive' failed                                       
make: *** [all-recursive] Error 1        
```

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
An executable file.  

### Actual behaviour
Error in "make" command, leading to abnormal exit.

### Screenshots.
Screenshot of the error.
![image](https://user-images.githubusercontent.com/33412324/46545658-7f1fc300-c8f9-11e8-8147-030cb73b8953.png)

### What version of bitcoin-sv are you using?
Latest open beta. using git clone to the WSL 

### Machine specs:
- OS: Windows 10 1809, pro edition, with Ubuntu 18.04 LTS. (the error also occurs with 16.04 with Mingw-w64 packages from the Ubuntu 17.10)
- CPU: Intel i5-6300HQ
- RAM: 20G
- Disk size: 256G
- Disk Type (HD/SDD): SSD

**Comment by Danconnolly** [comment]
I'm sorry, but we don't support the Windows platform at this time. The inclusion of the "build-windows.md" file in the beta version was an omission which is being corrected for the release version.

**Comment by wer5lcy** [comment]
> I'm sorry, but we don't support the Windows platform at this time. The inclusion of the "build-windows.md" file in the beta version was an omission which is being corrected for the release version.

I am running the 0.1.0 release x86-64 under Windows Subsystem for Linux, with Win 10 1809 and Ubuntu 18.04 LTS.
It seems the client is working normally, with the param "datadir=/mnt/d/BitcoinSV" for both bitcoind and bitcoin-cli. I moved the datadir to the local partition D of windows. I cannot mine on the main net, but getblocktemplate works.
