### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [bitcoin-sv/bitcoin-sv#20]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We have supported Bitcoin-sv and for several days we have been exchanging bitcoin-sv for more than 170 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by Danconnolly** [comment]
Thank you for trying to contact us. I have sent an e-mail to the address listed on your site.
I will also check this repository to ensure that our contact information is easily accessible.
