### ISSUE TITLE
request to change the default script size limit from 10KB to 500KB

### ISSUE THREAD

**Issue by mc-gulu** [bitcoin-sv/bitcoin-sv#201]
Currently, we are working on multiple projects that would require a much higher default script size limit, so that the corresponding contracts can be deployed on the mainnet, without communicating with miners and have each of them set the parameter on their own.

Here is a sample tx:

[https://whatsonchain.com/tx/703d52f432cb2d2447dac2affb4d81a367763a718a3c3d4201808cd20c1e4486](https://whatsonchain.com/tx/703d52f432cb2d2447dac2affb4d81a367763a718a3c3d4201808cd20c1e4486) 

we're paying 22000 satoshis for the 44KB tx.

The detailed size chart is shown below (for your information):

![image002](https://user-images.githubusercontent.com/1855937/117753050-6bbffb80-b24a-11eb-89be-64feb439afc3.png)

We believe this could help applications (with relatively large script size) greatly. 

Thanks.

**Comment by OnchainTrade** [comment]
This is an issue that urgently needs to be addressed, without removing script size limit, it's impossible to run big smart contract on BSV, it only serves as another limit to Bitcoin scaling

**Comment by TokenSwapProtocol** [comment]
All limits should be removed, or Bitcoin is not actually scaling. Just removing block size limit doesn't mean Bitcoin scales, scaling means removing all limits that stops application/utility on Bitcoin

**Comment by quzhenok** [comment]
Urgent problems

**Comment by TokenSwapProtocol** [comment]
We sincerely request the team to realize how urgent this is and remove or at least increase the script size limit. Miners are not incentivized to do so, it is very similar to block size limit debate, it needs to be addressed from the root.

**Comment by longzhi** [comment]
If the default script size were changed to 500KB, I believe the Sensible Contract Protocol would work better and Bitcoin SV would show more power on smart contract.

**Comment by zxsz666** [comment]
The request is very important for BSV's future development,please nchain implement it as soon as possible.

**Comment by zxsz666** [comment]
> Urgent problems

Yes,the problem is very important, it is urgent to solve.

**Comment by ichengkr** [comment]
Support this request

**Comment by imcoddy** [comment]
Hope all the miners & developers in BitCoin ecosystem could consider this as we are still too small and time waits for no one.

**Comment by zhangguoqing0906** [comment]
need to remove this limit asap

**Comment by Pheromon** [comment]
Please remove all limits!

**Comment by jichuan2018** [comment]
Hope all the miners & developers in BitCoin ecosystem could consider this as we are still too small and time waits for no one

**Comment by ContradictoryCapitalism** [comment]
Support this request. Please remove all limits!

**Comment by dogesv** [comment]
Support this request. Please remove all limits!

**Comment by Shawnkiwi** [comment]
All limits should be removed, or Bitcoin is not actually scaling. Just removing block size limit doesn't mean Bitcoin scales, scaling means removing all limits that stops application/utility on Bitcoin

**Comment by BSVER10** [comment]
Support, limit must be removed, Time is running out for BSV

**Comment by soar4ever** [comment]
Support.

**Comment by ion-storm** [comment]
This increase will result in increased development on bsv, I support this.

**Comment by mathiasrw** [comment]
This is a good idea, but it is the miner that sets the actual value. Changing defaults will only bring us a bit more convenience but no guarantees (and that is a problem)

What we really need is transparency. It is not directly related to this issue but it would make sense to expand the mAPI to provide information about limitations like just like [this feature request](https://github.com/bitcoin-sv-specs/brfc-merchantapi/issues/8) is asking for more transparency regarding ancestor limits.

**Comment by kyuupichan** [comment]
Amazing how many with empty github histories care about this!

**Comment by rt121212121** [comment]
I am curious if you force a much higher default on a miner like Hather, what stops them from keeping the lower setting just to limit their costs? Besides, I am pretty sure Jerry Chan tweeted that Taal support this setting, and it should be possible to just submit the tx through their MAPI right and the problem is solved?

**Comment by kurtwuckertjr** [comment]
I support this change, but I would like to express how important it is for commercial developers to solicit such changes from their mining partners, and then for miners to have such changes made by developers. Steve Shadders is not, nor should he be the man who decides policy or consensus changes in Bitcoin SV. He's a hell of a dev and quite a nice guy, but only miners truly act. If the community puts Steve in a position of de facto protocol Czar, then we are in real trouble (again.) 

Please establish relationships with TAAL, MatterPool and Mempool, and work with them on such changes.

**Comment by mc-gulu** [comment]
> aand so it begins --- the blockstream takeover of the Bitcoin git repo v2.0 😅

As we all know, Blockstream is the one who keeps telling people "The limit is there so that no one could change, ever. Now come to use our hyper technology" As a gesture of goodwill, I think I didn't get the point you are talking about.

**Comment by kurtwuckertjr** [comment]
> > I support this change, but I would like to express how important it is for commercial developers to solicit such changes from their mining partners, and then for miners to have such changes made by developers. Steve Shadders is not, nor should he be the man who decides policy or consensus changes in Bitcoin SV. He's a hell of a dev and quite a nice guy, but only miners truly act. If the community puts Steve in a position of de facto protocol Czar, then we are in real trouble (again.)
> > Please establish relationships with TAAL, MatterPool and Mempool, and work with them on such changes.
> 
> About the communication with miners, please check out my reply above to @rt121212121.
> 
> We do have healthy communications with miners for some time. But with all due respect, "establish relationships" is a bad smell that it's generally not an encouraging signal for newcomers especially indie developers. They generally have even less time and resources to contribute than us. Their concerns cannot be heard if "establish relationships" is a necessary step toward "being taken into account" by existing players.
> 
> Developers could be able to get a chance to raise issues here to be heard (like all other projects on GitHub) I think that's the initial purpose to have this project in a collaborative open-source repository, isn't it?

I don't mean you any disrespect, nor do I want any unnecessary development friction. Also, I think that the miners need to have much more accessible and available customer service departments that are easy to navigate and collaborate with. 

That being said, Bitcoin SV is not an open development software project. It is an economic system governed by mining nodes. I *agree* with the goals of your pull request, but the proposition you are making is a policy change that needs to be adopted by miners' policy rules. As such, you're asking someone else to change software that miners DO NOT HAVE TO RUN. 

With all do respect, and I do respect your work and your opinions, precedent about governance and ownership matter more than anything in Bitcoin SV, so it is important to respect the process, in my opinion.

**Comment by OnchainTrade** [comment]
> I support this change, but I would like to express how important it is for commercial developers to solicit such changes from their mining partners, and then for miners to have such changes made by developers. Steve Shadders is not, nor should he be the man who decides policy or consensus changes in Bitcoin SV. He's a hell of a dev and quite a nice guy, but only miners truly act. If the community puts Steve in a position of de facto protocol Czar, then we are in real trouble (again.)
> 
> Please establish relationships with TAAL, MatterPool and Mempool, and work with them on such changes.

This sounds very similar to what small blockers said during the scaling fight. Increasing the limit is not a change to the consensus, it is just removing the limit that serves only as an obstacle to application. Miners can filter transactions with larger script if they cannot handle. Just like they can filter big blocks if they can't process. The situation is very similar to the 1MB block size thing. Some think it is a drastic change to the protocol, some think it is an urgent change to pave the way for application and growth of Bitcoin.

**Comment by kurtwuckertjr** [comment]
> > I support this change, but I would like to express how important it is for commercial developers to solicit such changes from their mining partners, and then for miners to have such changes made by developers. Steve Shadders is not, nor should he be the man who decides policy or consensus changes in Bitcoin SV. He's a hell of a dev and quite a nice guy, but only miners truly act. If the community puts Steve in a position of de facto protocol Czar, then we are in real trouble (again.)
> > Please establish relationships with TAAL, MatterPool and Mempool, and work with them on such changes.
> 
> This sounds very similar to what small blockers said during the scaling fight. Increasing the limit is not a change to the consensus, it is just removing the limit that serves only as an obstacle to application. Miners can filter transactions with larger script if they cannot handle. Just like they can filter big blocks if they can't process. The situation is very similar to the 1MB block size thing. Some think it is a drastic change to the protocol, some think it is an urgent change to pave the way for application and growth of Bitcoin.

It’s the opposite of that, actually. Miners can change their policy settings right now, and I believe they should. Asking the lead node dev is a way to put the lead dev in a leadership position like the Core devs. I don’t want to argue, especially since I support this proposal.

**Comment by shadders** [comment]
Brigading the Bitcoin SV git repo isn't the right way to get this change to happen and it like won't achieve the effect you are looking for anyway.  I've written a detailed description of what would likely happen if we accepted this request and a better way to make to change happen here: 

https://bitcoinsv.io/2021/05/12/on-the-governance-of-bitcoin-limits/

**Comment by zihanoo** [comment]
biger limit good for compound contract
