### ISSUE TITLE
Unable to get big blocks via RPC

### ISSUE THREAD

**Issue by Polve** [bitcoin-sv/bitcoin-sv#203]
### Describe the issue
I get an error while trying to download raw blocks from the node, via network

### Can you reliably reproduce the issue?
Yes:

1.
from my machine, connected to the internet with a stable, fiber 100mbit link I issue a command like this:
bitcoin-cli -rpcuser=X -rpcpassword=Y -rpcconnect=mynode  getblock 0000000000000000046bb497bda05586305fee1e86fdde1bb2802821729ec16b 0 > out.hex

2.
A large part of the block gets downloaded but after a few seconds (around 30-40) it fails with this error:
error: Could not connect to the server mynode (error code 1 - "EOF reached")

### Expected behaviour
It should download the hex raw block like it happens with smaller blocks

**Comment by matra774** [comment]
Try increasing  `-rpcservertimeout` on server side (default is 30 seconds).

**Comment by Polve** [comment]
That was the problem, thanks very much for the hint
