### ISSUE TITLE
bitcoin-sv isn't compatible with CentOS 7 (docker-sv)

### ISSUE THREAD

**Issue by Brightside56** [bitcoin-sv/bitcoin-sv#204]
It's not working on CenOS 7 using docker-sv  1.0.8 image
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::status: Function not implemented: "/srv/bsv"       
bitcoin in AppInit() 
```
1.0.7 is working fine with exactly same configuration. There is no problem on Ubuntu 20 or latest Fedora. I suspect it's because of boost update and it's not compatible with CentOS 7 runtime on default kernel

**Comment by matra774** [comment]
@Brightside56 are you official official docker image (https://hub.docker.com/r/bitcoinsv/bitcoin-sv/) or a custom one?

**Comment by Brightside56** [comment]
@matra774 Official one

**Comment by apufvqsp** [comment]
ubuntu 20.04 has a similar problem

**Comment by rt121212121** [comment]
In theory ElectrumSV builds Linux node binaries using centos 7, we have a docker image with dependencies pre-installed.

https://github.com/electrumsv/electrumsv-node/blob/master/.azure-pipelines/main.yml#L21

Our only problem compiling the nodes has been cmake on Windows, and it was cmake bugs not the node source code.

**Comment by APshenkin** [comment]
I found that official docker image is working on MacOS but doesn't work on Unix systems. Same thing if we build our own image using binary file from releases. Seems there are some internal dependencies in boost library that after building doesn't work on Unix systems

**Comment by APshenkin** [comment]
We found that using docker on Ubuntu 20.04 system doesn't lead to this error

**Comment by liuzhiyangGDM** [comment]
I also have the same problem，


Is there a solution?

**Comment by randydu** [comment]
The same issue occurs to me, v1.0.8 cannot start in the docker image debian:sid-slim running on Ubuntu 16.04.
Downgrade to v1.0.5, it works out of the box without any change.

**Comment by lifengmds** [comment]
The same problem happened to me, switched to v1.0.7 which worked.

**Comment by Danconnolly** [comment]
I'm sorry but CentOS 7 is not supported, either directly or as a docker host. Please upgrade to CentOS 8.

https://github.com/bitcoin-sv/bitcoin-sv/wiki/CentOS-7-not-supported
