### ISSUE TITLE
[vulnerability] Possible privacy leakage due to ordered transaction inputs

### ISSUE THREAD

**Issue by yixiao5428** [bitcoin-sv/bitcoin-sv#205]
The wallet uses ordered inputs of transactions (`src/wallet/wallet.cpp`, [line 2917 - 2925](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/wallet/wallet.cpp#L2917-L2925)), which may incur privacy risks like fingerprinting the wallet to observers.

A possible solution is to clear the original order, shuffle it, and push back the new order before signing the transaction.

Similar fix from Bitcoin: https://github.com/bitcoin/bitcoin/commit/2fb9c1e6681370478e24a19172ed6d78d95d50d3.

Reported by `6004ed5feaa31ae9df36b5dbc60f0fa53255a5fb734334082c6d202405fc738c`.

**Comment by Danconnolly** [comment]
Thank you for this submission. 

However, due to the potentially sensitive nature of this bug report, we are removing this ticket and will handle it confidentially. We will keep the submitted informed and post a public report in due course.
