### ISSUE TITLE
Wrong bitcoin whitepaper in history

### ISSUE THREAD

**Issue by carnhofdaki** [bitcoin-sv/bitcoin-sv#210]
Honored Mr. Wright, dear fellow Bitcoin SV developers, dear guests,

what I find really intriguing is that on archive.org they keep the malicious copy of bitcoin.pdf file. Please have a look at https://web.archive.org/web/20100704213649/bitcoin.org/bitcoin.pdf and possibly make them delete it.

### Can you reliably reproduce the issue?

Yes, just open any of the archived bitcoin.pdf files.

#### If so, please list the steps to reproduce below:

1. Go to [archive.org](https://archive.org).
2. Enter `bitcoin.org/bitcoin.pdf` into the search box.
3. Press **Go** button.
4. See all the malicious copies.

### Expected behaviour
The malicious bitcoin.pdf files should not be there. They are misleading and point to some unknown email address we do not have access to. The only [bitcoin-white-paper.pdf](https://craigwright.net/bitcoin-white-paper.pdf) files on the world wide web should be those with following SHA256 checksum:

```
7a3aeccf8d75095c96c21e57352a49120e0dd70627f70e935c8bfe781ddac957
```

The `pdfinfo` of the correct bitcoin-white-paper.pdf written by our Mr. Wright, long life to him, says this:

```
Title:          Bitcoin: A Peer to Peer Electronic Cash System
Keywords:       
Author:         Craig Wright
Creator:        Writer
Producer:       OpenOffice.org 2.4
CreationDate:   Tue Mar 24 18:33:15 2009 CET
ModDate:        Mon Jan 25 13:11:37 2021 CET
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          9
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      222865 bytes
Optimized:      yes
PDF version:    1.6
```

### Actual behaviour
There are plenty of bitcoin.pdf files on archive.org with following SHA256 checksum:

```
b1674191a88ec5cdd733e4240a81803105dc412d6c6708d53ab94fc248f4f553
```

The `pdfinfo` of this malicious file contains following:

```
Creator:        Writer
Producer:       OpenOffice.org 2.4
CreationDate:   Tue Mar 24 18:33:15 2009 CET
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          9
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      184292 bytes
Optimized:      no
PDF version:    1.4
```

The diff between the two is following and it clearly shows which one is the original (the one with more lines and more recent PDF format version):

```diff
--- bitcoin-white-paper.pdfinfo	2021-06-29 12:34:56.974140701 +0000
+++ bitcoin.pdfinfo	2021-06-29 12:34:56.418531944 +0000
@@ -1,10 +1,6 @@
-Title:          Bitcoin: A Peer to Peer Electronic Cash System
-Keywords:       
-Author:         Craig Wright
 Creator:        Writer
 Producer:       OpenOffice.org 2.4
 CreationDate:   Tue Mar 24 18:33:15 2009 CET
-ModDate:        Mon Jan 25 13:11:37 2021 CET
 Tagged:         no
 UserProperties: no
 Suspects:       no
@@ -14,6 +10,6 @@
 Encrypted:      no
 Page size:      612 x 792 pts (letter)
 Page rot:       0
-File size:      222865 bytes
-Optimized:      yes
-PDF version:    1.6
+File size:      184292 bytes
+Optimized:      no
+PDF version:    1.4
```

### Any extra information that might be useful in the debugging process.

I just whole-heart wish everybody understands the truth and accept Bitcoin SV as the only real and original, and that people from all the nations around the world would accept Mr. Wright as our savior. We can make it so that only the righteous copies of the original whitepaper and nothing else is available. Or?

Also following commits should be rewritten in history of our precious bitcoin-sv/bitcoin-sv repository because they point to even further act-of-violence misleading copies of the spoofed whitepaper:

 1. bitcoin-sv/bitcoin-sv@b06a1bbd0
 2. bitcoin-sv/bitcoin-sv@67958519f

Oops, and also make sure Bitcoin ABC is not mentioned anywhere. That was clearly a fork of our precious original Bitcoin SV and it should not look like our code is based on a fork of a fork.

All the best to everyone! We are here on this Earth together. There will be less environmental impact of crypto-mining if we forgot all the copies and would focus just on the one and original Bitcoin SV, the Satoshi Vision.

**Comment by carsenk** [comment]
Fuck Craig Steven Wright and fuck you for trying to help him spread disinformation.

He is not Satoshi. This delusional pretentious lieing asshole has the worst karma on the planet coming his way, we are not scared of him, at all.

Do not download or believe a word these idiots say, that white paper is plagiarized copy that Craig Wright unlawfully broke the MIT license of.

**Comment by carnhofdaki** [comment]
Dear @carsenk, please limit yourself to words that build. I totally see your point of view. Let's try to bridge the gaps for everyone who sees it from the other side. Yes, it is like physics. And the apple will eventually bump anyone's head. But let them take their time and think. Be kind.

https://www.gnu.org/philosophy/kind-communication.html

**Comment by baryon** [comment]
Close the thread please. It's not about source code.

**Comment by carnhofdaki** [comment]
@baryon Yes, just a moment. I wrote it here because I did not find any other channels that would be better suited to report the issue I found on archive.org.

**Comment by baryon** [comment]
reddit or twitter or medium, no github

**Comment by carnhofdaki** [comment]
@baryon Thank you! Closing now. I kept the [messages from this issue](https://gist.github.com/carnhofdaki/28af01c52df57cb4672f74408616bd55).
