### ISSUE TITLE
Fix misleading references in the repository

### ISSUE THREAD

**Issue by carnhofdaki** [bitcoin-sv/bitcoin-sv#211]
My previous [issue #220][issue220] was deleted as it was not fully code-related. But there is one part of it, which is.

[issue220]: https://gist.github.com/carnhofdaki/28af01c52df57cb4672f74408616bd55

Please have a look at this code-related part of it:

-----

Following commits should be rewritten in history of bitcoin-sv repository in order to make all the claims look more trustworthy:

 1. [bitcoin-sv/bitcoin-sv@b06a1bbd0][code1]
 2. [bitcoin-sv/bitcoin-sv@67958519f][code2]

[code1]: https://github.com/bitcoin-sv/bitcoin-sv/commit/b06a1bbd0
[code2]: https://github.com/bitcoin-sv/bitcoin-sv/commit/67958519f

**Comment by shadders** [comment]
Please stop posting nonsense on this repo. History is not meant to be rewritten. It is what it is.
