### ISSUE TITLE
Please clarify apparently deceptive licensing

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-sv/bitcoin-sv#213]
Craig Wright, an executive at nChain and the creator of the BSV fork of the Bitcoin software (which I happen to be copyright holder of), made [the following public statement](https://pbs.twimg.com/media/E8CApEvVgA4hLGh?format=png&name=orig):

> There will not be any alternative forks of BSV. Such an action is a breach of copyright, and criminal cases will be taken against any exchanges, nodes, operators, and developers who choose to copy BSV and try to run it.

This is an unambiguous contradiction with the licensing document which you are distributing at: https://github.com/bitcoin-sv/bitcoin-sv/blob/master/LICENSE

Please explain and cure this contradiction.

**Comment by shadders** [comment]
low value trolling
