### ISSUE TITLE
Release 1.0.9 not signed with any known public keys

### ISSUE THREAD

**Issue by muratso** [bitcoin-sv/bitcoin-sv#226]
The release 1.0.9 was not signed with any of the pgp keys in https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/keys.md.

Could you please update this doc with the new keys that we should expect?
@richmills3 @chrisgibson01

**Comment by Danconnolly** [comment]
Thank you for submitting this issue, the team is investigating it.
