### ISSUE TITLE
Release 1.0.9 breaks consensus

### ISSUE THREAD

**Issue by brianorwhatever** [bitcoin-sv/bitcoin-sv#227]
Freezing UTXOs will be used in malicious ways by bad actors. This breaks the "set in stone" ethos and is an all around bad idea. This change makes it appear that the Bitcoin Association is the bad actor the public claims them to be.

The solution is more honest hash power, which will not be attracted with protocol changes like this.

**Comment by shadders** [comment]
It doesn't break consensus anymore than the configurable excessiveblocksize parameter does. We've had that for nearly 3 years and never seen any problem.
