### ISSUE TITLE
EXCEPTION: N5boost10filesystem16filesystem_errorE   

### ISSUE THREAD

**Issue by arayalways** [bitcoin-sv/bitcoin-sv#228]
### Describe the issue
Upgrade bitcoin-sv from v1.0.5 to v1.0.9;

Program just shut down with error:
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::status: Function not implemented: "/bitcoin"       
bitcoin in AppInit()       

```

### What version of bitcoin-sv are you using?
v1.0.9 Release

### Machine specs:
- OS: Ubuntu 18.04.3
- CPU:Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz *8
- RAM: 32G
- Disk size: 2T
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
No logs no  other info

**Comment by arayalways** [comment]
Thanks and I'm in desperate need of a solution that my wallet doesn't work for a while.

**Comment by CassClark** [comment]
@arayalways we've been looking into this for you, however was wondering if you could provide a bit more information please.

Can you confirm what version of boost you are using?

**Comment by arayalways** [comment]
It's `libboost1.58-dev:amd64: /usr/include/boost/version.hpp` on host VM(ubuntu 16). However I run BSV node in a docker image based on ubuntu 18 which I could not find the `libboost` library.

**Comment by CassClark** [comment]
@arayalways Can you try using v1.65 of boost or later please?

**Comment by CassClark** [comment]
closing this ticket as 14 days have past since our last comment in relation to how to resolve the issue.
