### ISSUE TITLE
Testnet availablity

### ISSUE THREAD

**Issue by rockandruby** [bitcoin-sv/bitcoin-sv#23]
I run bitcoin-sv core in testnet mode. Are there any bchsv faucets to credit my test wallet?
Some other questions:
1. The first time I credited my testnet bitcoin-sv address using bch faucet and transaction came to wallet in about one day. It was the first and last time, all other trials of crediting my bchsv with bch faucet failed(transaction didn't come to my wallet). As I understand bch faucet should not work with bchsv?
2. When I had a successful tx for bchsv I tried to credit regular bchabc wallet an it did. Maybe because I used old 0.17 abc core version but I guess that shouldn't be like that anyway?!
All actions were done in testnet mode. Pls clarify things above.

**Comment by tuandung291** [comment]
@rockandruby Did you find the way to faucet BSV testnet mode?

**Comment by tranchiendang** [comment]
Do you guys know how can we get free coins in testnet for testing purpose.
I try searching but dont find out.

**Comment by mboyd1** [comment]
I'm running a testnet faucet at https://bitcoincloud.net/faucet/ as well as a block explorer for testnet.

**Comment by AustEcon** [comment]
@mboyd1 ah so it's you behind https://testnet.bitcoincloud.net 

Does it have an api for testnet? If so how would I connect? 

People have been requesting testnet for bitsv but so far I've only found a halfway-built whatsonchain api (which will be awesome when they finish it).

**Comment by Danconnolly** [comment]
Thanks for running the faucet.

**Comment by codenlighten** [comment]
> I'm running a testnet faucet at https://bitcoincloud.net/faucet/ as well as a block explorer for testnet.

I would love if you could show me how to set up a testnet mining faucet. -Greg
