### ISSUE TITLE
Release 1.0.10 signed with a non-listed key

### ISSUE THREAD

**Issue by brunomq** [bitcoin-sv/bitcoin-sv#235]
The 1.0.10 is signed with a different key not listed on the https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/keys.md
when I try to verify I am receiving the following  message

```
#9 12.14 gpg:                using RSA key 75000FF3A8FFB0A10627C859E2D379E050757AA0
#9 12.14 gpg: Can't check signature: No public key ``` 
```
I believe this key should be included in documentation

**Comment by Danconnolly** [comment]
Thank you. The SHA256SUMS.asc file has been updated.
