### ISSUE TITLE
Cross-check of mempool file and transaction database failed: Failed to open mempool file from disk. Continuing with empty mempool and transaction database.

### ISSUE THREAD

**Issue by johnzhou123** [bitcoin-sv/bitcoin-sv#236]
Who knows how to solve this problem，its a testnet bsv node

**Comment by CassClark** [comment]
This is a warning message you've provided alludes to the fact that the db's are out of sync because of improper shutdown.  It is not an issue.

**Comment by johnzhou123** [comment]
> 这是您提供的警告消息，暗示数据库由于关闭不当而不同步。这不是问题。

ok,i see ,thanks
