### ISSUE TITLE
How do I reduce storage running nodes

### ISSUE THREAD

**Issue by COLUD4** [bitcoin-sv/bitcoin-sv#239]
![截屏2021-12-10 下午2 45 33](https://user-images.githubusercontent.com/21240219/145529688-15daaa54-2cab-4345-8aa4-13efa7055b00.png)
I set prune=1000, but couldn't start the node. If removed, the node can be started and run normally

**Comment by Ljzn** [comment]
The unit of prune is MB if I remember it correctly. So 1000MB just 1GB, maybe it's too small to download the block data. Try a larger number.

**Comment by CassClark** [comment]
@COLUD4 We suggest that if you are using the prune config option, that you set it to a level appropriate to the disk space available on the machine. However, be advised that the node keeps at least 288 blocks. If these blocks are 2GB each, that’s 288 x 2GB = 576 GB. In addition, we recommend 128GB swap space (see https://bitcoinsv.io/documentation/miners/system-requirements), so a prune setting below 1TB is probably unwise.
 
We will be updating the Knowledge Base (https://github.com/bitcoin-sv/bitcoin-sv/wiki/Support-and-Knowledge-Base) with further advice in the near future.
