### ISSUE TITLE
The future of BSV (roadmap candidate)

### ISSUE THREAD

**Issue by priestc** [bitcoin-sv/bitcoin-sv#24]
I was only a SV supporter because it was forking without replay protection. In my opinion, "airdrop forks" or "forks with replay protection" are the worst thing ever to be invented in the cryptocurrency world, and "no-replay protection forks" or "non-airdrop forks" I hope someday may become the norm. 

It's a shame that so many people are abusing SV's rules to make BSV into an airdrop. For this reason, I think it's best if everyone mining SV should do everything in their power to deny everyone their airdrop, which really means just turning off their miners and stop extending the chain. Instead redirect those resources into the next BCH fork 6 months from now. There has been a lot of things learned from this last fork, and the next attempt may actually succeed in making ABC powerless over the BCH network.

I think instead of SV being yet another airdrop currency, SV should rebrand itself as ABC opposition, or rather "power opposition" instead of just an airdrop that people dump.

Here is a better roadmap for BCH:

1. Oppose his new hard forking changes not by making a new code repository, but by advocating for the previous rules. Last fork, the overton window was not in the right position for miners to switch from the ABC client to the "Fake Satoshi" client. The Overton window **is** in the right position for miners to switch from new ABC version to old ABC version, or at least thats my opinion. Its also my opinion that the slow adoption of segwit ultimately decreased the Core developer's influence, and successful opposition of ABC's new rules may very well hurt his influence too, which should be the goal of the SV project. Last fork, too many people were simply opposed to BSV simple because Craig was involved.

2. Once Amary's influence has been diminished, the Overton window may become in a position that'll allow miners to use another client, even one associated with CSW.

3. Remove almost everything Core/ABC has added to the protocol and restore BCH to Satoshi's vision. Eventually BCH may actually get listed as just Bitcoin on exchanges, and that should also be an ultimate goal of the SV project, but that'll be easier to do if BCH uses all the same stuff as the original Bitcoin protocol (including the Base58 address format)

**Comment by daengx** [comment]
Send a pull request

**Comment by ravibhojwani** [comment]
Early days yet .. let’s see after October we in stealth at the mo
