### ISSUE TITLE
Getblocktemplate request parsing error for releases newer than 1.0.6.

### ISSUE THREAD

**Issue by kr1z1s** [bitcoin-sv/bitcoin-sv#241]
I'm use ckpool which use jasson C library - https://github.com/akheron/jansson

If use 1.0.6 and older than parsing gbt result is ok. But with 1.0.7 and newer i get an error

`JSON decode ( "getblock...) failed(1): control character 0xd near '"'`

This error appeared after you started using Simplify JSonWriter.

Other RPC requests are processed correctly. I checked "getnewaddress", "getmininginfo", "getnetworkinfo", "getblockchaininfo"
Parsing is correct.

**Comment by CassClark** [comment]
hi @kr1z1s 

Would you be able to share the JSON that does not parse correctly please? 

Can you also advise of the following as this will help us investigate the issue you are experiencing:

- What OS are you using (please also provide the version)
- Can you advise what version of bitcoind you are using?
- Would you be able to send me the log file please? (I can provide a secure upload account to do this if you wish).
 
Many thanks

**Comment by kr1z1s** [comment]
> hi @kr1z1s
> 
> Would you be able to share the JSON that does not parse correctly please?
Ok. I will try to save the response to the request.
> 
> Can you also advise of the following as this will help us investigate the issue you are experiencing:
> 
> * What OS are you using (please also provide the version)
Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)
> * Can you advise what version of bitcoind you are using?
I check 1.0.7.1, 1.0.8, 1.0.9, 1.0.10
> * Would you be able to send me the log file please? (I can provide a secure upload account to do this if you wish).
I have full log. Where to upload them?
> 
> Many thanks
With others coins (BTC,BCH,XEC,DGB) there are no such problems. And with BSV daemons version 1.0.6 and older.

**Comment by CassClark** [comment]
hi @kr1z1s 

Thanks for the information you've provided.  Would you be able to send me your email address please so that I can send you a secure link to upload your full log to?  If you don't want to put your email address here, feel free to email me via the bitcoinsv support mailbox; support@bitcoinsv.io 

thanks
Cass

**Comment by kr1z1s** [comment]
> hi @kr1z1s
> 
> Thanks for the information you've provided. Would you be able to send me your email address please so that I can send you a secure link to upload your full log to? If you don't want to put your email address here, feel free to email me via the bitcoinsv support mailbox; [support@bitcoinsv.io](mailto:support@bitcoinsv.io)
> 
> thanks Cass


Sent log to you email.

**Comment by CassClark** [comment]
@kr1z1s log file received & passed to the dev team.

**Comment by richmills3** [comment]
Hi @kr1z1s 

Could you please let us know what additional arguments you are providing to the getblock RPC call? Ideally could you give a complete example of a getblock call that demonstrates the faulty JSON.

Thanks.

**Comment by kr1z1s** [comment]
Below is the pool code and the queries I tried.
Other RPC requests are processed correctly.

Only GBT request returns an error message - JSON decode ( "getblock...)
failed(1): control character 0xd near '"'


> static const char *gbt_req = "{\"method\": \"getblocktemplate\",
> \"params\": [{\"capabilities\": [\"coinbasetxn\", \"workid\",
> \"coinbase/append\"], \"r>
>
This is the current


> //static const char *gbt_req = "{\"method\": \"getblocktemplate\",
> \"params\": [{\"capabilities\": [\"coinbasetxn\", \"workid\",
> \"coinbase/append\"]}]}\n";
> //static const char *gbt_req = "{\"method\": \"getblocktemplate\",
> \"params\": [{\"capabilities\": [\"coinbasetxn\", \"workid\"], \"rules\" :
> [\"segwit\"]}]}\n";

//static const char *gbt_req = "{\"method\": \"getblocktemplate\"}\n";
>
Have you tried it

/* Request getblocktemplate from bitcoind already connected with a
> connsock_t
>  * and then summarise the information to the most efficient set of data
>  * required to assemble a mining template, storing it in a gbtbase_t
> structure */
> bool gen_gbtbase(connsock_t *cs, gbtbase_t *gbt)
> {
>         json_t *rules_array, *coinbase_aux, *res_val, *val;
>         const char *previousblockhash;
>         char hash_swap[32], tmp[32];
>         uint64_t coinbasevalue;
>         const char *target;
>         const char *flags;
>         const char *bits;
>         const char *rule;
>         int version;
>         int curtime;
>         int height;
>         int i;
>         bool ret = false;
>
>         val = json_rpc_call(cs, gbt_req);
>

 The challenge here is the same as in other places with others RPC



ср, 12 янв. 2022 г. в 11:17, richmills3 ***@***.***>:

**Comment by richmills3** [comment]
Thank you for that.

I just tried a quick test using a node running on the `regtest` network (I am also running up a mainnet node and will try that as well later) of your basic `getblocktemplate` call. I got the following JSON output:

```
rich@amy:~/nchain/sv$ ./src/bitcoin-cli getblocktemplate > getblocktemplate.json
rich@amy:~/nchain/sv$ cat getblocktemplate.json
{
  "capabilities": [
    "proposal"
  ],
  "version": 536870912,
  "previousblockhash": "6564c8049bc16479e0414d144c1c82e69bee1195f24209e9966513db4a7ea444",
  "transactions": [
  ],
  "coinbaseaux": {
    "flags": ""
  },
  "coinbasevalue": 2500000000,
  "longpollid": "6564c8049bc16479e0414d144c1c82e69bee1195f24209e9966513db4a7ea4442",
  "target": "7fffff0000000000000000000000000000000000000000000000000000000000",
  "mintime": 1641894220,
  "mutable": [
    "time",
    "transactions",
    "prevblock"
  ],
  "noncerange": "00000000ffffffff",
  "sizelimit": 128000000,
  "curtime": 1641979672,
  "bits": "207fffff",
  "height": 202
}
```
I then tried parsing that JSON using `jansson` (version 2.13):

```
#include <iostream>
#include <jansson.h>

int main()
{
    json_t* json {nullptr};
    json_error_t error {};

    json = json_load_file("/home/rich/test/jansson/getblocktemplate.json", 0, &error);
    if(json)
    {
        std::cerr << "All parsed ok" << std::endl;
    }
    else
    {
        std::cerr << "json error on line " << error.line << " : " << error.text << std::endl;
    }
}
```
```
rich@amy:~/test/jansson$ g++ main.cc -ljansson
rich@amy:~/test/jansson$ ./a.out 
All parsed ok
```
So currently I can't see the same issue as you are encountering. As I say, I'll try again later when I have a full node available rather than just a regtest node.

Also I should just mention that the `getblocktemplate` RPC method is superseded by the newer `getminingcandidate` RPC call. I'd recommend you move to using that if possible.

**Comment by kr1z1s** [comment]
Hm...

I'm use jansson version 2.10

ср, 12 янв. 2022 г. в 13:23, richmills3 ***@***.***>:

**Comment by kr1z1s** [comment]
And more. Are you parsing only a text response? I have an error that occurs
even when parsing the stream.

Here - https://github.com/akheron/jansson/blob/master/src/load.c#L323

ср, 12 янв. 2022 г. в 13:36, A S ***@***.***>:

**Comment by richmills3** [comment]
> And more. Are you parsing only a text response?

As I showed in my reply above: I'm saving the text output of the `getblocktemplate` RPC call to a file and then parsing the contents of that file. That should be enough to test whether the returned JSON is correctly formed and whether jansson can read it.

I just tried building and linking against jansson 2.10 and that also parsed without error, so it's not that.

**Comment by kr1z1s** [comment]
I understand that's not the point.
 Because before version 1.0.7 I had no problems. And it works fine on
version 1.0.6.
It is the text response that you are analyzing. Control characters are
not visible in the text!
And the answer shows that the parser stumbles on the control symbol.

ср, 12 янв. 2022 г. в 14:15, richmills3 ***@***.***>:

**Comment by richmills3** [comment]
> I understand that's not the point. Because before version 1.0.7 I had no problems. And it works fine on version 1.0.6.

There are 3 possibilities:
1. 1.0.7 introduced a bug in bitcoind JSON generation.
2. 1.0.7 changed JSON generation and triggered a bug on your side.
3. 1.0.7 changed JSON generation and is triggering a bug in jansson.

I'm concentrating on testing cases 1 and 3, I can't obviously investigate case 2. 

>It is the text response that you are analyzing. Control characters are not visible in the text!

That's not entirely true; control characters wouldn't be visible when I `cat` the file, but they would be present in the file if they were returned in the output to `bitcoin-cli`. I agree it is possible however that something might be stripping them out of the data returned from bitcoind before they are displayed and written to the file, so to eliminate that possibility I have attached a patch I would like you to try applying to the file `src/rpc/client.cpp`. The diff is taken from version 1.0.7 of the source but will probably apply cleanly to later versions as well.

[client.cpp.diff.txt](https://github.com/bitcoin-sv/bitcoin-sv/files/7854538/client.cpp.diff.txt)

After rebuilding if you could please run `bitcoin-cli getblocktemplate`. That should also dump the binary contents of the HTTP response from bitcoind to bitcoin-cli to a temporary file `/tmp/rpc.json`. Please attach that file to a response here and I can take a look at it (you'll probably have to gzip it for github to allow it to be attached).

For what it's worth, I've already tried that here and again jansson happily parses it, but it'll be interesting to see if you produce something different.

**Comment by kr1z1s** [comment]
rpc.json in attach

[rpc.tar.gz](https://github.com/bitcoin-sv/bitcoin-sv/files/7854776/rpc.tar.gz)

**Comment by richmills3** [comment]
Thanks. Ok, so that also parses fine using jansson in that test program I posted above.

To summarise; we've used bitcoin-cli to issue a `getblocktemplate` call to the node and applied a patch that intercepts the read response from the node and writes it out to a file before anything else can get to it and potentially modify or sanitize it. That raw response is well formatted JSON according to jansson.

We also have a functional test (`mining.py`) that uses Python to connect to the node, issue a `getblocktemplate` call and parse the returned JSON. This works as well. Other users of the mining RPC interface also report no errors here.

So unless you can provide some information to identify a specific problem in the node I think we have to suspect a problem in your reading and processing of the response from the node.

One thing that definitely changed in the sending of the `getblocktemplate` response between 1.0.6 and 1.0.7 is that we started using a chunked HTTP response rather than just constructing the entire response in memory and sending it in one. I wonder if it's possible you have a bug handling chunked HTTP?

**Comment by kr1z1s** [comment]
You can repeat this error yourself by installing
https://bitbucket.org/ckolivas/ckpool-solo/src/master/

чт, 13 янв. 2022 г. в 11:37, richmills3 ***@***.***>:

**Comment by kr1z1s** [comment]
> One thing that definitely changed in the sending of the `getblocktemplate` response between 1.0.6 and 1.0.7 is that we started using a chunked HTTP response rather than just constructing the entire response in memory and sending it in one. I wonder if it's possible you have a bug handling chunked HTTP?

Yes. I think it's because of that.

**Comment by CassClark** [comment]
@kr1z1s did you manage to get the JSON that does not parse correctly?  This would allow @richmills3 to investigate further for you.

**Comment by richmills3** [comment]
@CassClark I'm not sure we need the JSON anymore; we're pretty sure the problem is that ckpool doesn't handle HTTP chunked encoding and so is miss-interpreting the message sent back from the node.
