### ISSUE TITLE
Can't reach current block height

### ISSUE THREAD

**Issue by aad3365** [bitcoin-sv/bitcoin-sv#243]
My bsv node can't reach to the current blocks.
When approximately 15000 ~ 20000 blocks to sync remain, node tells something wrong on mempool and does rollback.
Here's the log.
![image](https://user-images.githubusercontent.com/17927890/151466190-159c64f8-1544-4fbd-92dc-589c99cccea0.png)
![image (1)](https://user-images.githubusercontent.com/17927890/151466192-190d673a-ebdc-4a71-97d1-00dc147d43ff.png)
![image (2)](https://user-images.githubusercontent.com/17927890/151466198-d9224af8-7c2b-44d0-be72-19a05722d41f.png)

Running configs
```
./bin/bitcoind \
  --server -txindex=1 \
  -port=8888 \
  -rpcbind=0.0.0.0 \
  -rpcport=3000 \
  -rpcallowip=0.0.0.0/0 \
  -rpcuser=$RPCUSER \
  -rpcpass=$RPCPASS \
  -rpcworkqueue=1024 \
  -datadir=$DATADIR \
  -excessiveblocksize=10000000000 \
  -maxstackmemoryusageconsensus=200000000 \
  -maxmempool=1000000 \
  -datacarriersize=100000 \
  -limitancestorsize=100000 \
  -limitdescendantsize=100000 \
  -dbcache=40000 -printtoconsole
 
```

I'm running bsv 1.0.10 on ubuntu 18.04

**Comment by CassClark** [comment]
@aad3365 what version of the node software are you running and what is your machine spec?

**Comment by CassClark** [comment]
apologies i see you are running v1.0.10, so if you can confirm the machine spec thanks

**Comment by aad3365** [comment]
Wait a sec,, is 20G memory small to run bsv?
I found docker memory setup to run container under 20G memory.
I will try without this option.

**Comment by CassClark** [comment]
Hi @aad3365  

thanks for the update.

here are our recommended specs:
https://bitcoinsv.io/documentation/miners/system-requirements/

**Comment by aad3365** [comment]
@CassClark Yea the limitation was the problem. My node successfully finished sync.

**Comment by CassClark** [comment]
@aad3365 thanks for the update - glad to hear the issue is now resolved.
