### ISSUE TITLE
how to used getaddressbalance rpc  cmd on bitcoin-sv

### ISSUE THREAD

**Issue by nakinthorn** [bitcoin-sv/bitcoin-sv#25]
how to used getaddressbalance rpc  cmd on bitcoin-sv

I try to add  getaddressbalance rpc  cmd on bitcoin-sv node
but it not works

**Comment by rockandruby** [comment]
@nakinthorn are you sure that api has that method? The only I know is getbalance

**Comment by nakinthorn** [comment]
https://github.com/BTCGPU/BTCGPU/commit/1c1d93de551d778c7e868ebe6cff66e53d09e712

try this

**Comment by rockandruby** [comment]
@nakinthorn but it is implemented for bitcoingold core. Anyway I get Method not found on my sv core

**Comment by nakinthorn** [comment]
I need to run insight api on bitcoin-sv are u have solution ? @rockandruby

**Comment by rockandruby** [comment]
@nakinthorn No, I don't

**Comment by shweta037** [comment]
> I need to run insight api on bitcoin-sv are u have solution ? @rockandruby

Is there any way to generate BCHSV address using insight or bitcore library please help...

**Comment by rockandruby** [comment]
@shweta037 The only way I know is native bitcoin-core sv usage

**Comment by shweta037** [comment]
> @shweta037 The only way I know is native bitcoin-core sv usage
Thanks for reply...
oh can i get the reference...how to differentiate the BCHSV address from BCH..Please guide me...

**Comment by nerverwind** [comment]
bitcoind with params: -checkblocks=10 -checklevel=1

It's work for me.

**Comment by Danconnolly** [comment]
Closing, no response.
