### ISSUE TITLE
sync block from xxx blockid

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/bitcoin-sv#252]
THE BSV node is too big  to waste ssd,

Could i apply a request to add a command to bitcoind server;

so that i could sync block from the block according command params,

**Comment by lijianl** [comment]
does any body have any responsible for the issue

**Comment by Danconnolly** [comment]
Do you mean that you want to sync the blockchain from a particular block to the tip of the chain, instead of from the genesis block?

**Comment by lijianl** [comment]
> Do you mean that you want to sync the blockchain from a particular block to the tip of the chain, instead of from the genesis block?

yes, when is use `genesisactivationheight=620538` in bitcoin.conf,  it still sync from height=0, sync from a particular block will very helpful especially when `txindex=1` was set,

 or could you give some hit to change source code by myself

**Comment by lijianl** [comment]
does any body responsible for the issue

**Comment by Danconnolly** [comment]
I'm looking into it.

**Comment by Danconnolly** [comment]
OK, thats not what this option is for. This option is related to the Genesis upgrade and should not be used on mainnet or testnet.

We do not have the option to start syncing the chain from a particular height. It is something that is desirable, and it is on our long term backlog, but its not something we are working on now and we are not planning to work on it in the near future.

Note that our primary users are miners. Miners need the full utxo set, which would not be available if you sync from a particular height.

**Comment by lijianl** [comment]
> Genesis upgrade

get it
