### ISSUE TITLE
ask for public node

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/bitcoin-sv#253]
do  you guys  have any public node for service?

the bitcoinsv source code  is too bad to system, there two many limitation

**Comment by Danconnolly** [comment]
I'm afraid not, the RPC interface is only intended for internal use and contains commands that would cause issues.

You could try https://developers.whatsonchain.com/#introduction.

**Comment by lijianl** [comment]
> I'm afraid not, the RPC interface is only intended for internal use and contains commands that would cause issues.
> 
> You could try https://developers.whatsonchain.com/#introduction.

The browser has too low limit for an available service, not enough to scan tx for a  wallet

**Comment by Danconnolly** [comment]
The "browser"? They have a JSON API.
