### ISSUE TITLE
sync exit by OOM

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/bitcoin-sv#254]
```
txindex=1
server=1
port=xxxx
rpcport=xxxx
rpcallowip=0.0.0.0/0
reindex=1
debug=1
excessiveblocksize=10000000000
maxstackmemoryusageconsensus=200000000
maxmempool=2000
maxsigcachesize=250
maxscriptcachesize=250
maxconnections=7
mempoolexpiry=72
```

does any config not enough for the bsvnode, because of sync stop out by `Error: Out of memory. Terminating.`

**Comment by Danconnolly** [comment]
See https://bitcoinsv.io/documentation/miners/system-requirements/

**Comment by lijianl** [comment]
> See https://bitcoinsv.io/documentation/miners/system-requirements/

i have seen this, i want to know whether there any more debug-info to locate the limitation? mem or HD or any config-item

**Comment by lijianl** [comment]
> See https://bitcoinsv.io/documentation/miners/system-requirements/

```
2022-03-21 23:59:08 [msghand] Leaving block file 4354: CBlockFileInfo(blocks=1, size=324973208, heights=700732...700732, time=2021-08-17...2021-08-17)
2022-03-21 23:59:08 [msghand] Pre-allocating up to position 0x78000000 in blk04355.dat
2022-03-21 23:59:09 [msghand] Error: Out of memory. Terminating.
```

the log looks link HD is not enough? how to change the certain conf

**Comment by Danconnolly** [comment]
To me it looks like you have run out of RAM. To verify large blocks, you really do need 60GB of RAM.

You could also check the system log, usually /var/log/syslog. Look for lines showing an out of memory error, or the string "killed".

**Comment by CassClark** [comment]
closing due to time passed without further response / request for further assistance.
