### ISSUE TITLE
Unable to get hex dump of block 00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0

### ISSUE THREAD

**Issue by Polve** [bitcoin-sv/bitcoin-sv#258]
### Describe the issue

I'm unable to get a hex dump of block #733601 , whose hash is in the subject.

The command "getblock 00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0" gives a json with the right information, but by adding the parameter "0" that requests a hex dump of the block I get a 4GB file (instead of 2.4 like it should) where for more than one gigabyte there are only spaces (0x20, see dump below)

#### list of the steps to reproduce below:
1. bitcoin-cli getblock 00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0 0 > /00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0.hex
2. size of file 00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0.hex: 4294967296 bytes
3. this is the output of "od -t x 00000000000000000f4a8e63b3c8d234e69f02054a1886ebf154aadac296f7f0.hex" (of course just the few initial lines):
```
0000000 20202020 20202020 20202020 20202020
*
14760522360 20202020 20202020 30653030 31323465
14760522400 37313530 33373430 64343863 34646463
14760522420 33346635 39393661 65376235 35626135
14760522440 39656565 36343863 64396135 64306336
14760522460 30303030 30303030 30303030 30303030
14760522500 66396634 62303564 63653038 34393763
14760522520 31363834 37326430 32376161 32356564
14760522540 37623361 64643666 32323062 35396465
14760522560 34646666 34306364 65616563 66666366
14760522600 66323863 32366134 65376165 38313231
14760522620 37386436 66393133 37376566 63306562
14760522640 31303030 30303030 31303030 30303030
14760522660 30303030 30303030 30303030 30303030
*
14760522740 30303030 30303030 30303030 66666666
14760522760 66666666 33303832 31333161 34306230
14760523000 66323863 32366134 37363830 66666666
14760523020 32613562 30303030 33313030 37346632
14760523040 32376636 63363936 31366336 66363035
14760523060 63366636 39366532 30326636 66393066
14760523100 64383661 30306632 30303030 31303030
14760523120 30616336 38333961 30303030 30303030
14760523140 36373931 34313961 36373238 31346430
14760523160 62303730 61353231 33303663 30393036
14760523200 36616564 30326166 32613061 33363536
14760523220 63613838 30303030 30303030 30303130
14760523240 30303030 66336130 37646434 61366566
14760523260 61373237 39323237 37653062 34343938
14760523300 32656438 33393762 33633466 32326666
14760523320 31333464 35393534 30346362 66313262
14760523340 37323730 32303464 30303030 62363030
14760523360 30333834 32303534 30303132 61316439
14760523400 63653535 39653531 36373761 65663335
14760523420 66326436 38313661 63346331 37396433
14760523440 66396136 66303765 66633237 66306663
14760523460 61313236 39343234 36386332 30323230
14760523500 63323836 36336536 61313762 31323330
```

### What version of bitcoin-sv are you using?
I tried with version 1.0.7 that I then upgraded to 1.0.10 without any change in the result.

I tried on different machines with linux, 64GB of ram and fast CPU (ryzen 7)

**Comment by Danconnolly** [comment]
Thank you for the complete error report.

I've confirmed the error with version 1.0.10.

**Comment by CassClark** [comment]
Internal ticket raised to track issue: SVN-1995

**Comment by pfromberg** [comment]
A workaround exists. A fix to this issue is now scheduled for future development
