### ISSUE TITLE
what should be minminingtxfee?

### ISSUE THREAD

**Issue by aad3365** [bitcoin-sv/bitcoin-sv#260]
I run node as rpc server, I'm confused what minniningtxfee should be.
Is it meaningful option for rpc server?

**Comment by Danconnolly** [comment]
The minminingtxfee setting will affect which transactions are present in the mempool of your node. We suggest you set it to the same value as miners are configuring.

I think Taal and Gorillapool are both setting this value to "0.0000005", which is equivalent to 50 sats/kb.
