### ISSUE TITLE
License clarification needed

### ISSUE THREAD

**Issue by ContrarianUnderscoreUnderscore** [bitcoin-sv/bitcoin-sv#262]
### Current license text.
The current license reads (in relevant part, emphasis added): "The Bitcoin SV blockchains are defined, for purposes of this license, as the Bitcoin blockchain containing block height #556767 with the hash "000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b" and that contains the longest persistent *chain of blocks accepted by this Software* and *which are valid under the rules* set forth in the Bitcoin white paper (S. Nakamoto, Bitcoin: A Peer-to-Peer Electronic Cash System, posted online October 2008) and *the latest version of this Software available in this repository* ...

It appears that compliant software must have certain "acceptance" and "validity" rules, but it's entirely unclear what the difference between those two are (if anything), since both involve "chains of blocks". 

### Comments by nChain personnel
[According](https://github.com/bitcoin-sv/bitcoin-sv/issues/261#issuecomment-1121994536) to @Danconnolly , "The bottom line is that if you want to use Bitcoin in a way that follows the rules *but is not accepted by this node software*, then please do go ahead and write your own node software. You can even fork this software, as long as you follow the terms of the license."

[Also according](https://github.com/bitcoin-sv/bitcoin-sv/issues/261#issuecomment-1121963581) to @Danconnolly , the "Bitcoin rules" will not change in the future.

[According](https://www.bailii.org/cgi-bin/format.cgi?doc=/ew/cases/EWHC/Ch/2022/667.html) to Craig Wright, nChain is planning on a change that would allow coins to be reassigned.

## Questions 

1. Is "accepted by this software" different from "valid under the rules"? @Danconnolly 's [comment](https://github.com/bitcoin-sv/bitcoin-sv/issues/261#issuecomment-1121994536) implies that they are different, but I can't see why that would be the case, considering that the license says *a chain of blocks* is "accepted" or not, while only *transactions* are generally "accepted" or not in standardness rules. Could you please clarify precisely what those two phrases mean?
2. What precisely are the "rules of Bitcoin"? Does this have a technical definition or set spec? My understanding was that the "consensus validity rules" of this software are exactly the "rules of Bitcoin". If this is not correct, please clarify.
3. Several consensus validity rule changes have been promised for BSV, including [adding support](https://web.archive.org/web/20200116233246/https://bitcoinsv.io/2019/12/20/bitcoin-sv-genesis-hard-fork-specification/#:~:text=Support%20the%20original%20sighash%20algorithm%20for%20transaction%20spending%20pre%2DGenesis%20UTXOs) for the original sighash algorithm, [restoring](https://wiki.bitcoinsv.io/index.php/Opcodes_used_in_Bitcoin_Script#:~:text=(-,This%20opcode%20is%20scheduled%20to%20be%20re%2Denabled%20in%20the%20Chronicle%20update),-OP_IF) certain opcodes, and [allowing coin reassignment](https://www.bailii.org/cgi-bin/format.cgi?doc=/ew/cases/EWHC/Ch/2022/667.html#:~:text=In%20contrast%2C%20Dr,by%2Dcase%20basis.). All three of these changes would affect the consensus validity rules. Are we now to understand that none of these changes will ever happen in the future?  
4. (Somewhat related to question (1.)) If I were to fork this repository and change only the *standardness* rules (ie - which *transactions* the software would "accept", relay, and put into a candidate block), would that comply with the terms of the license?
5. The license appears to allow for certain soft-forking changes. (To clarify, these are strict additions to the validity rules, such that every "valid" chain of blocks in the forked software is also "valid" in the original software, but there is a non-empty set of chains of blocks that are invalid in the forked software but valid in the original software.) Is this correct? If not, please explain why.
6. The license says, "...and are valid under the rules ... in .... *the latest version of this Software available in this repository or another repository designated by Bitcoin Association*". Since the Bitcoin rules will not change, isn't this superfluous?

**Comment by Danconnolly** [comment]
Please seek professional and independent legal advice.

**Comment by ContrarianUnderscoreUnderscore** [comment]
> Please seek professional and independent legal advice.

This is unhelpful, as *you* are the person who asserted that the rules of Bitcoin are fixed, yet it appears that nChain is planning on changing the rules. Can you at least clarify that?

**Comment by Danconnolly** [comment]
It is very helpful. You are asking advice about a legal document. I am not a lawyer. This forum (the github issue feature) is for technical issues and advice, not legal ones. It would be wise that if you wanted legal advice about a legal document that you consult a legal expert, and preferably an independent one.

nChain do not own this software, it is owned by the Bitcoin Association.

**Comment by ContrarianUnderscoreUnderscore** [comment]
I am asking a technical question about an assertion *you* made. Ignore the license for a moment and at least answer whether there are any plans on changing consensus code in the future, please.

More directly: absent emergency, unforeseen bugfixes, will the consensus rules that this software follows (ie - the set of chains of blocks that the software will build upon) change in the future?

**Comment by Danconnolly** [comment]
There is no concrete plan to re-enable OP_VER or add support for the original sighash algorithm.

**Comment by ContrarianUnderscoreUnderscore** [comment]
> There is no concrete plan to re-enable OP_VER or add support for the original sighash algorithm.

In your statement about "the Bitcoin rules ... will not change ", is that the type of "rules" you were guaranteeing will not change? 

Are there any plans for any future consensus-rule changes?

**Comment by Danconnolly** [comment]
This is not the forum for these questions.

**Comment by ContrarianUnderscoreUnderscore** [comment]
> This is not the forum for these questions.

I don't understand. You said (in this forum) that the "Bitcoin rules ... will not change".

What did you mean by that, *precisely*?
