### ISSUE TITLE
"Bitcoin rules" and future plans for BSV

### ISSUE THREAD

**Issue by ContrarianUnderscoreUnderscore** [bitcoin-sv/bitcoin-sv#263]
### Comments by nChain personnel
[According](https://github.com/bitcoin-sv/bitcoin-sv/issues/261#issuecomment-1121963581) to @Danconnolly , the "Bitcoin rules" will not change in the future.

[According](https://www.bailii.org/cgi-bin/format.cgi?doc=/ew/cases/EWHC/Ch/2022/667.html) to Craig Wright, nChain is planning on a change that would allow coins to be reassigned.

## Questions 

1. What precisely are the "rules of Bitcoin"? Does this have a technical definition or set spec? My understanding was that the "consensus validity rules" of this software are exactly the "rules of Bitcoin". If this is not correct, please clarify.
2. Several consensus validity rule changes have been promised for BSV, including [adding support](https://web.archive.org/web/20200116233246/https://bitcoinsv.io/2019/12/20/bitcoin-sv-genesis-hard-fork-specification/#:~:text=Support%20the%20original%20sighash%20algorithm%20for%20transaction%20spending%20pre%2DGenesis%20UTXOs) for the original sighash algorithm, [restoring](https://wiki.bitcoinsv.io/index.php/Opcodes_used_in_Bitcoin_Script#:~:text=(-,This%20opcode%20is%20scheduled%20to%20be%20re%2Denabled%20in%20the%20Chronicle%20update),-OP_IF) certain opcodes, and [allowing coin reassignment](https://www.bailii.org/cgi-bin/format.cgi?doc=/ew/cases/EWHC/Ch/2022/667.html#:~:text=In%20contrast%2C%20Dr,by%2Dcase%20basis.). All three of these changes would affect the consensus validity rules. Are we now to understand that none of these changes will ever happen in the future?

**Comment by Danconnolly** [comment]
Duplicate
