### ISSUE TITLE
Freezing and reassigning coins without corresponding private keys

### ISSUE THREAD

**Issue by ContrarianUnderscoreUnderscore** [bitcoin-sv/bitcoin-sv#264]
According to nChain Chief Scientist Craig Wright, nChain is actively working on updating this software to allow users to "recover" lost or stolen coins without needing the corresponding private keys:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/35772929/168141725-365c23c3-8857-4453-846e-39fcd7944ea8.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/35772929/168141953-d6eac475-bf0e-4ffa-827d-30cdd7d4bad6.png">

I appreciate that @Danconnolly [clarified](https://github.com/bitcoin-sv/bitcoin-sv/issues/262#issuecomment-1124209801) that there are no concrete plans to re-enable OP_VER or add support for the original sighash algorithm, but could anyone please shed light on whether there are concrete plans to enable this coin "recovery" behavior, and if there are, when we can expect them? 

This seems like a rather drastic change ("much more complex" according to Wright), so it's in the best interest of anyone planning on forking this software to be aware of significant upcoming technical changes.

**Comment by Danconnolly** [comment]
We have no comment on this topic.

**Comment by baryon** [comment]
Bitcoin is a consensus currency. It grew up with all kinds of threats. Even if Dr. CSW wins a case in one country, it does not mean that BSV is subject to a particular judgment in other countries. Otherwise, BSV will lose consensus, meaning the collapse of community and price.
