### ISSUE TITLE
how to get bsv testnet faucets

### ISSUE THREAD

**Issue by taimurworks98** [bitcoin-sv/bitcoin-sv#267]
I can't find any place to get testnet faucets for BSV, all available links seem dead to me.
Is there any platform that still provides faucets for BSV?
My testnet address is: n3RyLTQsvnHRKGRhf6DV6UAwua6cqfDJzp (Sensilet Wallet)

**Comment by Danconnolly** [comment]
Try https://testnet.satoshisvision.network/.
