### ISSUE TITLE
ubuntu 20.04 error

### ISSUE THREAD

**Issue by david739** [bitcoin-sv/bitcoin-sv#268]
hello I'm installing on ubuntu 20.04 here is the installation procedure but I have an error can someone tell me what's wrong thank you

sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-
sudo apt-get install libdb-dev
sudo apt-get install libdb++-dev

git clone https://github.com/bitcoin-sv/bitcoin-sv.git bsv
sudo ./autogen.sh
sudo ./configure
sudo make
sudo make install

./autogen.sh

configure.ac:70: installing 'build-aux/compile'
configure.ac:30: installing 'build-aux/missing'
Makefile.am:15: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.16/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
src/Makefile.am: installing 'build-aux/depcomp'

./configure

config.status: executing libtool commands
Fixing libtool for -rpath problems.

Options used to compile and link:
  prod build    = no
  with wallet   = yes
  with zmq      = yes
  with test     = yes
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  debug enabled = no
  werror        = no

  sanitizers
          asan  = no
          tsan  = no
          ubsan = no

  memory allocators
       tcmalloc = no
       jemalloc = no

  target os     = linux
  build os      =

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++17
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter
  LDFLAGS       =

make

  CXXLD    libbitcoinconsensus.la
make[2]: Leaving directory '/home/pool/bsv/src'
make[1]: Leaving directory '/home/pool/bsv/src'
Making all in doc/man
make[1]: Entering directory '/home/pool/bsv/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pool/bsv/doc/man'
make[1]: Entering directory '/home/pool/bsv'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/pool/bsv'

make install

root@:~/bsv$ sudo make install
[sudo] password for pool:
Making install in src
make[1]: Entering directory '/home/pool/bsv/src'
make[2]: Entering directory '/home/pool/bsv/src'
make[3]: Entering directory '/home/pool/bsv/src'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libbitcoinconsensus.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libbitcoinconsensus.so.0.0.0 /usr/local/lib/libbitcoinconsensus.so.0.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so.0 || { rm -f libbitcoinconsensus.so.0 && ln -s libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so || { rm -f libbitcoinconsensus.so && ln -s libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so; }; })
libtool: install: /usr/bin/install -c .libs/libbitcoinconsensus.lai /usr/local/lib/libbitcoinconsensus.la
libtool: install: /usr/bin/install -c .libs/libbitcoinconsensus.a /usr/local/lib/libbitcoinconsensus.a
libtool: install: chmod 644 /usr/local/lib/libbitcoinconsensus.a
libtool: install: /usr/bin/ranlib /usr/local/lib/libbitcoinconsensus.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the ' -D__LIBTOOL_IS_A_FOOL__ ' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c bitcoind bitcoin-cli bitcoin-tx bitcoin-miner test/test_bitcoin bench/bench_bitcoin '/usr/local/bin'
libtool: install: /usr/bin/install -c bitcoind /usr/local/bin/bitcoind
libtool: install: /usr/bin/install -c bitcoin-cli /usr/local/bin/bitcoin-cli
libtool: install: /usr/bin/install -c bitcoin-tx /usr/local/bin/bitcoin-tx
libtool: install: /usr/bin/install -c bitcoin-miner /usr/local/bin/bitcoin-miner
libtool: install: /usr/bin/install -c test/test_bitcoin /usr/local/bin/test_bitcoin
libtool: install: /usr/bin/install -c bench/bench_bitcoin /usr/local/bin/bench_bitcoin
 /usr/bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 script/bitcoinconsensus.h '/usr/local/include'
make[3]: Leaving directory '/home/pool/bsv/src'
make[2]: Leaving directory '/home/pool/bsv/src'
make[1]: Leaving directory '/home/pool/bsv/src'
Making install in doc/man
make[1]: Entering directory '/home/pool/bsv/doc/man'
make[2]: Entering directory '/home/pool/bsv/doc/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 bitcoind.1 bitcoin-cli.1 bitcoin-tx.1 '/usr/local/share/man/man1'
make[2]: Leaving directory '/home/pool/bsv/doc/man'
make[1]: Leaving directory '/home/pool/bsv/doc/man'
make[1]: Entering directory '/home/pool/bsv'
make[2]: Entering directory '/home/pool/bsv'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libbitcoinconsensus.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/pool/bsv'
make[1]: Leaving directory '/home/pool/bsv'

**Comment by david739** [comment]
how do i turn it off i can't start bitcoind --daemon


~/bsv/src$ bitcoind --daemon
Mandatory consensus parameter is not set. In order to start bitcoind you must set the following consensus parameters: "excessiveblocksize" and "maxstackmemoryusageconsensus". In order to start bitcoind with no limits you can set both of these parameters to 0 however it is strongly recommended to ensure you understand the implications of this setting.

For more information of how to choose these settings safely for your use case refer to

**Comment by david739** [comment]
hello, is there anyone here, are you telling me that there is no one here who can get bitcoin-sv working in ubuntu

**Comment by matra774** [comment]
@david739  As error message specifies, you need to set mandatory parameters. Check the documentation here: https://node.bitcoinsv.io/sv-node/settings#mandatory-settings

**Comment by david739** [comment]
hi, thanks for the documentation, I'll read it, but can you please give me some commands to start it up?

**Comment by matra774** [comment]
Specify mandatory settings listed in the link that I provided  (excessiveblocksize, maxstackmemoryusageconsensus) on command line or configuration file.

**Comment by david739** [comment]
hello, thanks, but I'm probably blind, how to open the command line of sv node in ubuntu

**Comment by Danconnolly** [comment]
`./bitcoind  -excessiveblocksize=10GB -maxstackmemoryusageconsensus=200MB -minminingtxfee=0.00000050`

**Comment by david739** [comment]
thanks for the command it works now
