### ISSUE TITLE
Stealthex cryptocurrency exchange

### ISSUE THREAD

**Issue by Stealthexio** [bitcoin-sv/bitcoin-sv#27]
Hi everyone,
My name is Eric, I represent the crypto to crypto exchange service Stealtex.io.

We have already started supporting BitcoinSV coin and our customers can exchange SV for more than 150 coins.

We would like to find contact with you in order to be able to ask quick technical questions if they arise, as well as interact in open media if it is convenient for you.

You can always find me by mail info@stealthex.io

Hope to find contact as soon as possible

**Comment by Danconnolly** [comment]
Sent e-mail. Closing.
