### ISSUE TITLE
bitcoind.service

### ISSUE THREAD

**Issue by david739** [bitcoin-sv/bitcoin-sv#270]
hi i am trying to run bitcoind.service but it is showing an error can someone help me please ubuntu ubuntu 18.04, 20.04

bitcoind.service

[Unit]
Description=Bitcoin service
After=network.target
[Service]
Type=forking
ExecStart=/home/pool/bitcoin/bin/bitcoind -conf=/home/pool/bitcoin-data/bitcoin.conf -datadir=/home/pool/bitcoin-data -daemon
ExecStop=/home/pool/bitcoin/bin/bitcoin-cli -conf=/home/pool/bitcoin-data/bitcoin.conf -datadir=/home/pool/bitcoin-data stop
ExecReload=/bin/kill -s HUP $MAINPID
Restart=on-abnormal
TimeoutStopSec=120
KillMode=none
PrivateTmp=true
User=test
[Install]
WantedBy=multi-user.target

sudo systemctl start bitcoind.service

error
 sudo systemctl start bitcoind.service
Job for bitcoind.service failed because the control process exited with error code.
See "systemctl status bitcoind.service" and "journalctl -xe" for details.

**Comment by CassClark** [comment]
Internal Ticket raised: SVN-1992

**Comment by CassClark** [comment]
@david739 would you be able to provide further information please to help us investigate?
https://github.com/bitcoin-sv/bitcoin-sv/wiki/Data-required-by-Support
