### ISSUE TITLE
-26_66: mempool min fee not met

### ISSUE THREAD

**Issue by Ljzn** [bitcoin-sv/bitcoin-sv#274]
### Expected behaviour

Use bitcoin-sv node to broadcast this tx https://whatsonchain.com/tx/3ee3e91778a66e813ff0085af08ddb8314bd73208c39f5af89acee9633f97b5f

### Actual behaviour

Returns "-26_66: mempool min fee not met" , then we have to use the WoC api to broadcast it.

### What version of bitcoin-sv are you using?

1.0.10

**Comment by pfromberg** [comment]
This means your mempool was full at some point. The mempool acceptance fee will decay automatically. But you can speed up the process by restarting the node.

**Comment by Ljzn** [comment]
> This means your mempool was full at some point. The mempool acceptance fee will decay automatically. But you can speed up the process by restarting the node. After restarting the node the acceptance fee will be zero.

Maybe this mechanism can be removed? I don't think the local node's mempool status should affect the transactions being broadcast to other nodes.
