### ISSUE TITLE
Node stuck at height 755241

### ISSUE THREAD

**Issue by maayank** [bitcoin-sv/bitcoin-sv#275]
Our node is stuck for the last hour at block 755241, while we see peers with 755279 blocks.

getnetworkinfo:
```
{"result":{"version":101001100,"subversion":"/Bitcoin SV:1.0.11/","protocolversion":70016,"localservices":"0000000000000021","localrelay":true,"timeoffset":0,"txnpropagationfreq":250,"txnpropagationqlen":0,"networkactive":true,"connections":8,"addresscount":44364,"streampolicies":"BlockPriority,Default","networks":[{"name":"ipv4","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false},{"name":"ipv6","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false}],"relayfee":0.00000000,"minconsolidationfactor":20,"maxconsolidationinputscriptsize":150,"minconfconsolidationinput":6,"minconsolidationinputmaturity":6,"acceptnonstdconsolidationinput":false,"localaddresses":[],"warnings":"Warning: The network does not appear to agree with the local blockchain! Still waiting for block data for more details."},"error":null,"id":null}
```

getblockchaininfo:
```
{"result":{"chain":"main","blocks":755241,"headers":755279,"bestblockhash":"000000000000000006437cffa2b5bd3152416adb7df64ba50abb095f8f48360f","difficulty":75156551982.47322,"mediantime":1662021897,"verificationprogress":0.9999460972869165,"chainwork":"0000000000000000000000000000000000000000013b8f9687d669634693bf2b","pruned":false,"softforks":[{"id":"bip34","version":2,"reject":{"status":true}},{"id":"bip66","version":3,"reject":{"status":true}},{"id":"bip65","version":4,"reject":{"status":true}},{"id":"csv","version":5,"reject":{"status":true}}]},"error":null,"id":null}
```

Are others experiencing the same? What steps can we take to debug and solve this issue?

**Comment by Danconnolly** [comment]
Can you please supply recent log?

Also there is a diagnostic script (https://github.com/bitcoin-sv/bitcoin-sv/tree/master/contrib/diagnostic) that you can run. It will collect  important information that can help with diagnosing the issue.

The next block is large, 4GB. Can you please check your excessiveblocksize setting?

**Comment by maayank** [comment]
@Danconnolly , excessiveblocksize=100000000000.

We've solved it for now (not fully - still syncing and not at head, but there's progress) - what happened was that there was a limit of 16GB for the docker container containing the node and with the large blocks it reached that limit and killed the process. We've increased the memory of the instance and the limit.

**Comment by Danconnolly** [comment]
Thank you for replying and closing the ticket. 

That's an interesting cause, we'll make a note of that.
