### ISSUE TITLE
Add BitcoinSV services

### ISSUE THREAD

**Issue by HODLERTECH** [bitcoin-sv/bitcoin-sv#28]
Hello.
Please add fully featured Bitcoin SV block Explorer: https://bsvexplorer.info to services section on bitcoinsv.io website and our HODLER Open Source Multi-Asset Wallet (Windows and Android version) to the "wallets" subsection. Homesite of the wallet: https://hodler.tech

HODLER Wallet supports legacy and bech32 Bitcoin SV addresses, automatic and custom fee, importing/exporting private keys, HD seed.

Thank you and best regards.

Logo HODLER Open Source Multi-Asset Wallet: 
![200200](https://user-images.githubusercontent.com/36729396/49155488-53c6bc80-f31b-11e8-8687-302b0267e8c9.jpg)

**Comment by Fl4reTobiasH** [comment]
> Can I broadcast transactions to https://bsvexplorer.info? I'm looking for an explorer that I can broadcast to... if so any documentation?

Please write to us to get access to the API: contact (at) hodler.tech

**Comment by Danconnolly** [comment]
We'll get these added.

**Comment by Fl4reTobiasH** [comment]
Thank you very much and regards!

**Comment by ALFAcashier** [comment]
@Danconnolly please add https://www.alfacashier.com to the list of exchanges.

ALFAcashier is cryptocurrency automatic exchange service supporting many cryptocurrencies including Bitcoin SV and many others (sorta like ShapeShift or Changelly).

Buy link: https://www.alfacashier.com/buy/bitcoinsv
Sell link: https://www.alfacashier.com/sell/bitcoinsv

Thank you.

**Comment by Danconnolly** [comment]
Was done, site appears to be down right now.
