### ISSUE TITLE
`#include <mutex>` needed in `txn_util.h` & `txn_recent_rejects.h`

### ISSUE THREAD

**Issue by TinosNitso** [bitcoin-sv/bitcoin-sv#283]
### Describe the issue
Somewhere near line 10 both [txn_util.h](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/txn_util.h) & [txn_recent_rejects.h](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/txn_recent_rejects.h) need an extra line:
`#include <mutex>`

Otherwise when I go to build I get a whole bunch of errors, with specific advice that the line should be added. The errors occur when I `./configure`. Maybe there's a flag which would allow `<shared_mutex>` to work instead of `<mutex>`. 🤔

### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
Just following the standard [instructions](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/build-unix.md) causes this.

### What version of bitcoin-sv are you using?
Self compiled bitcoin-sv-1.0.11

### Machine specs:
- OS: VirtualBox Ubuntu 22.04.

Oh, another bug is that it still won't work without
`./configure --disable-hardening`
I haven't actually tried running the node yet, to sync from the start.

**Comment by pfromberg** [comment]
Hi Tinos,

your problem suggests you have configured an environment that is very unusual on Ubuntu. I expect to see those errors on Suse which we do not support.  I will make sure those mentioned headers will be included in the next version we deploy.

--disable-hardening is ok for debugging but it makes a production system less safe.

What compiler version are you using?

Thanks publishing this issue.

**Comment by TinosNitso** [comment]
Thanks, I've successfully built & run v1.0.13 without any issue, but I still used `--disable-hardening`. Maybe for a future release I'll try without it. I'm using gcc 11.2.0.

**Comment by pfromberg** [comment]
Can you give me the exact error message emitted by ./configure when you remove the --disable-hardening option?

**Comment by TinosNitso** [comment]
I just went over the whole build again & have verified the latest version builds fine  without `--disable-hardening`. 🙂

However the files come out a much smaller size after running `strip *`. e.g. comparing official & my results I get
bitcoind   14.7MB  8.5MB
bitcoin-cli  4.6MB  0.7MB
bitcoin-tx  4.9MB  1.3MB

Maybe they're stripped differently.

**Comment by pfromberg** [comment]
Thanks for the update Tino. We do not strip the debug information just in case we need that information to inspect a core dump.

**Comment by pfromberg** [comment]
Thanks for the update Tino. You may be linking some libraries dynamically which the gitian build links statically.
