### ISSUE TITLE
IBD time performance

### ISSUE THREAD

**Issue by ZoideNFT** [bitcoin-sv/bitcoin-sv#285]
This issue tracker is only for technical issues related to bitcoin-sv.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
I was trying to setup a node with version 11 many times and atm I can't finish the initial block download without spending a lot of time. 
First try 1,5 months --> not finished
Second try with DBcache 8GB --> fastest at the beginning but... and here is the point of the issue.

I taked samples during the IBD on the second try and I saw that the block download speed decrease drastically as the block height grows. It happens not because the size of the blocks but because the quantity of them. Obviously the time is increased too if the block size is bigger (becouse data download is needed), but the processing speed was decreasing linealy from 0 to 85% of the total process. From 0 to 85% the block size is small so the problem is not the size of them.

This raises a big problem in the future, because if not corrected, once chain has (let's imagine) 50TB with 1M blocks, the IDB will be impossible to reach out in a acceptable time, and nobody can set up a node from 0, making bitcoin structure only reachable a little cuantity of people who can achive the costs of the deployment and the time too.  

Maybe something is misconfigured in my node? Maybe I'm misunderstanding something? I don't know, but atm all of this has some sense, hope this can help.

![image](https://user-images.githubusercontent.com/117897120/201035852-ab1444f1-31ca-4007-9208-33e464fdf2a9.png)

### Expected behaviour
Imo this need to be a process similar to download the data from the network. If the chain is 2TB sized, the process has to spend the same or similar time to finish as the regular download of 2TB. Maybe more because of the validations, but mantaining a stable speed and not decreasing it.

### What version of bitcoin-sv are you using?
1.0.11

### Machine specs:
- OS: Ubuntu 22.04.1 LTS
- CPU: 4 CPUs x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
- RAM: 24GB
- Disk size: 250GB
- Disk Type (HD/SDD): SSD

- SWAP: 10GB
- DBCACHE: 10GB
- bitcoin-data stored in a 8TB HDD 15rpm NAS mapped with NFS

### Any extra information that might be useful in the debugging process.

bitcoin.conf:

printtoconsole=1
#ZMQ
zmqpubhashtx=tcp://127.0.0.1:18332
zmqpubhashblock=tcp://127.0.0.1:18332

#Ports - Leave commented for defaults
port=9333
rpcport=9334

#rpc settings
rpcservertimeout=60
rpcworkqueue=600
rpcthreads=16
rpcallowip=0.0.0.0/0 
rpcpassword=password
rpcuser=user

#debug=1
dbcache=10000

##MANDATORY (NON-MINING)
excessiveblocksize=10GB
maxstackmemoryusageconsensus=200MB
minminingtxfee=0.00000050

##OPTIONAL (NON-MINING)
maxmempool=25GB
maxsigcachesize=256MiB
maxscriptcachesize=256MiB
maxorphantxsize=64MB

##PERFORMANCE FAQS
blockdownloadtimeoutbaseibdpercent=600
blockdownloadtimeoutbasepercent=200

#multi-threaded options
#threadsperblock=4
#maxparallelblocks
#scriptvalidatormaxbatchsize
#maxparallelblocksperpeer
#maxstdtxvalidationduration=15
#maxcollectedoutpoints=1000000
#maxstdtxnsperthreadratio=10000
#maxnonstdtxvalidationduration

##CONNECTIONS
#maxuploadtarget=10MB
maxconnections=80

**Comment by pfromberg** [comment]
You will need at least 64GB of RAM but even then you will be swapping a bit.

250GB Disk Space is not even enough in pruning mode. Your configuration suggests you are not pruning. With a pruning node you will need at least 500GB and without pruning 10TB and that number will increase in a few month.

We will implement measures to improve IBD speed in the near future but the minimum hardware requirements will not be reduced by those changes.

**Comment by CassClark** [comment]
resolved - closing ticket.
