### ISSUE TITLE
Sync stalled at block 563637

### ISSUE THREAD

**Issue by bobsummerwill** [bitcoin-sv/bitcoin-sv#287]
I have been running a "pleb sync" of BSV as an experiment with a well specced tower PC.

I have been tweet-threading my progress, which was initially all on an 16TB HDD, then restarted with a 500GB NVMe with a soft link to the HDD for just the "blocks" subdirectory, at Shadders suggestion.

It made rapid progress before stalling completely early into the BSV era, with only 3-4 peers and no forward progress whatsoever.

I wonder whether MY NODE might have been blacklisted by other nodes because of its own lack of forward progress?

I will add links to appropriate tweets and log files here as comments.

Best wishes!

**Comment by bobsummerwill** [comment]
End of Full thread here (read from the top):
https://twitter.com/BobSummerwill/status/1599185734216593408

Machine specification here:
https://twitter.com/BobSummerwill/status/1595679048570908672

End of bitcoind.log
https://drive.google.com/file/d/174m1Fblr91yC2bF4EMKRQRPtncbwHlrt/view

getinfo:
https://drive.google.com/file/d/1NciHqokaIoZvRvoRTlX24OioRxBeeKOv/view

getnetworkinfo:
https://drive.google.com/file/d/1AL8Su8iJr3gxM62hIbyviYWRRRkAtTIx/view

**Comment by bobsummerwill** [comment]
>> The version of the node software

1.0.13

>> OS + version.

Ubuntu Ubuntu 22.04.1 LTS

>> The machine specification. The machine should satisfy the minimum system requirements. See https://www.bitcoinsv.io/svnode#system-req.

64.0 GiB memory (and 64 GiB swap)
12th Gen Intel® Core™ i5-12600K × 16
500GB NVMe + 16TB HDD (datadir on NVMe and "blocks" mapped to the HDD)

>> The node log file (must cover the incident and possibly some time either side of the incident).
https://drive.google.com/file/d/174m1Fblr91yC2bF4EMKRQRPtncbwHlrt/view

>> bitcoin.conf + any command line parameters passed to bitcoind.

No conf file.

./bitcoin-sv-1.0.13/bin/bitcoind -minminingtxfee=0 -maxstackmemoryusageconsensus=1000000000 -excessiveblocksize=100000000 -datadir=./data

>> If the issues is transaction related, then a copy of the transaction.

N/A

>> If the node crashed, the core dump.

N/A

>> Description of the build origin. E.g. Is this an official gitian build or a locally compiled node?

Unzipped official binaries

**Comment by bobsummerwill** [comment]
Here is the final block:
https://whatsonchain.com/block/00000000000000000152aebb08736901cd73e8ee2c2daba8d3f3117a7d9ae3c6

I just did a fresh sync from genesis, this time with wired ethernet connection.   That got the same block in under 9 hours but again stalled on the same block, now with 0 peers.

**Comment by bobsummerwill** [comment]
End of twitter thread:
https://twitter.com/BobSummerwill/status/1599825667096727552

I cannot progress further.   Awaiting feedback here, and happy to provide further information as required and/or rerun with more diagnostics or logging.

**Comment by kurtwuckertjr** [comment]
I'm not sure why you would have no peers at that block except that perhaps it has a lot of payments and the large volume of signatures is either making it crawl slowly or causing some other unknown crash. 

However, if you need peers, you can use GorillaPool peers manually added: 

addnode=178.63.43.123
addnode=107.6.17.35
addnode=23.250.19.252
addnode=99.127.49.102

**Comment by bobsummerwill** [comment]
Thanks for those, @kurtwuckertjr.
I'll wait to see if there is some other suggestion from the team.

BTW, do you have your "max connections" configured higher than 8?  I am wondering whether that might be necessary for BSV given the lack of nodes, or maybe that would not make a difference.    I was thinking that if other nodes end up blacklisting me for whatever reason, that it might be a death sentence.

**Comment by kurtwuckertjr** [comment]
Nope. We use the default 8. 

I can’t imagine anyone blacklisting you.

**Comment by bobsummerwill** [comment]
Right, thanks, @kurtwuckertjr.

To be clear, by "blacklisting", I am not referring to an intentional human action, but to well connected nodes deciding that my node was not "behaving".   Like my own node is dropping connections other nodes:

Misbehaving: 162.62.21.182:8333 peer=345 (0 -> 100) reason: invalid-UA BAN THRESHOLD EXCEEDED

I don't think it is coincidental that my node went down to 0 nodes not very far into "BSV zone".   Prior to that it was possible to peer with all BTC nodes, then all BCH+BSV nodes, but then finally only BSV nodes (of which we know there are few.

**Comment by matra774** [comment]
>`invalid-UA BAN`

This is OK. It usually indicated remote node is BCH or BSV node. It can be controlled with  the following option: https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/init.cpp#L1145

Default is:
https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/policy/policy.h#L155

Check the log files if there are any other ban reasons.

**Comment by kurtwuckertjr** [comment]
Yes, when we synchronize at GorillaPool, we usually accept peers from everyone until the BSV era, and then we proactively block connections to BTC and BCH nodes going forward. There’s no reason to have a big graph when the goal is clearly defined.

**Comment by bobsummerwill** [comment]
Third run through with exactly the same result.

Peers drop from 8 to 0 within a minute straight after UpdateTip to block 563637, and then the same churn of the following forever, with zero forward progress:

[msghand] New outbound peer connected: version: 70016, blocks=769066, peer=85
or
[msghand] Misbehaving: 3.11.11.106:8333 peer=102 (0 -> 100) reason: invalid-UA BAN THRESHOLD EXCEEDED

I've added tracking for connections counts per minute, so can see that connection count is then fluctuating between 0,1,2,3 and very rarely 4 or 5 peers in the hours after that, so I'll leave this running for another day or two just in case it manages to resurrect itself.

**Comment by bobsummerwill** [comment]
@matra774 matra774 "Check the log files if there are any other ban reasons."

They are all identical.  I see 222 of them, all for the same reason.

@kurtwuckertjr So are you running without the default bans?  And then add more than those default bans?  ("abc","cash","bch")

You would need to be banning BTC nodes as well.   Do you have a magic set of strings you could share, please?    I assume that is my issue.   BCH nodes are always banned, but I still have all the BTC nodes.

**Comment by bobsummerwill** [comment]
All of this stuff SHOULD resolve itself in the end, but maybe it just cannot do so without some "assistance"?

**Comment by bobsummerwill** [comment]
OK - here are the peers that my node has now managed to connect to after many hours:
https://drive.google.com/file/d/1u0ceW5Bp3TAGrPLxQb1m2_UqFfG73_t5/view?usp=share_link

Does "starting height" mean that block height which that peer was at when my node first established the connection with them?

    "subver": "/Bitcoin SV:0.2.1(EB2000.0)/",
    "startingheight": 620540,
    
    "subver": "/Bitcoin SV:1.0.1/",
    "startingheight": 707502,
    
    "subver": "/Bitcoin SV:1.0.11/",
    "startingheight": 614020,
    
    "subver": "/Bitcoin SV:1.0.11/",
    "startingheight": 614020,
    
    "subver": "/Bitcoin SV:1.0.10/",
    "startingheight": 761146,
    
It looks like only the last one is near the tip of the chain, and I would at least hope that one should be helping my node progress?

**Comment by bobsummerwill** [comment]
OK - this is interesting, and I should have checked it earlier.
The NEXT block was the first over 99MB.

https://whatsonchain.com/block-height/563638

When starting bitcoind, there is no default setting for "excessiveblocksize" or for "maxstackmemoryusageconsensus".  These have to be specified by the user either on the command-line or in the config file.

The URL which the client points to is a broken link:
https://www.bitcoinsv.io/choosing-consensus-settings/

So I will have found my defaults from some other Google search which presumably took me to some old information.   Actually, this will explain how my first run worked, because I remember manually updating the config file for that time but then the whole directory being deleted for my subsequent runs, losing my original settings by accident.   I restored them as command-line settings for subsequent runs, but must have got old ones the second time around.

Now taking them from this press release and will restart the client:
https://bitcoinassociation.net/taal-brings-4gb-blocks-to-bsv-with-breakthrough-upgrade-what-miners-should-know/

excessiveblocksize=10000000000
maxstackmemoryusageconsensus=200000000

**Comment by bobsummerwill** [comment]
New end of twitter thread:
https://twitter.com/BobSummerwill/status/1600388470366953472

I have actually just done a complete restart.  I had very poor peers at the end of the previous run (presumably ones which were not well connected to the miners either, because they could not have dealt with blocks over 100MB themselves).

**Comment by bobsummerwill** [comment]
I have got passed that block now.

It was a client misconfiguration issue.   Maybe I was missing some configuration for extended logging.   It would have been used to know that potential new block tips were being rejected from my client because they were too large, but maybe that is not a simple thing to do, because we cannot know if they were valid, so maybe too spammy?
