### ISSUE TITLE
Broken URL in error message

### ISSUE THREAD

**Issue by bobsummerwill** [bitcoin-sv/bitcoin-sv#288]
If the user omits to specify maximum sizes for blocks and memory use on the command-line or in the configuration file then an error message appears, including the following URL, but the link is broken.

https://www.bitcoinsv.io/choosing-consensus-settings/

This is happening from 1.0.13 prebuilt binaries but I imagine has been broken for a while.

**Comment by bobsummerwill** [comment]
Here is the line of code with the broken URL:
https://github.com/bitcoin-sv/bitcoin-sv/blob/b489c32ef55d428c5c3825d5526de018031a20af/src/bitcoind.cpp#L136

**Comment by bobsummerwill** [comment]
PS. As well as the URL being broken, that line is missing the trailing newline so swaps badly in terminal.

**Comment by CassClark** [comment]
@bobsummerwill thanks for making us aware of the issue.  It's been escalated internally for investigation / resolution.

I'll update you once fixed.

Internal ticket number: BSD-16

**Comment by CassClark** [comment]
@bobsummerwill 

Having checked, the following link will provide you with the node settings.  May I ask where you came across the link you provided please - I believe it came from our old website, therefore if it's still referenced somewhere within our documentation, I'd like to ensure it's updated. 


[https://node.bitcoinsv.io/sv-node/settings#method-to-choose-mandatory-consensus-parameter-values](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnode.bitcoinsv.io%2Fsv-node%2Fsettings%23method-to-choose-mandatory-consensus-parameter-values&data=05%7C01%7Cc.clark%40nchain.com%7C78c3f83cc0e34404105b08dae313ce50%7C6e031f8d35cc44c5b695c8d2958c0550%7C1%7C0%7C638071972396083123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=uWho8J1q8Ed7lBf4Yzi0hdyvizgIQRzHJnoulsTvfUk%3D&reserved=0) 

Many thanks

**Comment by bobsummerwill** [comment]
Thanks, @CassClark.
I worked out the right settings myself in the end, but the correct link in the client will help others.
And don't forget the newline on the end :-)
Best wishes.

**Comment by CassClark** [comment]
@bobsummerwill thank you.
