### ISSUE TITLE
When replay protection release ?

### ISSUE THREAD

**Issue by nakinthorn** [bitcoin-sv/bitcoin-sv#29]
When replay protection release ?

**Comment by Danconnolly** [comment]
We are consulting with businesses, miners, and the community on this topic. We expect to present a plan for this soon, for further feedback and discussion.

**Comment by jddebug** [comment]
In the mean time is there a way to safely send from this current SV wallet without losing your BCH and vise versa?

**Comment by cypherdoc** [comment]
@jddebug there are several wallets that split ABC/SV

**Comment by gitzhou** [comment]
Hi there

One question about replay protection 
From tech aspect, if we change the value of SIGHASH_FORKID, then we have the replay protection, right?

Related issue #34

**Comment by y0ke** [comment]
@gitzhou `SIGHASH` has 32 bits length. And its least significant byte is used to identify sighash's type (`ALL` `0x01`,`NONE` `0x02`, `SINGLE` `0x03` and `ANYONECANPAY` `0x80`) and the `SIGHASH_FORKID` flag `0x40`. Remaining 24 bits are used as `FORK_ID` which is representing which fork coin it is.
ABC uses `0` as FORK_ID.
So,The easiest and simplest way to achieve 2 way replay protection is to set a number which is not used in other coins yet as `FORK_ID`.
Personally I think `3104` is good for SV. It's not used in any other coins yet and it stands for `3=sa 10=to 4=shi` using Japanese spelling way to convert words into numbers.

**Comment by screeni** [comment]
> When replay protection release ?

this will occur in the first quarter of 2019

**Comment by jddebug** [comment]
How is this feature progressing? Coinbase has made BSV available to its users who had BCH. I have all my BCH in a full node wallet and same with my BSV. I am concerned that if I move either wallets contents that I may loose the others.

**Comment by Xsq147** [comment]
When replay protection release ?

**Comment by breign** [comment]
What replay protection? This is Bitcoin.

**Comment by Pheromon** [comment]
LOL

A bitcoin that is slowing going to oblivion.

@Xsq147 : they don't add reply protection to limit the number of people dumping the coins

**Comment by jddebug** [comment]
screeni said first quarter 2019. Pretty sure that has come and gone.

**Comment by Danconnolly** [comment]
We have no plans to implement replay protection at this time.
