### ISSUE TITLE
Ubuntu 22.10 compilation issue "error: variable ‘constexpr const std::array<unsigned char, 4> protocol_id’ has initializer but incomplete type"

### ISSUE THREAD

**Issue by student03012009** [bitcoin-sv/bitcoin-sv#291]
This issue tracker is only for technical issues related to bitcoin-sv.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

#### If so, please list the steps to reproduce below:
1. Ubuntu 22.10
2. Make latest release "bitcoin-sv-1.0.13"
3. In file included from ./primitives/transaction.h:10,
                 from consensus/validation.h:11,
                 from abort_node.h:8,
                 from abort_node.cpp:4:
./script/script.h: In function ‘constexpr bool IsMinerInfo(bsv::span<const unsigned char>)’:
./script/script.h:307:38: error: variable ‘constexpr const std::array<unsigned char, 4> protocol_id’ has initializer but incomplete type
  307 |     constexpr std::array<uint8_t, 4> protocol_id{0x60, 0x1d, 0xfa, 0xce};

### Expected behaviour
Tell us what should happen
should compile a binary

### Actual behaviour
Tell us what happens instead
doesn't compile a binary

### What version of bitcoin-sv are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

https://github.com/bitcoin-sv/bitcoin-sv/archive/refs/tags/v1.0.13.tar.gz

### Machine specs:
sufficient for non-production

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `bitcoind.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

$ cat config.log | grep -B 1 fatal 
######################
g++: error: unrecognized command-line option '-V'
g++: fatal error: no input files
--
g++: error: unrecognized command-line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
--
g++: error: unrecognized command-line option '-V'
g++: fatal error: no input files
--
g++: error: unrecognized command-line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
--
configure:6219: g++ -std=c++17 -c   conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
--
configure:6261: g++ -std=c++17 -c -g  conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
--
configure:6277: g++ -std=c++17 -c   conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
--
configure:6294: g++ -std=c++17 -c -g  conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
--
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
--
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
--
gcc: error: unrecognized command-line option '-version'
gcc: fatal error: no input files
--
configure:15530: g++ -std=c++17 -E  conftest.cpp
conftest.cpp:22:10: fatal error: ac_nonexistent.h: No such file or directory
--
configure:15586: g++ -std=c++17 -E  conftest.cpp
conftest.cpp:22:10: fatal error: ac_nonexistent.h: No such file or directory
--
configure:23356: gcc -E  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.c
conftest.c:24:10: fatal error: ac_nonexistent.h: No such file or directory
--
configure:23412: gcc -E  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.c
conftest.c:24:10: fatal error: ac_nonexistent.h: No such file or directory
--
configure:25472: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:59:10: fatal error: sys/endian.h: No such file or directory
--
configure:25954: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:12: fatal error: sys/sysctl.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: bdb5.3/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: libdb5.3/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: db5.3/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: bdb6.0/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: libdb6.0/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: db6.0/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: bdb6.1/db_cxx.h: No such file or directory
--
configure:26244: g++ -std=c++17 -c -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:67:18: fatal error: libdb6.1/db_cxx.h: No such file or directory

**Comment by richmills3** [comment]
I tried to reproduce the build failure locally on Ubuntu 22, but it works for me here.

Could you please upload the full contents of your `config.log`, and also the full output from your:
```
./autogen.sh
./configure
make
```

E.g. as I have here:
[build.txt](https://github.com/bitcoin-sv/bitcoin-sv/files/10838145/build.txt)

Thank you.

**Comment by richmills3** [comment]
Never mind; I have managed to reproduce your issue now.

The problem is a missing `#include <array>` in the file `src/script/script.h` that is causing a problem for the updated version 12 of gcc in Ubuntu 22.10. This missing include is already fixed in our next release branch, so when the next 1.0.14 release comes out it should build for you.

If you need to build 1.0.13 you can either add the missing include line yourself locally and build, or use an older version of  gcc (11).
