### ISSUE TITLE
Is the current transaction fee rate fixed, and if so, what is it?

### ISSUE THREAD

**Issue by bajian** [bitcoin-sv/bitcoin-sv#295]
I just started getting into BSV.
1、I found that the `estimatesmartfee`  and `estimatefee` have both been removed.
2、And the [Deterministic transaction fee calculation](https://bsvdevcon.net/blog/bitcoin-sv-miner-fee-calculation-and-merchant-api-mapi) article :  0.5 sat/B
3、Now about [0.05 sat/B](https://whatsonchain.com/tx/a23f6e9fcc1ab1c190fa8f58d801d204ac6eb501a854b4fa9694c7b9d1439241) showing from the explorer 

So I want to know what the latest fee calculation rule is?

**Comment by bajian** [comment]
Do I have to install mAPI for this feature

**Comment by rt121212121** [comment]
No. The current way that applications like wallets get fee quotes, is to use the merchant API (or mAPI) to ask miners directly. We do not need to run it ourselves. These have expiry dates. The in-development version of ElectrumSV for instance, gauges the fees from various miner run mAPI servers and chooses one of these to broadcast.

Just poll the fee quote (which as an expiry date) with an web request and use it. No need to run a node. No need to run a mAPI server, which would also require running a node.

https://github.com/bitcoin-sv-specs/brfc-merchantapi#2-get-fee-quote

Then broadcast using the mAPI server you select.

https://github.com/bitcoin-sv-specs/brfc-merchantapi#3-submit-transaction

One miner who provides this is TAAL although they require an API key and signing up, so this may not suit your use case:

https://docs.taal.com/core-products/transaction-processing/mapi-endpoints

Another miner who provides this is GorillaPool who do not require an API key or signing up (we/ElectrumSV prefer this one):

https://mapi.gorillapool.io/

**Comment by rt121212121** [comment]
If you have questions like this, you can also go to the [Bitcoin SV discord](https://discord.com/invite/bsv) to ask for assistance and might get more prompt answers where it does not rely on technical support by the node team.

**Comment by bajian** [comment]
Okay, thank you very much for your help. I am currently trying TAAL, but it did not return the mainnet API key. I am providing feedback on this issue with them.
By the way, I feel that this way (mAPI) is not very stable and reliabe for business .

**Comment by rt121212121** [comment]
One of the most vocal complaining parties about unreliability was HandCash, which would do some of the highest throughput transaction counts on Bitcoin SV, from what I understand their issues with mAPI have been resolved and it is generally considered stable now.

**Comment by rt121212121** [comment]
I recommend GorillaPool, having spoken with Kurt, I understand there is no API key nor no plans to require one. mAPI will be going away at some point in any case, once it's replacement ARC is polished, from what I understand there.

**Comment by bajian** [comment]
@rt121212121   Thank you for your nice suggestion. I will use multiple mAPI providers to ensure the stability of the service.
