### ISSUE TITLE
Opcodes after `OP_RETURN` still cause bad-txns-too-many-sigops

### ISSUE THREAD

**Issue by gitzhou** [bitcoin-sv/bitcoin-sv#296]
Output

```
OP_FALSE OP_RETURN 01 00 ae
```

will cause error `64: bad-txns-too-many-sigops`.

Check [this code](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/script/script.cpp#L61) where `0xae` is `OP_CHECKMULTISIG` but `0x00` is not the minimal encoding of integer 0, so the error occurs.

The static check can't determine which part of the script will not be executed, but we still do this check.

This is weird, any comments?

**Comment by deanmlittle** [comment]
The very obvious solution is to simply remove minimal encoding altogether. It is not a part of the original protocol, nor is it a part of consensus, and there is no reason for it to be there. It was originally introduced to remove signature malleability, arguing non-minimal encoding would enable people to make multiple valid versions of the same transaction. This is no longer relevant, and custom scripts, nsequence and nlocktime mean signature malleability is inevitable no matter what you do. There is no good reason to maintain minimal encoding going forward.

**Comment by gitzhou** [comment]
According to the [Genesis specification](https://github.com/bitcoin-sv-specs/protocol/blob/master/updates/genesis-spec.md#formal-grammar-for-bitcoin-script), `OP_RETURN` can be followed by any sequence of bytes.

It's neither about removing minimal coding nor about signature malleability. We see no reason to do this kind of static checking, because it neither calculates `sigops` accurately, but also causes false positives, and BVM will check the resource usage of the script when it's running, as well as other indicators such as running time, which is already a protective measure.

**Comment by richmills3** [comment]
>We think there is no reason to do this static check.

That's my current view as well. I'm looking at it now but I can't immediately think of any reason to be performing sigops checks on a provably unspendable OP_FALSE OP_RETURN type script.

**Comment by gitzhou** [comment]
Thanks, @richmills3

Not just the `OP_FALSE OP_RETURN` script, it's just an example to reproduce this error.

One of our users found this false positive when using a custom script of the form `... script ... OP_RETURN xxx`, where `xxx` will not execute.

**Comment by gitzhou** [comment]
> of the form `... script ... OP_RETURN xxx`

for example: `OP_1 OP_RETURN 01 00 ae`

**Comment by Danconnolly** [comment]
From genesis spec: https://github.com/bitcoin-sv-specs/protocol/blob/master/updates/genesis-spec.md

Section: Formal Grammar of Bitcoin Script

> OP_RETURN may appear at any location in a valid script. The functionality of OP_RETURN has been restored and is defined later in the section OP_RETURN Functionality. Grammatically, any bytes after an OP_RETURN that is not in a branch block are not evaluated and there are no grammatical requirements for those bytes.

It looks like a bug.

**Comment by xhliu** [comment]
When can we ship this hotfix so miners can use it?

**Comment by richmills3** [comment]
Fix is included in the latest 1.0.15.1 release

**Comment by gitzhou** [comment]
Thanks guys
