### ISSUE TITLE
How to run a BSV archive node

### ISSUE THREAD

**Issue by TonyS001** [bitcoin-sv/bitcoin-sv#297]
I want to run a BSV archive node, only using for synchronizing data, not mining. 
How much disk space do I need to prepare for mainnet and testnet? 
Is there any snapshot so I don't have to synchronize from genesis block, which would take a long time?

**Comment by mickmight** [comment]
Hi, please see https://node.bitcoinsv.io/sv-node/system-requirements for details on disk space requirements. 10-20GB for testnet, significantly more for mainnet. I'm not aware of any snapshot services right now, but I agree this would be a useful thing to have.

**Comment by TonyS001** [comment]
@mickmight Thanks for reply.
I try to run the node under the instruction in https://node.bitcoinsv.io/sv-node/installation/bitcoind , but the zipped release in https://download.bitcoinsv.io/bitcoinsv is very old version. How can I get the latest version of  executable files, since I don't want to compile the file by myself nor use the docker.

**Comment by mickmight** [comment]
Which OS are you using pls?

**Comment by TonyS001** [comment]
> Which OS are you using pls?

centos8
