### ISSUE TITLE
Assertion 'get() != pointer()' failed

### ISSUE THREAD

**Issue by nhojjohn** [bitcoin-sv/bitcoin-sv#298]
### Describe the issue
Since 1.0.15 if I compile with `-Wp,-D_GLIBCXX_ASSERTIONS` I get a runtime assertion failure
`/opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/unique_ptr.h:719: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp [], _Dp>::operator[](std::size_t) const [with _Tp = unsigned char; _Dp = std::default_delete<unsigned char []>; typename std::add_lvalue_reference<_Tp>::type = unsigned char&; std::size_t = long unsigned int]: Assertion 'get() != pointer()' failed.`

#### If so, please list the steps to reproduce below:
1. Compile with `-Wp,-D_GLIBCXX_ASSERTIONS` in CXXFLAGS (which what rpmbuild adds by default and seem like something you would want to enable?)

### What version of bitcoin-sv are you using?
This only started happening with 1.0.15 and 10.0.15.1 (10.0.14 works fine).

### Machine specs:
- OS: Centos 8 Stream

### Any extra information that might be useful in the debugging process.
```Jul 12 10:54:23 bsv bitcoind-sv[3302683]: 2023-07-12 08:54:23 [dnsseed] 22 addresses found from DNS seeds
Jul 12 10:54:23 bsv bitcoind-sv[3302683]: 2023-07-12 08:54:23 [dnsseed] dnsseed thread exit
Jul 12 10:54:23 bsv bitcoind-sv[3302683]: 2023-07-12 08:54:23 [worker10-N-HTTPServer] Leaving InitialBlockDownload (latching to false)
Jul 12 10:54:29 bsv bitcoind-sv[3302683]: /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/unique_ptr.h:719: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp [], _Dp>::operator[](std::size_t) const [with _Tp = unsigned char; _Dp = std::default_delete<unsigned char []>; typename std::add_lvalue_reference<_Tp>::type = unsigned char&; std::size_t = long unsigned int]: Assertion 'get() != pointer()' failed.
Jul 12 10:54:29 bsv systemd[1]: bitcoin-sv@1.service: Main process exited, code=killed, status=6/ABRT
```

**Comment by mickmight** [comment]
Hi @nhojjohn these are non-standard flags so not an urgent issue. I'm also not aware we have ever supported RPM builds. I'll feed this back to team as something they can consider in a future release. Are the docker images useful for you instead?

**Comment by nhojjohn** [comment]
I got it to run by removing `-Wp,-D_GLIBCXX_ASSERTIONS`

I thought I would highlight this though as as far as I know (and I'm not a C++ developer) GLIBCXX_ASSERTIONS are there to catch programming issues which might otherwise go undetected.  Hopefully this is benign and not causing some hidden data corruption or vulnerability.

**Comment by mickmight** [comment]
Many thanks.

**Comment by mickmight** [comment]
The team have had a look at this issue actually and are reviewing some possible code changes.

**Comment by mickmight** [comment]
@nhojjohn we have a commit to address this and it will be included in the next Node release. Keep an eye out for announcements from the BSV Association on dates. It will be announced very soon.

**Comment by nhojjohn** [comment]
I've built 1.0.16 with the rpmbuild default compile flags and seen no runtime assertion errors.

Thanks for fixing this.
