### ISSUE TITLE
How we will got bitcoin-sv ? 

### ISSUE THREAD

**Issue by luizfelipetx** [bitcoin-sv/bitcoin-sv#3]
Hello Guys, its is a question in really, but looking the code and block definitions i not see any copy of block-size or fork info. 
When you launch bitcoin how can I get coins?
Buying BCH and waiting for a fork? or will create a ICO ?

**Comment by Danconnolly** [comment]
Bitcoin SV is not a coin. Bitcoin SV is a software implementation.
