### ISSUE TITLE
questions on config parameters

### ISSUE THREAD

**Issue by TonyS001** [bitcoin-sv/bitcoin-sv#300]
I run a bsv mainnet node and have some questions on config parameters.

1. The log shows `maxconnections` was removed, so which parameters can config this now? I want to limit the bandwidth during synchronizing blocks.
2. I start the node with `txindex=1` and synchronizing data for a time, but find the disk has no enough space. Can I simply stop the node and change the config to `-prune`, then restart node?

**Comment by richmills3** [comment]
If I remember correctly, you can only limit the number of created outgoing connections using `maxoutboundconnections`. If you want to prevent incoming connections then you will have to specify a non-listening node using `listen=0`. I wouldn't have thought you'd be losing much bandwidth to incoming peers during IBD though.

Stopping the node, changing the `prune` setting and restarting should be fine.

**Comment by TonyS001** [comment]
@richmills3 Thanks for reply.
For the second question, I stop the node and change the prune setting as 400000, 400GB I suppose. But the disk usage is still grow and much over 400GB. I believe the setting doesn't work.  
I attach the config files, thanks for help!
[bitcoind.txt](https://github.com/bitcoin-sv/bitcoin-sv/files/12123164/bitcoind.txt)

**Comment by richmills3** [comment]
The prune value is a target, not a hard limit.

The node has to keep some number of blocks regardless of the pruning target to ensure it can cope with reorg's. This by default is 288 blocks. You can override this 288 block limit and set it to a lower value using `pruneminblockstokeep`, but I would recommend you only change this value while sync'ing the blockchain during IBD and remove the config change afterwards.

**Comment by danasabe90** [comment]
How are you downloading

**Comment by afomi** [comment]
@TonyS001 - [streamsendratelimit](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/init.cpp#L890C15-L890C34) can also limit bandwidth during IBD
