### ISSUE TITLE
Configuration File to Boot Production Node

### ISSUE THREAD

**Issue by hanzoyolo** [bitcoin-sv/bitcoin-sv#309]
### Configuration for booting a new BSV production node
Would like to request if there are any configuration files to assist with booting the node. Also if there's any recommendations to optimise node performances to accelerate sync to the latest block.

### What version of bitcoin-sv are you using?
1.0.16

### Machine specs:
- CPU: 16 Core
- RAM: 64GB
- Disk size: 32TB
- Disk Type (HD/SDD): SDD

**Comment by richmills3** [comment]
Hi, sorry for the late response.

Have you seen: [BSVA node installation docs](https://docs.bsvblockchain.org/network-topology/nodes/sv-node/installation/sv-node)? There is an example configuration file there.

As for speeding up initial block download, by far the most important thing is to have the best network connectivity to other full nodes you can. Once that's in place, you may find you can help things along a bit more by tweaking:

- **blockdownloadlowerwindow**: Has a default value of 10, try increasing it as high as you can upto a maximum value of 1000. The downside is you will use more disk space during IBD.
- **blockstallingmindownloadspeed** & **blockdownloadslowfetchtimeout**: By changing these you can reduce the amount of time the node will waste if it is waiting on a slow or unresponsive peer to send it blocks. The downside is you may waste some bandwidth fetching the same block from multiple peers.

**Comment by richmills3** [comment]
Closing
