### ISSUE TITLE
Dust threshold should be disabled by default

### ISSUE THREAD

**Issue by 1Hyena** [bitcoin-sv/bitcoin-sv#35]
Since SV was forked from ABC it unfortunately still includes some of the ABC's flaws. Namely, like ABC, SV enforces the obsolete dust threshold of 546 satoshis per TX output. Bitcoin Unlimited removed dust threshold several years ago and is in that sense a good example how to do it. I suggest the removal of this centrally planned rule from Bitcoin SV as well. At least, this rule should be disabled by default but perhaps optional via some configuration parameter.

1. Download and install Bitcoin SV.
2. Try to send 1 satoshi to someone.
3. See the TX getting rejected with the error message saying `dust`.

### Expected behaviour
By default, SV should allow any amount of bitcoins to be sent (including the zero amount).

### Actual behaviour
TX gets rejected by the very same node from which the TX originates.

**Comment by Danconnolly** [comment]
Thank you for your input, this is being considered for the future.
