### ISSUE TITLE
Use BIP135 for Next Update

### ISSUE THREAD

**Issue by ta32** [bitcoin-sv/bitcoin-sv#37]
Is SV going to commit to **using BIP135 to introduce changes to the protocol?**

https://github.com/bitcoin/bips/blob/master/bip-0135.mediawiki

BU supports this feature will SV?

As a potential investor I want to know

**Comment by Danconnolly** [comment]
No. I core tenet of the Bitcoin SV blockchain is that miners should vote for changes to the protocol with their hashrate by producing blocks.
