### ISSUE TITLE
How do I know how to generate an address in Bitcoin SV?

### ISSUE THREAD

**Issue by AhnSungHyeon** [bitcoin-sv/bitcoin-sv#38]
Bitcoin SV wants to generate a new address to receive coins.

I entered the following command.
./bitcoin-cli -datadir = / root / .bitcoin getnewaddress

But the result was not what I wanted.

error code: -32601
error message:
Method not found

Can you tell me why?

**Comment by tranchiendang** [comment]
How about the sync process of your block?
Possible try the command
./bitcoin-cli -conf=.bitcoin/bitcoin.conf getnewaddress

**Comment by AhnSungHyeon** [comment]
Thank you for answering my question.

I've entered it the way you told me.

./bitcoin-cli -conf=/root/.bitcoin.conf getnewaddress

However, the results are the same as before.

error code: -32601
error message:
Method not found

No problem with the other command.
./bitcoin-cli -conf=/root/.bitcoin.conf getblockcount
return value : 358391

./bitcoin-cli -datadir=/root/.bitcoin getblockcount
return value : 360851

Only the account is not created. 

Should I think of it as a bug?

The version of bitcoin sv I am using is as follows.

Bitcoin SV version v0.1.0.0-6e75abf

**Comment by tranchiendang** [comment]
Pls drop your bitcoin.conf as well as getblockchaininfo here, so that we can know more detail.

**Comment by AhnSungHyeon** [comment]
The bitcoin.conf file information I have is as follows.


##
## bitcoin.conf configuration file. Lines beginning with # are comments.
##
 
# Network-related settings:

# Run on the test network instead of the real bitcoin network.
#testnet=0

# Run a regression test network
#regtest=0

# Connect via a SOCKS5 proxy
#proxy=127.0.0.1:9050

# Bind to given address and always listen on it. Use [host]:port notation for IPv6
#bind=<addr>

# Bind to given address and whitelist peers connecting to it. Use [host]:port notation for IPv6
#whitebind=<addr>

##############################################################
##            Quick Primer on addnode vs connect            ##
##  Let's say for instance you use addnode=4.2.2.4          ##
##  addnode will connect you to and tell you about the      ##
##    nodes connected to 4.2.2.4.  In addition it will tell ##
##    the other nodes connected to it that you exist so     ##
##    they can connect to you.                              ##
##  connect will not do the above when you 'connect' to it. ##
##    It will *only* connect you to 4.2.2.4 and no one else.##
##                                                          ##
##  So if you're behind a firewall, or have other problems  ##
##  finding nodes, add some using 'addnode'.                ##
##                                                          ##
##  If you want to stay private, use 'connect' to only      ##
##  connect to "trusted" nodes.                             ##
##                                                          ##
##  If you run multiple nodes on a LAN, there's no need for ##
##  all of them to open lots of connections.  Instead       ##
##  'connect' them all to one node that is port forwarded   ##
##  and has lots of connections.                            ##
##       Thanks goes to [Noodle] on Freenode.               ##
##############################################################

# Use as many addnode= settings as you like to connect to specific peers
#addnode=69.164.218.197
#addnode=10.0.0.2:8333

# Alternatively use as many connect= settings as you like to connect ONLY to specific peers
#connect=69.164.218.197
#connect=10.0.0.1:8333

# Listening mode, enabled by default except when 'connect' is being used
listen=1

# Maximum number of inbound+outbound connections.
maxconnections=10

#
# JSON-RPC options (for controlling a running Bitcoin/bitcoind process)
#

#server=1 tells bitcoind to accept JSON-RPC commands
server=1

# Bind to given address to listen for JSON-RPC connections. Use [host]:port notation for IPv6.
# This option can be specified multiple times (default: bind to all interfaces)
#rpcbind=<addr>

# If no rpcpassword is set, rpc cookie auth is sought. The default `-rpccookiefile` name
# is .cookie and found in the `-datadir` being used for bitcoind. This option is typically used
# when the server and client are run as the same user.
#
# If not, you must set rpcuser and rpcpassword to secure the JSON-RPC api. The first
# method(DEPRECATED) is to set this pair for the server and client:
rpcuser=bitcoincash_sv_ash
rpcpassword=bitcoincash_sv_ash_password
#
# The second method `rpcauth` can be added to server startup argument. It is set at intialization time
# using the output from the script in share/rpcuser/rpcuser.py after providing a username:
#
# ./share/rpcuser/rpcuser.py alice
# String to be appended to bitcoin.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# On client-side, you add the normal user/password pair to send commands:
#rpcuser=alice
#rpcpassword=DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# You can even add multiple entries of these to the server conf file, and client can use any of them:
# rpcauth=bob:b2dd077cb54591a2f3139e69a897ac$4e71f08d48b4347cf8eff3815c0e25ae2e9a4340474079f55705f40574f4ec99

# How many seconds bitcoin will wait for a complete RPC HTTP request.
# after the HTTP connection is established. 
#rpcclienttimeout=30

# By default, only RPC connections from localhost are allowed.
# Specify as many rpcallowip= settings as you like to allow connections from other hosts,
# either as a single IPv4/IPv6 or with a subnet specification.

# NOTE: opening up the RPC port to hosts outside your local trusted network is NOT RECOMMENDED,
# because the rpcpassword is transmitted over the network unencrypted.

# server=1 is read by bitcoind to determine if RPC should be enabled 
#rpcallowip=10.1.1.34/255.255.255.0
#rpcallowip=1.2.3.4/24
#rpcallowip=2001:db8:85a3:0:0:8a2e:370:7334/96


rpcallowip=127.0.0.1

# Listen for RPC connections on this TCP port:
rpcport=8332

# You can use Bitcoin or bitcoind to send commands to Bitcoin/bitcoind
# running on another host using this option:
rpcconnect=127.0.0.1

# Transaction Fee Changes in 0.10.0

# Send transactions as zero-fee transactions if possible (default: 0)
sendfreetransactions=0

# Create transactions that have enough fees (or priority) so they are likely to begin confirmation within n blocks (default: 1).
# This setting is over-ridden by the -paytxfee option.
#txconfirmtarget=n

# Miscellaneous options

# Pre-generate this many public/private key pairs, so wallet backups will be valid for
# both prior transactions and several dozen future transactions.
keypool=100

# Pay an optional transaction fee every time you send bitcoins.  Transactions with fees
# are more likely than free transactions to be included in generated blocks, so may
# be validated sooner.
paytxfee=0.00

# User interface options

# Start Bitcoin minimized
#min=1

# Minimize to the system tray
#minimizetotray=1

**Comment by AhnSungHyeon** [comment]
I hope this information is helpful. 

When I entered the command below, I found a list of commands.

./bitcoin-cli help

The command list does not contain "getnewaddress".

Please help me.

The list below is an output list of "/bitcoin-cli help".

== Blockchain ==
getbestblockhash
getblock "blockhash" ( verbose )
getblockchaininfo
getblockcount
getblockhash height
getblockheader "hash" ( verbose )
getchaintips
getchaintxstats ( nblocks blockhash )
getdifficulty
getmempoolancestors txid (verbose)
getmempooldescendants txid (verbose)
getmempoolentry txid
getmempoolinfo
getrawmempool ( verbose )
gettxout "txid" n ( include_mempool )
gettxoutproof ["txid",...] ( blockhash )
gettxoutsetinfo
preciousblock "blockhash"
pruneblockchain
verifychain ( checklevel nblocks )
verifytxoutproof "proof"

== Control ==
getinfo
getmemoryinfo
help ( "command" )
stop
uptime

== Generating ==
generatetoaddress nblocks address (maxtries)

== Mining ==
getblocktemplate ( TemplateRequest )
getmininginfo
getnetworkhashps ( nblocks height )
prioritisetransaction <txid> <priority delta> <fee delta>
submitblock "hexdata" ( "jsonparametersobject" )

== Network ==
addnode "node" "add|remove|onetry"
clearbanned
disconnectnode "[address]" [nodeid]
getaddednodeinfo ( "node" )
getconnectioncount
getexcessiveblock
getnettotals
getnetworkinfo
getpeerinfo
listbanned
ping
setban "subnet" "add|remove" (bantime) (absolute)
setexcessiveblock blockSize
setnetworkactive true|false

== Rawtransactions ==
createrawtransaction [{"txid":"id","vout":n},...] {"address":amount,"data":"hex",...} ( locktime )
decoderawtransaction "hexstring"
decodescript "hexstring"
getrawtransaction "txid" ( verbose )
sendrawtransaction "hexstring" ( allowhighfees )
signrawtransaction "hexstring" ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] ["privatekey1",...] sighashtype )

== Util ==
createmultisig nrequired ["key",...]
estimatefee nblocks
signmessagewithprivkey "privkey" "message"
validateaddress "address"
verifymessage "address" "signature" "message"

**Comment by Polve** [comment]
I'm using regtest and when I ask for a new address I get the BCH address format instead of the bitcoin one:

> bitcoin-cli getnewaddress
> bchreg:qqxuk94ngflpl8rk9nhpcqys6tesu5udhcwu3sgnfr

**Comment by Danconnolly** [comment]
Set usecashaddr=0 in the bitcoin.conf.

**Comment by Polve** [comment]
Ok, but that should be the default since the bitcoin cash address is not compatible with SV network, right?

**Comment by AhnSungHyeon** [comment]
Adding "cashaddr=0" to the bitcoin.conf file still results in the same error.

**Comment by AhnSungHyeon** [comment]
Adding "usecashaddr=0" to the bitcoin.conf file still results in the same error.

error code: -32601
error message:
Method not found

**Comment by AhnSungHyeon** [comment]
Thank you for your answers. Let's try again.

**Comment by AhnSungHyeon** [comment]
I think the way I installed it before was wrong.

Previously, the following command was entered:
./autogen.sh
./configure --without-miniupnpc --disable-wallet
Make check

When performing a new reinstallation, the command was entered as follows:
./autogen.sh
./configure
Make
make install

After installation 

I entered the command to generate the address again and it was created in the following format.

bitcoincash:qzun8t2gepczp05np7c77e2g8g...

The address format appears to be the same as Bitcoincash (ABC). 

Is this generated normally?

**Comment by Danconnolly** [comment]
@Polve technically speaking, the address format is just a way of showing information. The CashAddress format will work on BSV, if the software accepts it. Most of the BSV compatible software seems to be moving away from the CashAddress convention.

We are changing the default in the next release to not use the cashaddr format.
