### ISSUE TITLE
how to get bsv testnet coins

### ISSUE THREAD

**Issue by purplecity** [bitcoin-sv/bitcoin-sv#39]
can't find any bsv testnet faucets.    bch testnet faucets(https://coinfaucet.eu/en/bch-testnet/) does't work

**Comment by jsitowski** [comment]
Why not mine your own? :smile_cat:

**Comment by Danconnolly** [comment]
A faucet is in progress, meanwhile post a testnet address here.

**Comment by purplecity** [comment]
@Danconnolly  see glimmers of hope!  could u  get 15 BSV testnet coins   😁  addr:       mhzuR9LJuJvwq9hfYLpgtvxuwyAMvNsPwG

**Comment by dasterdly** [comment]
That’s 1200 $ ! Exactly what are you testing? Remember we can test a lot of your heave stuff throught narrowing down variables with math and statistic theory and check confirm and run tests on your own desktop.

**Comment by purplecity** [comment]
@dasterdly  ok  5 BSV .  I wan't use this one addr as faucet to our team test bsv.

**Comment by purplecity** [comment]
@Danconnolly  I am wrong. could give me 5 BSV testnetcoins.... need test.  boss let me to complete bsv walelt for our exchange. could u tell me when u had sended testnet coins. thanks

**Comment by dasterdly** [comment]
Sorry I’m not with Nchain (yet) :) did only want to point out that it is not always you need a physical test net! When a virtual one is possible!

**Comment by snoopaku** [comment]
Hi! Can you send please any amount to:
**qqldlzl44lft785q4a9js25frhfe3q7wecjmlster5**

Just need to test deposit and withdrawal for our exchange.
And you can also provide your address, I'll get your coins back to you after testing.

Thanks in advance!

**Comment by dfoderick** [comment]
> Hi! Can you send please any amount to:
> **qqldlzl44lft785q4a9js25frhfe3q7wecjmlster5**
> 
> Just need to test deposit and withdrawal for our exchange.
> And you can also provide your address, I'll get your coins back to you after testing.
> 
> Thanks in advance!

@snoopaku 
See if this transaction gets to you for .1 tBSV. I am testing my faucet.

Sending request...
Success: tBSV are on their way!
TXID: 1c34a64612eb28cac081567bcba91ebf6e2ed77ea3b57f3e9ec35250a3592b29

https://testnet.bitcoincloud.net/tx/1c34a64612eb28cac081567bcba91ebf6e2ed77ea3b57f3e9ec35250a3592b29

**Comment by dfoderick** [comment]
> @Danconnolly see glimmers of hope! could u get 15 BSV testnet coins   addr: mhzuR9LJuJvwq9hfYLpgtvxuwyAMvNsPwG

Sending request...
Success: tBSV are on their way!
TXID: 99e2ea733f6d3ca8873d40723d7694035da8ca55cc77283d18bfbcdd4596c926

https://testnet.bitcoincloud.net/tx/99e2ea733f6d3ca8873d40723d7694035da8ca55cc77283d18bfbcdd4596c926

**Comment by Danconnolly** [comment]
Thank you @dfoderick 

Also sent some.

**Comment by snoopaku** [comment]
> > Hi! Can you send please any amount to:
> > **qqldlzl44lft785q4a9js25frhfe3q7wecjmlster5**
> > Just need to test deposit and withdrawal for our exchange.
> > And you can also provide your address, I'll get your coins back to you after testing.
> > Thanks in advance!
> 
> @snoopaku
> See if this transaction gets to you for .1 tBSV. I am testing my faucet.
> 
> Sending request...
> Success: tBSV are on their way!
> TXID: 1c34a64612eb28cac081567bcba91ebf6e2ed77ea3b57f3e9ec35250a3592b29
> 
> https://testnet.bitcoincloud.net/tx/1c34a64612eb28cac081567bcba91ebf6e2ed77ea3b57f3e9ec35250a3592b29

Got them, thank you! Do you need them back?

**Comment by dfoderick** [comment]
> Got them, thank you!
> Can you provide your address also please? So I could test a withdrawal too.

You can send back a small amount to mgczdj3eMXFH1h8Q8YSW4aMXNLJX2YZWo7
if you want to test.

**Comment by keviny** [comment]
You mean this?
https://www.reddit.com/r/bitcoincashSV/comments/aaqe72/bsv_testnet_faucet/

**Comment by tranchiendang** [comment]
@dfoderick can you give me any faucet at address bchtest:qpsarlfqrgps0w7qypam75pxagw2gltfegpq2m6ews
I am doing integration.
Thank you very much

**Comment by dfoderick** [comment]
@tranchiendang 
Try one of the online faucets to see if they work for you.
https://tools.fullcyclemining.com/
https://bitcoincloud.net/faucet/

**Comment by tranchiendang** [comment]
@dfoderick yep, thank you very much, it works.

**Comment by rauldelcorte** [comment]
Hi, there! The Bitcoin SV Testnet Faucet does not works
https://bitcoincloud.net/faucet/
Every time I enter a Bitcoin SV address, I always get the same answer: "The address you've entered is invalid"

**Comment by Danconnolly** [comment]
It worked for me just now. What is the address you are entering?

**Comment by Danconnolly** [comment]
No answer, closing.

**Comment by shagorbleed** [comment]
need some testnet coins for testing something interesting.
want to deploy something.


mqjq7CaU59LvJi5p14ZLEieyzGqtbjQKM3


can anyone help me with some coins?

**Comment by rt121212121** [comment]
There are faucets. Look at the handy page the Scrypt project provides:
https://scrypt.io/#faucet
