### ISSUE TITLE
Cointype for BSV?

### ISSUE THREAD

**Issue by yoyoyousei** [bitcoin-sv/bitcoin-sv#4]
To create HD wallet([BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)) for BSV, I think we need to define cointype for BSV.

To define cointype, decide cointype number for BSV and reflect to slip-0044. https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by bitcoinsvsupport** [comment]
Hi

Bitcoin SV is not a new coin; it is a software implementation of Bitcoin Cash. If you need the cointype for any reason you would specify Bitcoin Cash (index 145 from that list).

**Comment by yoyoyousei** [comment]
I think it is currently, yes.
But does BSV become new coin in the next 2018/11 fork, new blocks which created BSV Nodes might have over 128MB, and other BCH Nodes(ABC and Unlimited) cannot handle the block.
So I think the network becomes different between BSV and others. isn't it?

**Comment by Danconnolly** [comment]
The Bitcoin SV software will not produce a new coin.

**Comment by yoyoyousei** [comment]
I see.
Do you have any ideas to handle those implementations of BitcoinCash in HD wallet?

**Comment by yoyoyousei** [comment]
The result of the longest chain seems to differ between the implementations. 
Because blocks which have transactions containg Satoshi Opcodes are rejected on other implementation(ABC and Unlimited).

**Comment by Danconnolly** [comment]
The longest chain is the chain which has the most proof of work. This is the chain that client software will select.

**Comment by WhyBitcoinCash** [comment]
BitcoinSV will always be bitcoin.
