### ISSUE TITLE
BSV testnet coins

### ISSUE THREAD

**Issue by purplecity** [bitcoin-sv/bitcoin-sv#40]
Dear @Danconnolly: 
I represent Bithumb.global exchange（Coming Soon）and responsible for  accessing BSV to our exchange .  but have't testnet coins to test. is there any idea can help me to get testnet coins?  I have emailed to support@bitcoinsv.io and issues #39 but  no reply.     I think a lot of developers are concerned about testnet faucets as well。

**Comment by Polve** [comment]
I'm interested in testnet coins as well

**Comment by purplecity** [comment]
<img width="1132" alt="wechatimg8" src="https://user-images.githubusercontent.com/38914615/50332682-dff48a00-053d-11e9-87a3-6d259163c830.png">


here is config file

**Comment by purplecity** [comment]
<img width="787" alt="wechatimg8" src="https://user-images.githubusercontent.com/38914615/50332749-13cfaf80-053e-11e9-8686-e37fe945d5fa.png">

config file
