### ISSUE TITLE
why getblock  don't return detail information

### ISSUE THREAD

**Issue by purplecity** [bitcoin-sv/bitcoin-sv#45]
in btc or bchabc.  API getblock

getblock "blockhash" ( verbosity ) 

If verbosity is 0, returns a string that is serialized, hex-encoded data for block 'hash'.
If verbosity is 1, returns an Object with information about block <hash>.
If verbosity is 2, returns an Object with information about block <hash> and information about each transaction. 

but  at bsv getblock. verbosity is true or false  and have not  information about each transaction. 

This causes the getrawtransaction interface to be invoked for each txid。 if  a block has 100 000 txs.  it will  take a lot of time

**Comment by vittoj** [comment]
Indeed, but imagine a 128m block

**Comment by Danconnolly** [comment]
This was implemented in version 0.2.1. Note that it may return a very large of information.
