### ISSUE TITLE
testnet - safe mode

### ISSUE THREAD

**Issue by tranchiendang** [bitcoin-sv/bitcoin-sv#46]
I am practicing bitcoin sv in testnet mode, but when i connect to make rpc call, encounter this problem, i try to add peer nodes from https://github.com/bitcoin-sv/bitcoin-sv/issues, but no affect.

> Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade

**Comment by Danconnolly** [comment]
This message is displayed because your node has seen the BCH testnet chain. Your node is warning you that an invalid chain exists. At the present time, the message can be safely ignored.

**Comment by tranchiendang** [comment]
Ya, i know, but in the same time, it prevent me to call rpc or any commands such as bitcoin-cli listaccounts

**Comment by tranchiendang** [comment]
@Danconnolly I try more options such as setting -disablesafemode but it's affect.
Still can't call json rpc.

**Comment by tranchiendang** [comment]
Now, it happens in mainnet too. It throws

> warning='11 of last 100 blocks have unexpected version'

**Comment by Danconnolly** [comment]
That warning looks like it comes from the log file. What is the error message from bitcoin-cli?

**Comment by dfoderick** [comment]
> Now, it happens in mainnet too. It throws
> 
> > warning='11 of last 100 blocks have unexpected version'

That just means miners are mining with AsicBoost. Overt AsicBoost is mined with version number as part of the nonce. For example, these two blocks were mined with asicboost.
![image](https://user-images.githubusercontent.com/625411/50948762-899dab80-1458-11e9-87a1-34f611b56325.png)

**Comment by tranchiendang** [comment]
@Danconnolly @dfoderick Thank you for your kind supporting , right now, after starting bitcoind with option -disablesafemode, i can submit json rpc call.
