### ISSUE TITLE
Node creation in windows

### ISSUE THREAD

**Issue by cryptodeveloperin** [bitcoin-sv/bitcoin-sv#48]
I have downloaded bitcoin ABC node from https://www.bitcoincash.org/nodes.html for windows machine.

I have tried to search node for Bitcoin SV but could not found. Please can you provide me the proper instruction to generate node on windows machine.  Means i need bitcoin-cli.exe and bitcoind.exe for bitcoin sv. so i can make full node on my windows server.

**Comment by mboyd1** [comment]
have you tried following the linux build instructions from within Windows Subsystem for Linux?

**Comment by cryptodeveloperin** [comment]
I have tried with Linux but not getting results. So can you provide steps for it.

**Comment by tanderbold** [comment]
Windows users wait a core wallet

**Comment by tanderbold** [comment]
All coins have it

**Comment by StanWarford** [comment]
Yes, and MacOS users want a MacOS build. I use full core desktop wallets for all my alt coins and am waiting for BSV to provide one. Windows and MacOS builds are overdue.

**Comment by Danconnolly** [comment]
We don't supply binaries for MacOs or Windows but we do support changes to enable compilation on these platforms.

If you are having issues with compilation on Windows, please raise a new ticket.

Closing due to age.
