### ISSUE TITLE
why getrawtransaction don't return details of txid.

### ISSUE THREAD

**Issue by antechdemo** [bitcoin-sv/bitcoin-sv#49]
-- Request body --
{"jsonrpc":"1.0","method":"getrawtransaction","params":["b966fc66a876de8a524b45cc8b35d1a160e5eba8025ccb18518440bc926625d5",true]}

-- Response body --
{"result":null,"error":{"code":-5,"message":"No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions."},"id":null}

**Comment by roccomuso** [comment]
You need to run your coin client and sync your chain with the flag `-txindex`

**Comment by antechdemo** [comment]
Hey roccomuso,
Thanx for the reply.

But now its given me a warning ,We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade

{
  "version": 100010000,
  "protocolversion": 70015,
  "walletversion": 160300,
  "balance": 1.11000000,
  "blocks": 1280740,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 3.378336308875358,
  "testnet": true,
  "keypoololdest": 1546853452,
  "keypoolsize": 1999,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.",
  "maxblocksize": 128000000,
  "maxminedblocksize": 32000000
}

**Comment by Danconnolly** [comment]
This is because the node sees the ABC chain. This message can be ignored.

**Comment by Danconnolly** [comment]
Answered. Closed.
