### ISSUE TITLE
How bitcoin SV will update consensus rules after November 

### ISSUE THREAD

**Issue by ta32** [bitcoin-sv/bitcoin-sv#5]
For: https://cash.coin.dance/poli

Describe the issue
Can the community get a statement from BitcoinSV on whether future protocol changes will be broken down into independent changes and activated using BIP135.

Or is bitcoinSV committed to bi-annual hardforks?
I am personal neutral to both approaches

We also need a public statement of your preference of how the road map will be deployed ( Bi-Annual updates or BIP-135) for coin-dance. This is for the coin-dance policy chart.

I didn't know how to ask the whole team in a publicly verifiable way - maybe you can updated your website/roadmap

**Comment by Danconnolly** [comment]
We are not committed to bi-annual upgrades. We will discuss plans for consensus rules changes with miners, development groups, and the community.

**Comment by ta32** [comment]
@Danconnolly will SV use BIP135 ( block signaling ) before activating new rules. I need a yes or no answer for coindance please.
