### ISSUE TITLE
broadcast larger tx hex

### ISSUE THREAD

**Issue by Klar** [bitcoin-sv/bitcoin-sv#51]
### Describe the issue
Trying to broadcast a larger TX Hex but getting an error:

error code: -22
error message:
TX decode failed

### Can you reliably reproduce the issue?
Yes, able to reproduce, it is working with less Data.

### Expected behaviour
Broadcasting

### Actual behaviour
error code: -22
error message:
TX decode failed

I have set datacarriersize=100000 and restarted my node. Not sure if any settings are missing.

**Comment by Danconnolly** [comment]
It looks like you have an error in your tx. `datacarriersize=100000` is sufficient to enable larger OP_RETURN payloads.

**Comment by Klar** [comment]
working now, my fault. Thanks for your help.
