### ISSUE TITLE
BitcoinSV Wallet

### ISSUE THREAD

**Issue by slickster33** [bitcoin-sv/bitcoin-sv#52]
This issue tracker is only for technical issues related to bitcoin-sv.

For reporting security issues, please contact people privately.

### Describe the issue
I have a bitcoisv wallet the name of it is Wallet BitcoinSV App for android i have coins in it i also had winnings from phun.io transfered to it . I have contacted the place where the wallet  come from and it bitcoinsv.io answered back saying my wallet is a bitcon cash wallet not a bitcoin Sv wallet the poblem is it came from bitcoinsv.io i need my coins my wallet address is 1AnDnvFJ5rUVzrxtu2RudkW67QU3NbgUBd can someone help me get my funds out of this wallet

**Comment by alexxsounds** [comment]
Bitcoin is an **IMMUTABLE** ledger

**Comment by screeni** [comment]
you have sent BCH to your BSV WALLET ?

**Comment by Danconnolly** [comment]
I'm glad to see that you have been able to retrieve your funds.

**Comment by slickster33** [comment]
Danconnolly i haventr recieved them and screeni if you read my post good phun.io made the deposit and they only deal in sv if anyone can help let me know please
