### ISSUE TITLE
node always log error

### ISSUE THREAD

**Issue by purplecity** [bitcoin-sv/bitcoin-sv#55]
always log:  block 00000000000002773f8970352e4a3368a1ce6ef91eb606b64389b36fdbf1bd56  is invalid .

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/38914615/52847299-c12e0080-3146-11e9-8315-601d9ee385bb.png">

at time now RPC work well but I don't know why have this error log?

**Comment by purplecity** [comment]
ENV:   bsv testnet

**Comment by mboyd1** [comment]
that is block [1286727](https://testnet.bitcoincloud.net/block-height/1267997). It was mined November 15 2018, the day of the BCH/BSV hard fork.  The errors are from peers running bitcoin-abc on the bch testnet chain being unable to follow the bsv testnet chain.  It's safe to ignore them.

`./bitcoin-cli -rpcport=18332 getblock 00000000000002773f8970352e4a3368a1ce6ef91eb606b64389b36fdbf1bd56 6.2s
{
  "hash": "00000000000002773f8970352e4a3368a1ce6ef91eb606b64389b36fdbf1bd56",
  "confirmations": -1,
  "size": 5666,
  "height": 1267997,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "7ff03217143ee9bc29e6cd69713ed87164d058fec50974cdc9e5e9907fbbc427",
  "tx": [
    "f2f43274168b89abcac4183e32100872b97ca3f9e2280e2cb319a98df86293a8",
    "0165281820c10801dedc666d51e4e9a22da0da1e452b4d8ce671d0a2d7c0bfa7",
    "0dac6660b560fd01e9d4b1a56e3270ae14eed57d97f44fbce4b165b9fcfcefbb",
    "1de2d5cb827c0105d09740bff8bd011521c17c65a21010c5a76be4244919a0de",
    "1f64f01f2dc4e652722c8b7a7cf8a6695a23288af80f085236109afaede8b021",
    "449bdb70a033b92a8dd16939af6d3a620a760fc97db575ef871da428df569042",
    "4dc3f74c0e1c4857b19f7a59e036287b46e8b41afc0fc71a9b47dc8fe0fe6e71",
    "5b51b0ea817e5ae07fa53122c9ed4d13779fe8ed989144633eca93b1c0aaaeeb",
    "721c9fa19dc7f480ae02480f0a94e3b8b98fd35c24f835780be05d90795eb1ba",
    "830cbb1ebe3ef9d48b30b948c6a641a6c2b2559fd8eb177870f4d08923f03772",
    "8dee63bc1b591f57194b8f23eda0d924ef6cf6917c703bb0407dfa5654a8572f",
    "919c8ed83cf30dc61eeec501e3fa1f6a633bd8135dc6f34232ae93a7d170802f",
    "9ef57e7714570b1fd6c7ac0f82cc0a3e45eae7acf88c9d1f28cc7be0ab2b1aae",
    "a66fc1311f797f903b01f29ea957de9a817516930a2f650852ce7b9fec7fbad4",
    "bc1e399b4092a0927f0de7f4dd17f5439385b83666e36d246f46083ac3089ece",
    "c6feb07b79b0f6c546386c3405148b4a29847be877fa7030d6bccd9263c12310",
    "c73308d6274ccb2c3174444761e4a67a3ef96213a35f32c4745760016182dae9",
    "cf3cea802b8ae2623d3f719c006a71ac06f5b517c4e04ce7d0811993df80629b",
    "eac292032d1be6ca0feaa6ac1b57d19e03152aab12122eafbc974ec4e6a11c35"
  ],
  "time": 1542302023,
  "mediantime": 1542300144,
  "nonce": 1836634712,
  "bits": "1a07242b",
  "difficulty": 2349292.752862646,
  "chainwork": "00000000000000000000000000000000000000000000003f3d08c568b1b987e3",
  "previousblockhash": "00000000000001fae0095cd4bea16f1ce8ab63f3f660a03c6d8171485f484b24"
}`

**Comment by purplecity** [comment]
@mboyd1 but my node neighbor node mostly running bchabc. so how to find only running bsv node?

**Comment by Danconnolly** [comment]
The node will ignore this invalid block automatically.

Old issue, closing.
