### ISSUE TITLE
how to estimate fee?

### ISSUE THREAD

**Issue by purplecity** [bitcoin-sv/bitcoin-sv#58]
if I construct a transaction. how to estimate transaction size and fee?  don't use RPC API estimatefee

**Comment by purplecity** [comment]
at bitcoin . estimate transaction size is : in*180 + out*34 + 10.  if bsv follow this?  but how many transaction fee per kB?

**Comment by Danconnolly** [comment]
That is a method to estimate a normal transaction. Try 1 satoshi per kb.

**Comment by bajian** [comment]
I also want to know how to evaluate the fee rate now. Since the `estimatemartbee` and`estimatefee` have both been removed.
