### ISSUE TITLE
never confirm even high fee ...

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin-sv/bitcoin-sv#59]
I send a low fee transaction , but I try to push it to chain , so I try to send many transactions ...

fee : 0.00000192 (x1 recommend fee ... from my BCHSV node ... )
https://bchsvexplorer.com/tx/65af116e6dfb68467e13988c425a280c9b285b77b3bdeffd2a0b4fd6006f2d61

fee : 0.00000576 (x3)
https://bchsvexplorer.com/tx/c93d7176e7e512c41ac4a09dd9db1e150c2ac5d573d9290c60f9fa1f61786b41

fee : 0.0000384 (x20)
https://bchsvexplorer.com/tx/c1fb1ce7b39adea8867cac86a928159387b7f234f8e0e6cceae50ccb0f0ea969

fee : 0.00192 (x1000)
https://bchsvexplorer.com/tx/c85d65e1343a7e4e593e8ad41c7b682b9499d573a4ec6dad1150930e87653485

but it look like never confirm ... can I do something to help it confirm , or just the miner choice ? , if I use double spent it ... I think it will be drop from memory pool ...

**Comment by Danconnolly** [comment]
Do you have the actual transactions? Which wallet were you using?

**Comment by JokerCatz** [comment]
this issue can be close ....... I use double spent to resend it and success ...... the low fee will not broadcast to all network mempool , it will be drop by another peers , so I try to build a another empty node and resend successed
