### ISSUE TITLE
Two different archives containing the source code for release 0.1.0

### ISSUE THREAD

**Issue by c0deright** [bitcoin-sv/bitcoin-sv#6]
Please see https://github.com/bitcoin-sv/bitcoin-sv/releases/tag/v0.1.0

There are two archives linked which should contain the same files:

https://github.com/bitcoin-sv/bitcoin-sv/releases/download/v0.1.0/bitcoin-sv-0.1.0.tar.gz
https://github.com/bitcoin-sv/bitcoin-sv/archive/v0.1.0.tar.gz

Both archives differ in size and content. Please make up your mind as to which should be linked on the release page. Two different archives only leads to confusion.

**Comment by Danconnolly** [comment]
The second link you gave, with URL https://github.com/bitcoin-sv/bitcoin-sv/archive/v0.1.0.tar.gz, is automatically provided by GitHub. Please ignore this link.

We will be moving to another distribution mechanism in the future which will remove this "feature".
