### ISSUE TITLE
how to connect to the bsv node?

### ISSUE THREAD

**Issue by zhfnjust** [bitcoin-sv/bitcoin-sv#60]
I connect to the bsv node , but after i send my version message to the other node, i got nothing, then the socket close.
this my versoin message raw byte 

7f1101000100000000000000eeae9f5c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000077d535920e8168f0122f6d796c616e642d6273763a302e302e312f0000000001

**Comment by shadders** [comment]
Can you decide the version message and post it here? What client are
you using?

**Comment by zhfnjust** [comment]
i modify this library to make it can connect to the sv node [https://github.com/bitpay/bitcore/tree/master/packages/bitcore-p2p-cash](url)

**Comment by Danconnolly** [comment]
Is this working for you now?

**Comment by Danconnolly** [comment]
No response, closing.
