### ISSUE TITLE
Nodes will not relay large OP_RETURN transactions to other nodes unless 3 other parameters are increased in addition to datacarriersize

### ISSUE THREAD

**Issue by attilaaf** [bitcoin-sv/bitcoin-sv#62]
### Describe the issue

Users are unable to send large OP_RETURN transactions. Nodes will not relay large OP_RETURN transactions to other nodes.

The user will need to wait until new blocks are found and resubmit their transactions at a later time.

It is not the case that the only parameter that needs to be set is datacarriersize to fully support large OP_RETURNs, there are actually 3 other parameters that should be configured.

You can reproduce this issue and see the problem yourself by producing many transactions with > 90KB+ OP_RETURN transactions where you chain together many unconfirmed large OP_RETURN utxos.

Once it reaches greater than 101 KB, then your transaction will not propagate in the network or return an error outright.
 
https://www.yours.org/content/important-and-overlooked-settings-to-fully-enable-large-op_returns-for-760ac1d4af95

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:
1.  Send a transaction with OP_RETURN size 90KB
2. Send another transaction (chained with the previous one) of an OP_RETURN size 90kb. 
3. The 2nd transaction is reject and/or not propagated to other nodes

### Expected behaviour

The user should be able to support chaining up to 24 unconfirmed transactions, with each of them carrying up to 100KB OP_RETURNs,

### Actual behaviour

The user is unable to exceed a total of 101KB OP_RETURN size for the sum of all the chained transactions in the mempool.

### What version of bitcoin-sv are you using?

v0.1.1 - https://github.com/bitcoin-sv/bitcoin-sv/tree/v0.1.1

### Any extra information that might be useful in the debugging process.

https://www.yours.org/content/important-and-overlooked-settings-to-fully-enable-large-op_returns-for-760ac1d4af95

**Comment by Danconnolly** [comment]
Did you set limitancestorsize and limitdescendantsize as the article suggested?

**Comment by attilaaf** [comment]
Yes, I wrote the Yours.org article above to help people.

I'm reporting this as a "bug" because many people and businesses misconfigured  their nodes thinking they only had to set the datacarriersize

**Comment by Danconnolly** [comment]
OK, thank you for this report. The next version of Bitcoin SV will have these configurations set by default.
