### ISSUE TITLE
Rest API /rest/block/BLOCK-HASH.json not work when response greater than 2 MB

### ISSUE THREAD

**Issue by TouchYou** [bitcoin-sv/bitcoin-sv#63]
It is not work When I use this API and response body greater than 2M. The response body's json is not right.

I saw the doc REST-interface.md writes
> The HTTP request and response are both handled entirely in-memory, thus making maximum memory usage at least 2.66MB (1 MB max block, plus hex encoding) per request.

Is that means this API can't handle block size greater than 1 MB?

If that's true, how shold I get block details?

**Comment by backcopy** [comment]
Process the raw block .blk files yourself and store as per your requirements; you can use a dedicated database. 

Leaving some notes below:

https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/httpserver.cpp
https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/httpserver.cpp#L603
https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/httpserver.cpp#L424
https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/univalue/lib/univalue_write.cpp#L29

**Comment by Danconnolly** [comment]
We'll look into this.

**Comment by Danconnolly** [comment]
This works in v0.2.1.

`curl localhost:8332/rest/block/00000000000000000254d7c2710bce68546614b30d21a765c509bf1d38f28673.json`

Note that the receiving process needs to keep up. Using curl with output to stdout over SSH may not be able to keep up, redirecting to a file will help.

Updates that will appear soon: documentation updated, tests for large blocks added.
