### ISSUE TITLE
License issue - non compliance with originating license

### ISSUE THREAD

**Issue by stevescot** [bitcoin-sv/bitcoin-sv#68]
### Describe the issue
MIT license which predates this code has the following statement: 
"including without limitation the rights to use,"
yet 
https://github.com/bitcoin-sv/bitcoin-sv/blob/master/LICENSE

has restrictions on use - suggest these are removed and originating license is used without change.
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/COPYING 

#### If so, please list the steps to reproduce below:
1. Read licenses of previous versions before BSV branch

### Expected behaviour
License should stand

### Actual behaviour
License has been modified.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-sv are you using?
Not Using BSV

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `bitcoind.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Danconnolly** [comment]
The MIT license continues to apply to the source code that is in version 0.1.1. The code in version 0.2.0 now uses the Open BSV license.

**Comment by stevescot** [comment]
unless it's all been rewritten then the license still stands.

**Comment by Danconnolly** [comment]
I received this by e-mail: unless it's all been rewritten then the license still stands.

As you have pointed out, the MIT license states "including without limitation the rights to use,", but the full sentence is "including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell". We have
