### ISSUE TITLE
Is 0.2.0 stable? How about a changelog?

### ISSUE THREAD

**Issue by c0deright** [bitcoin-sv/bitcoin-sv#76]
According to https://github.com/bitcoin-sv/bitcoin-sv/releases there was a release version 0.2.0 tagged but it's lacking a Changelog.

https://download.bitcoinsv.io/bitcoinsv/ has 0.2.0 for download.

Is 0.2.0 considered stable? How about a changelog?

**Comment by Pheromon** [comment]
Changelog?

They forked ABC and even forget to change the address prefix, so they use the "bitcoincash:" for their address too :-D

SV is joke run by clowns, and I find amusing to see that there are people still falling for scams: it means I'll be able to make more money with other senseless forks.

**Comment by c0deright** [comment]
Unfortunately, some people/exchanges have to support BSV because of it's userbase ;)

**Comment by Pheromon** [comment]
At least I hope they are well paid to do such a dirty job! ;-)

**Comment by breign** [comment]
Found this for you

Changes of note include:

- new mining API
- support for Quasar upgrade
- change of the license to Open BSV license
- default maximum OP_RETURN size to 100kb
- default transaction relay delay to 150ms
- upgrade to C++17
- removal of support for 32-bit and ARM architectures
- cleanup of defunct code – magnetic upgrade activation, ABC forced obsolescence

**Comment by Danconnolly** [comment]
The changes are clearly identified in the [release notes](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/release-notes.md).
