### ISSUE TITLE
bitcoin-cli dumprawmempool true fails if mempool > 1000 transactions.

### ISSUE THREAD

**Issue by jhoenicke** [bitcoin-sv/bitcoin-sv#77]
When mempool has more than ~1024 transactions, `bitcoin-cli dumprawmempool true` fails with 

     JSON NESTING DEPTH exceed 2049 > 2048

This is caused by this patch: https://github.com/bitcoin-sv/bitcoin-sv/commit/4ae738a6db69bbd4a965f36665ccd212857293f3#diff-e7850961097d802315e979efcd41558f. Indeed the `ObjArrCounter` is never decremented when parentheses are closed.

**Comment by Danconnolly** [comment]
Thank you. This is fixed in the next release which is due soon.
