### ISSUE TITLE
Incentivize Chain Compression

### ISSUE THREAD

**Issue by xloem** [bitcoin-sv/bitcoin-sv#79]
I propose an improvement where:
A. Rather than publishing a block, a miner can publish a script that generates the block correctly.
B. Mining reward is given to incentivize the creation of the smallest possible script.

This has probably been thought of before, but it seems obvious to me.  Any thoughts?

**Comment by Danconnolly** [comment]
What do you mean by point B?

**Comment by xloem** [comment]
The goal is to get block mining work to make the blockchain smaller without losing any data.

Blocks are picked based on either existing proof of work _or_ increased compression of their content.  So B lets you roughly get free proof of work if you can correctly compress blocks more, with a script you include in the new block.

Thinking more about it, I guess you'd want the script to compress the previous block(s), but not the new one, or people would use fake transactions to game it.

If your script makes the whole old blockchain smaller than anybody else's without losing data, you get rewarded by either the block itself, or bonus proof of work, or whatnot.

Is the idea clear at all?

**Comment by Danconnolly** [comment]
While the idea of being able to produce a script that produces the block is interesting, it sounds like you're also talking about changing some of the fundamental mechanisms on how Bitcoin works ("Blocks are picked on either existing proof of work or increased compression of their content").

There's a line somewhere, between efficiently communicating a block and changing the fundamental properties of Bitcoin. 

I'd encourage you to further explore this idea, but I think its a bit out of scope of this forum.

**Comment by xloem** [comment]
Thanks, Danconnolly.  I hope somebody keeps the idea on the backburner somewhere for solving chain growth.  I may not be able to pursue it on my own.

**Comment by Danconnolly** [comment]
Thanks for the ideas. Closing.
