### ISSUE TITLE
Zmq Questions about Block Rollback

### ISSUE THREAD

**Issue by Rui2guo** [bitcoin-sv/bitcoin-sv#82]
### Describe the issue

hello,
I'd like to ask ZMQ whether block monitoring for bitcoin will process rollback blocks into queues
In Jul-10-2019 11:24:15 Block rollback occurred in BSV network

But I found that ZMQ hashblock listener did not listen for the correct hash of the rollback block.
Original Chain： 590482 -->590483 --->590484

Normal occurrence block rollback chain:590482 -->590483(r) --->590484(r)-->590485--->(......)
ZMQ is not acquired the 590483(r) 590484(r) blockhash ,but the blockhash of 590485 is acquired. the old 590483 590484 is acquired

**Comment by Danconnolly** [comment]
Thank you, we'll look into this.

**Comment by CassClark** [comment]
@Rui2guo please be advised that this is covered in our latest release v1.0.10:
 https://bitcoinsv.io/2021/11/25/upgrades-bsv-v1-0-10-mapi-v1-4-0/
