### ISSUE TITLE
estimatefee always returns -1

### ISSUE THREAD

**Issue by xloem** [bitcoin-sv/bitcoin-sv#85]
```
$ bitcoin-cli estimatefee 6
-1
```

It seems the result is _always_ -1, regardless of anything else.

**Comment by Danconnolly** [comment]
This command will be removed. The purpose of this command is to estimate the fee required for a transaction to be confirmed within a certain number of blocks. The goal of Bitcoin SV is that a transaction will always be included in the next block. Detailed fee information will be exposed by the Merchant API.
