### ISSUE TITLE
What version is needed for 24th of July BSV Upgrade (Quasar)?

### ISSUE THREAD

**Issue by c0deright** [bitcoin-sv/bitcoin-sv#86]
Regarding the Quasar Upgrade I would like to know which version of bitcoin-sv a **non-miner** needs to run.

In the articles published at

* https://bitcoinsv.io/2019/04/17/the-roadmap-to-genesis-part-1/
* https://bitcoinsv.io/2019/07/13/quasar-upgrade-24th-july-recommendations-roadmap-to-genesis-part-2/

there is no mention as to what version is the minimum requirement for the 24th of July Fork.

Is 0.1.1 with no modifications to `bitcoin.conf` regarding max blocksize safe?
Or is 0.2.x a requirement?

For the future: Please specify in your articles the minimum requirements so it's absolutely clear which version will work and which not.

Thank you.

**Comment by shadders** [comment]
V0.2.0 or V0.2.1

Yes it would have been helpful if we'd put it in thos articles. Although
it's specified in release notes of both versions. Generally you'd want to
run with latest version anyway though.

**Comment by c0deright** [comment]
Thank you

**Comment by c0deright** [comment]
v0.2.0 contains this in rpc responses:

`"errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"`

Is this the same for v0.2.1?

**Comment by Danconnolly** [comment]
not sure why this was opened again. Closing.
