### ISSUE TITLE
compile error on centos 7

### ISSUE THREAD

**Issue by jerryxmm** [bitcoin-sv/bitcoin-sv#87]
This issue tracker is only for technical issues related to bitcoin-sv.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
make fail[src/init.cpp:1846:43: error: expected ‘)’ before ‘PRId64’]
![image](https://user-images.githubusercontent.com/13878704/61702989-47441800-ad73-11e9-90f6-11c26adb9446.png)

#### If so, please list the steps to reproduce below:
1.mkdir build && cmake ..
2.make

Temporary solution:
1.add below code:
#include <inttypes.h>

**Comment by Danconnolly** [comment]
Thank you, this is fixed in the next version.
