### ISSUE TITLE
scheduler thread interrupt

### ISSUE THREAD

**Issue by love386** [bitcoin-sv/bitcoin-sv#89]
How to upgrade version 0.1.1.0 to 0.2.1

**Comment by Danconnolly** [comment]
Please download the new binaries from http://download.bitcoinsv.io/bitcoinsv/0.2.1/, verify them, and then replace the old binaries with the new ones. After this is done, restart the bitcoin daemon.

**Comment by Danconnolly** [comment]
Old, closing.
