### ISSUE TITLE
About “mempoolminfee”

### ISSUE THREAD

**Issue by jerryxmm** [bitcoin-sv/bitcoin-sv#90]
This issue tracker is only for technical issues related to bitcoin-sv.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
“mempoolminfee” will grow up if "usage" > "mempool".
1.any way to clear  “mempoolminfee” without restart fullnode?(I have check the code,is seems no rpc command or other way to clear mempoolminfee.)

2.can "mempoolminfee" automatic adapt usage?

3.my fullnode is not miner fullnode,I just use it to broadcast my transaction, so I don't want to increase mempool's configuration. 

![getmempoolinfo](https://user-images.githubusercontent.com/13878704/62098722-1f4a3c80-b2be-11e9-98e8-20bd8de95db9.jpg)

**Comment by Danconnolly** [comment]
No, there is no method to clear the mempoolminfee without restarting the node.

It will go down by itself with time but it will take a while.

**Comment by jerryxmm** [comment]
Ok, Thank you for your reply.
