### ISSUE TITLE
REST JSON get empty

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin-sv/bitcoin-sv#91]
`curl http://127.0.0.1:17179/rest/block/0000000000000000056169089b58d52cd82a2a04b83cae62a37aaab3272ab696.json`

return empty ...

**Comment by Cronus11** [comment]
Same issue, other blocks as well. For example:
0000000000000000039ddb56d7430383a7ef8db4f5b41c636d3eb02738a4bb54

**Comment by JokerCatz** [comment]
@Cronus11 "other blocks as well" ... you are so funny ... and another BTC chain like : LTC / BCH / BTG / ZCASH ... all blocks as well , so you mean this is not bug ? you are so ridiculous ...

**Comment by JokerCatz** [comment]
I think this is not good for BCHSV ... it too many bug and many people call this shit-coin ... include like this

https://twitter.com/BitMEXResearch/status/1154065637649596419

if here will not fix this bug ... I'll recommend many exchange side include our exchange services to leave BCHSV ...

**Comment by Cronus11** [comment]
> @Cronus11 "other blocks as well" ... you are so funny ... and another BTC chain like : LTC / BCH / BTG / ZCASH ... all blocks as well , so you mean this is not bug ? you are so ridiculous ...

If you'd search the block hash (https://bsvexplorer.info/#/block/0000000000000000039ddb56d7430383a7ef8db4f5b41c636d3eb02738a4bb54), you'd see this is also a SV block which also returns nothing through the REST API. 

I never even mentioned other chains. I'd suggest asking for clarification instead of behaving like this if you do not understand what someone is saying.

**Comment by JokerCatz** [comment]
I need say ... HA ... HA ... HA ... you are so ... funny ... again

if I use BUcash 1.5.1.0 and sync it , use `invalidateblock` and
`reconsiderblock` to switch right chain , or just share SV blockchain data to BUcash , it will return non-empty JSON include
`0000000000000000056169089b58d52cd82a2a04b83cae62a37aaab3272ab696`
and all another blocks , it work very will

bug only be bug ... not feature ...... [ if you do not understand what someone is saying ]

**Comment by JokerCatz** [comment]
bye BCHSV

**Comment by Danconnolly** [comment]
Thank you. This error is known and is caused by the block being 256MB.

**Comment by Danconnolly** [comment]
Its fixed in the next version which will be released soon:
![image](https://user-images.githubusercontent.com/2034127/65338169-e9dd1380-dbc9-11e9-88c9-b5e800aaafda.png)
