### ISSUE TITLE
BSV sent to segwit address recovery

### ISSUE THREAD

**Issue by niulingyun** [bitcoin-sv/bitcoin-sv#94]
Hi,
    I sent some BSV to a bitcoin segwit address start with a 3, and I got the privateKey of the bitcoin address, How could I recovery it?
    I've searched many pages, but got no idea.
    I have tried this way: import the bitcoin wif privateKey to bsv, but it generate another address. So how could I convert  bitcoin's privateKey to bsv's privateKey?  how could I recover those coins? Thanks.

**Comment by dannybitgo** [comment]
+1 on this issue.

BCH allows recovery of funds sent to BTC segwit addresses, but they only require the redeem script (no signature) and they must be directly mined by a miner (can't just broadcast it). 

Where does BSV stand on this?

**Comment by Danconnolly** [comment]
@niulingyun please e-mail support@bitcoinsv.io

**Comment by dannybitgo** [comment]
support@bitcoinsv.io is unresponsive - hoping some devs here can help

**Comment by dannybitgo** [comment]
@niulingyun It appears that recovering BSV sent to BTC segwit is possible - we just had a customer's fund's get swept.

However. DO NOT USE THE BTC ADDRESS ON THE BTC CHAIN. If you spend from the BTC address on the BTC chain, you reveal your redeem script, which enables any miner to sweep your BSV funds.

@niulingyun I'm willing to help you out as I've helped construct these types of recoveries in the past, will DM you

**Comment by niulingyun** [comment]
> @niulingyun It appears that recovering BSV sent to BTC segwit is possible - we just had a customer's fund's get swept.
> 
> However. DO NOT USE THE BTC ADDRESS ON THE BTC CHAIN. If you spend from the BTC address on the BTC chain, you reveal your redeem script, which enables any miner to sweep your BSV funds.
> 
> @niulingyun I'm willing to help you out as I've helped construct these types of recoveries in the past, will DM you

How to reach you?

**Comment by Danconnolly** [comment]
Please be careful sharing information with others, including public keys. 

I will check up on the support e-mail account but it will take another day or two.

**Comment by niulingyun** [comment]
Still got no response.

**Comment by niulingyun** [comment]
> Please be careful sharing information with others, including public keys.
> 
> I will check up on the support e-mail account but it will take another day or two.

Hi，Still got no response  from the support. please help.

**Comment by niulingyun** [comment]
> I will check up on the support e-mail account but it will take another day or two.

please help

**Comment by Danconnolly** [comment]
Replied by e-mail.
