### ISSUE TITLE
`getbalance` RPC method returns `Method not found` error

### ISSUE THREAD

**Issue by hugorut** [bitcoin-sv/bitcoin-sv#99]
### Describe the issue
`getbalance` method returns `Method not found` from RPC gateway.

#### If so, please list the steps to reproduce below:
1. spin up a bitcoin-sv daemon from 0.2.1 release
2. `curl -d '{"jsonrpc": "2.0", "method": "getbalance", "params": ["169BgJcHBFnnagWwzK5PemC7nYjc3EbMov"], "id": 1 }' localhost`
3. observe output

### Expected behaviour
I expected to see a `getbalance` output based on the fact that this is included in bitcoin-core and works in bitcoin-sv with the `bicoin-cli`. Furthermore the method is listend under the client.cpp in rpc.

```
{
  "result": "12.000 BTC"
}
```
### Actual behaviour
Tell us what happens instead
`{"result":null,"error":{"code":-32601,"message":"Method not found"},"id":1}`

### What version of bitcoin-sv are you using?
0.2.1

bitcoin.conf:

```
server=1
rpcallowip=0.0.0.0/0
printtoconsole=1
txindex=1
```

**Comment by Danconnolly** [comment]
Is the wallet disabled in your version?

This could be because:

- your bitcoin.conf has `disablewallet=1` in it
- bitcoind was started with the option `-disablewallet`
- you have compiled your own bitcoind without wallet support

**Comment by Danconnolly** [comment]
Tested with version 0.2.2 and it works.
![image](https://user-images.githubusercontent.com/2034127/68676387-37d31f80-055a-11ea-8fd2-42c078eb9ee4.png)

**Comment by hugorut** [comment]
Wallet services were being overwritten by an external config, my apologies
